const category = { id: "verbs-advanced", label: "Advanced Verbs", css_class: "cat-verbs-advanced", group_name: "Verbs" };

const cards = [
  { pt: "Alcançar", en: "To reach / To achieve", category_id: "verbs-advanced" },
  { pt: "Atingir", en: "To reach / To hit", category_id: "verbs-advanced" },
  { pt: "Superar", en: "To overcome", category_id: "verbs-advanced" },
  { pt: "Enfrentar", en: "To face / To confront", category_id: "verbs-advanced" },
  { pt: "Suportar", en: "To endure / To stand", category_id: "verbs-advanced" },
  { pt: "Aguentar", en: "To handle / To bear", category_id: "verbs-advanced" },
  { pt: "Resistir", en: "To resist", category_id: "verbs-advanced" },
  { pt: "Render", en: "To yield / To surrender", category_id: "verbs-advanced" },
  { pt: "Desistir", en: "To give up", category_id: "verbs-advanced" },
  { pt: "Arriscar", en: "To risk", category_id: "verbs-advanced" },
  { pt: "Beneficiar", en: "To benefit", category_id: "verbs-advanced" },
  { pt: "Desperdiçar", en: "To waste", category_id: "verbs-advanced" },
  { pt: "Acumular", en: "To accumulate", category_id: "verbs-advanced" },
  { pt: "Espalhar", en: "To spread", category_id: "verbs-advanced" },
  { pt: "Encolher", en: "To shrink", category_id: "verbs-advanced" },
  { pt: "Esticar", en: "To stretch / To extend", category_id: "verbs-advanced" },
  { pt: "Dobrar", en: "To fold / To double", category_id: "verbs-advanced" },
  { pt: "Embrulhar", en: "To wrap", category_id: "verbs-advanced" },
  { pt: "Desembrulhar", en: "To unwrap", category_id: "verbs-advanced" },
  { pt: "Pendurar", en: "To hang", category_id: "verbs-advanced" },
  { pt: "Amarrar", en: "To tie", category_id: "verbs-advanced" },
  { pt: "Desamarrar", en: "To untie", category_id: "verbs-advanced" },
  { pt: "Caber", en: "To fit", category_id: "verbs-advanced" },
  { pt: "Pertencer", en: "To belong", category_id: "verbs-advanced" },
  { pt: "Depender", en: "To depend", category_id: "verbs-advanced" },
  { pt: "Influenciar", en: "To influence", category_id: "verbs-advanced" },
  { pt: "Contribuir", en: "To contribute", category_id: "verbs-advanced" },
  { pt: "Participar", en: "To participate", category_id: "verbs-advanced" },
  { pt: "Colaborar", en: "To collaborate", category_id: "verbs-advanced" },
  { pt: "Liderar", en: "To lead", category_id: "verbs-advanced" },
  { pt: "Obedecer", en: "To obey", category_id: "verbs-advanced" },
  { pt: "Trair", en: "To betray", category_id: "verbs-advanced" },
  { pt: "Enganar", en: "To deceive / To trick", category_id: "verbs-advanced" },
  { pt: "Roubar", en: "To steal / To rob", category_id: "verbs-advanced" },
  { pt: "Deter", en: "To detain / To stop", category_id: "verbs-advanced" },
  { pt: "Fugir", en: "To flee / To escape", category_id: "verbs-advanced" },
  { pt: "Perseguir", en: "To chase / To pursue", category_id: "verbs-advanced" },
  { pt: "Investigar", en: "To investigate", category_id: "verbs-advanced" },
  { pt: "Comprovar", en: "To prove / To confirm", category_id: "verbs-advanced" },
  { pt: "Testemunhar", en: "To witness", category_id: "verbs-advanced" },
  { pt: "Jurar", en: "To swear", category_id: "verbs-advanced" },
  { pt: "Herdar", en: "To inherit", category_id: "verbs-advanced" },
  { pt: "Envelhecer", en: "To age / To grow old", category_id: "verbs-advanced" },
  { pt: "Amadurecer", en: "To mature / To ripen", category_id: "verbs-advanced" },
  { pt: "Adoecer", en: "To get sick", category_id: "verbs-advanced" },
  { pt: "Emagrecer", en: "To lose weight", category_id: "verbs-advanced" },
  { pt: "Engordar", en: "To gain weight", category_id: "verbs-advanced" },
  { pt: "Fortalecer", en: "To strengthen", category_id: "verbs-advanced" },
  { pt: "Enfraquecer", en: "To weaken", category_id: "verbs-advanced" },
  { pt: "Transformar", en: "To transform", category_id: "verbs-advanced" }
];

module.exports = { categories: [category], cards };
