const category = { id: "verbs-common", label: "Common Verbs", css_class: "cat-verbs-common", group_name: "Verbs" };

const cards = [
  { pt: "Correr", en: "To run", category_id: "verbs-common" },
  { pt: "Abrir", en: "To open", category_id: "verbs-common" },
  { pt: "Fechar", en: "To close", category_id: "verbs-common" },
  { pt: "Pagar", en: "To pay", category_id: "verbs-common" },
  { pt: "Vender", en: "To sell", category_id: "verbs-common" },
  { pt: "Ajudar", en: "To help", category_id: "verbs-common" },
  { pt: "Mudar", en: "To change / To move", category_id: "verbs-common" },
  { pt: "Usar", en: "To use", category_id: "verbs-common" },
  { pt: "Tentar", en: "To try", category_id: "verbs-common" },
  { pt: "Acontecer", en: "To happen", category_id: "verbs-common" },
  { pt: "Jogar", en: "To play (games/sports)", category_id: "verbs-common" },
  { pt: "Tocar", en: "To touch / To play (music)", category_id: "verbs-common" },
  { pt: "Andar", en: "To walk (in motion)", category_id: "verbs-common" },
  { pt: "Caminhar", en: "To walk (physical)", category_id: "verbs-common" },
  { pt: "Viver", en: "To have life (be alive)", category_id: "verbs-common" },
  { pt: "Morrer", en: "To die", category_id: "verbs-common" },
  { pt: "Perder", en: "To lose", category_id: "verbs-common" },
  { pt: "Ganhar", en: "To win / To earn", category_id: "verbs-common" },
  { pt: "Seguir", en: "To follow", category_id: "verbs-common" },
  { pt: "Criar", en: "To create", category_id: "verbs-common" },
  { pt: "Mandar", en: "To send / To order", category_id: "verbs-common" },
  { pt: "Receber", en: "To receive", category_id: "verbs-common" },
  { pt: "Entrar", en: "To enter", category_id: "verbs-common" },
  { pt: "Cair", en: "To fall", category_id: "verbs-common" },
  { pt: "Escolher", en: "To choose", category_id: "verbs-common" },
  { pt: "Continuar", en: "To continue", category_id: "verbs-common" },
  { pt: "Aprender", en: "To learn", category_id: "verbs-common" },
  { pt: "Ensinar", en: "To teach", category_id: "verbs-common" },
  { pt: "Contar", en: "To count / To tell", category_id: "verbs-common" },
  { pt: "Mostrar", en: "To show", category_id: "verbs-common" },
  { pt: "Servir", en: "To serve", category_id: "verbs-common" },
  { pt: "Trazer", en: "To bring", category_id: "verbs-common" },
  { pt: "Pôr", en: "To put", category_id: "verbs-common" },
  { pt: "Tirar", en: "To take off / To remove", category_id: "verbs-common" },
  { pt: "Buscar", en: "To search / To pick up", category_id: "verbs-common" },
  { pt: "Subir", en: "To go up / To climb", category_id: "verbs-common" },
  { pt: "Descer", en: "To go down", category_id: "verbs-common" },
  { pt: "Cortar", en: "To cut", category_id: "verbs-common" },
  { pt: "Guardar", en: "To keep / To save", category_id: "verbs-common" },
  { pt: "Ligar", en: "To call / To turn on", category_id: "verbs-common" },
  { pt: "Desligar", en: "To hang up / To turn off", category_id: "verbs-common" },
  { pt: "Dirigir", en: "To drive", category_id: "verbs-common" },
  { pt: "Parar", en: "To stop", category_id: "verbs-common" },
  { pt: "Terminar", en: "To finish / To end (formal)", category_id: "verbs-common" },
  { pt: "Explicar", en: "To explain", category_id: "verbs-common" },
  { pt: "Responder", en: "To answer / To reply", category_id: "verbs-common" },
  { pt: "Esquecer", en: "To forget", category_id: "verbs-common" },
  { pt: "Cuidar", en: "To take care of", category_id: "verbs-common" },
  { pt: "Preocupar", en: "To worry", category_id: "verbs-common" },
  { pt: "Acordar", en: "To wake up", category_id: "verbs-common" },
  { pt: "Trocar", en: "To exchange / To switch", category_id: "verbs-common" }
];

module.exports = { categories: [category], cards };
