const category = { id: "verbs-essential", label: "Essential Verbs", css_class: "cat-verbs-essential", group_name: "Verbs" };

const cards = [
  { pt: "Ser", en: "To be (permanent)", category_id: "verbs-essential" },
  { pt: "Estar", en: "To be (temporary)", category_id: "verbs-essential" },
  { pt: "Ter", en: "To have", category_id: "verbs-essential" },
  { pt: "Fazer", en: "To do / To make", category_id: "verbs-essential" },
  { pt: "Ir", en: "To go", category_id: "verbs-essential" },
  { pt: "Poder", en: "To be able to / Can", category_id: "verbs-essential" },
  { pt: "Dizer", en: "To say / To tell", category_id: "verbs-essential" },
  { pt: "Dar", en: "To give", category_id: "verbs-essential" },
  { pt: "Saber", en: "To know (facts)", category_id: "verbs-essential" },
  { pt: "Querer", en: "To want", category_id: "verbs-essential" },
  { pt: "Ver", en: "To see", category_id: "verbs-essential" },
  { pt: "Vir", en: "To come", category_id: "verbs-essential" },
  { pt: "Dever", en: "Should / To owe", category_id: "verbs-essential" },
  { pt: "Ficar", en: "To stay / To become", category_id: "verbs-essential" },
  { pt: "Falar", en: "To speak / To talk", category_id: "verbs-essential" },
  { pt: "Deixar", en: "To leave / To let", category_id: "verbs-essential" },
  { pt: "Passar", en: "To pass / To spend (time)", category_id: "verbs-essential" },
  { pt: "Chegar", en: "To arrive", category_id: "verbs-essential" },
  { pt: "Encontrar", en: "To find / To meet", category_id: "verbs-essential" },
  { pt: "Pensar", en: "To think", category_id: "verbs-essential" },
  { pt: "Levar", en: "To take / To carry", category_id: "verbs-essential" },
  { pt: "Conhecer", en: "To know (people/places) / to meet", category_id: "verbs-essential" },
  { pt: "Precisar", en: "To need", category_id: "verbs-essential" },
  { pt: "Começar", en: "To start / To begin", category_id: "verbs-essential" },
  { pt: "Pedir", en: "To ask for / To order", category_id: "verbs-essential" },
  { pt: "Parecer", en: "To seem / To appear", category_id: "verbs-essential" },
  { pt: "Acreditar", en: "To believe", category_id: "verbs-essential" },
  { pt: "Olhar", en: "To look", category_id: "verbs-essential" },
  { pt: "Chamar", en: "To call / to name", category_id: "verbs-essential" },
  { pt: "Trabalhar", en: "To work", category_id: "verbs-essential" },
  { pt: "Comer", en: "To eat", category_id: "verbs-essential" },
  { pt: "Beber", en: "To drink", category_id: "verbs-essential" },
  { pt: "Dormir", en: "To sleep", category_id: "verbs-essential" },
  { pt: "Morar", en: "To live (reside)", category_id: "verbs-essential" },
  { pt: "Esperar", en: "To wait / To hope", category_id: "verbs-essential" },
  { pt: "Gostar", en: "To like", category_id: "verbs-essential" },
  { pt: "Achar", en: "To think / To find", category_id: "verbs-essential" },
  { pt: "Entender", en: "To understand", category_id: "verbs-essential" },
  { pt: "Colocar", en: "To put / To place", category_id: "verbs-essential" },
  { pt: "Perguntar", en: "To ask (a question)", category_id: "verbs-essential" },
  { pt: "Sentir", en: "To feel", category_id: "verbs-essential" },
  { pt: "Comprar", en: "To buy", category_id: "verbs-essential" },
  { pt: "Sair", en: "To leave / To go out", category_id: "verbs-essential" },
  { pt: "Tomar", en: "To take / To drink", category_id: "verbs-essential" },
  { pt: "Lembrar", en: "To remember", category_id: "verbs-essential" },
  { pt: "Voltar", en: "To return / To come back", category_id: "verbs-essential" },
  { pt: "Acabar", en: "To finish / To end (broad)", category_id: "verbs-essential" },
  { pt: "Ouvir", en: "To hear / To listen", category_id: "verbs-essential" },
  { pt: "Escutar", en: "To hear / To listen", category_id: "verbs-essential" },
  { pt: "Ler", en: "To read", category_id: "verbs-essential" },
  { pt: "Escrever", en: "To write", category_id: "verbs-essential" }
];

module.exports = { categories: [category], cards };
