const category = { id: "verbs-everyday", label: "Everyday Verbs", css_class: "cat-verbs-everyday", group_name: "Verbs" };

const cards = [
  { pt: "Prender", en: "To arrest / To attach", category_id: "verbs-everyday" },
  { pt: "Virar", en: "To turn / To become", category_id: "verbs-everyday" },
  { pt: "Manter", en: "To maintain / To keep", category_id: "verbs-everyday" },
  { pt: "Conseguir", en: "To manage / To get", category_id: "verbs-everyday" },
  { pt: "Devolver", en: "To return (something)", category_id: "verbs-everyday" },
  { pt: "Cozinhar", en: "To cook", category_id: "verbs-everyday" },
  { pt: "Lavar", en: "To wash", category_id: "verbs-everyday" },
  { pt: "Limpar", en: "To clean", category_id: "verbs-everyday" },
  { pt: "Nadar", en: "To swim", category_id: "verbs-everyday" },
  { pt: "Viajar", en: "To travel", category_id: "verbs-everyday" },
  { pt: "Descansar", en: "To rest", category_id: "verbs-everyday" },
  { pt: "Vestir", en: "To wear / To dress", category_id: "verbs-everyday" },
  { pt: "Crescer", en: "To grow", category_id: "verbs-everyday" },
  { pt: "Sofrer", en: "To suffer", category_id: "verbs-everyday" },
  { pt: "Rir", en: "To laugh", category_id: "verbs-everyday" },
  { pt: "Chorar", en: "To cry", category_id: "verbs-everyday" },
  { pt: "Gritar", en: "To shout / To scream", category_id: "verbs-everyday" },
  { pt: "Cantar", en: "To sing", category_id: "verbs-everyday" },
  { pt: "Dançar", en: "To dance", category_id: "verbs-everyday" },
  { pt: "Desenhar", en: "To draw", category_id: "verbs-everyday" },
  { pt: "Pintar", en: "To paint", category_id: "verbs-everyday" },
  { pt: "Namorar", en: "To date / To be in a relationship", category_id: "verbs-everyday" },
  { pt: "Casar", en: "To marry", category_id: "verbs-everyday" },
  { pt: "Brigar", en: "To fight / To argue", category_id: "verbs-everyday" },
  { pt: "Abraçar", en: "To hug", category_id: "verbs-everyday" },
  { pt: "Beijar", en: "To kiss", category_id: "verbs-everyday" },
  { pt: "Sorrir", en: "To smile", category_id: "verbs-everyday" },
  { pt: "Mentir", en: "To lie", category_id: "verbs-everyday" },
  { pt: "Prometer", en: "To promise", category_id: "verbs-everyday" },
  { pt: "Decidir", en: "To decide", category_id: "verbs-everyday" },
  { pt: "Permitir", en: "To allow / To permit", category_id: "verbs-everyday" },
  { pt: "Proibir", en: "To prohibit / To forbid", category_id: "verbs-everyday" },
  { pt: "Oferecer", en: "To offer", category_id: "verbs-everyday" },
  { pt: "Aceitar", en: "To accept", category_id: "verbs-everyday" },
  { pt: "Recusar", en: "To refuse", category_id: "verbs-everyday" },
  { pt: "Emprestar", en: "To lend", category_id: "verbs-everyday" },
  { pt: "Pegar", en: "To grab / To catch", category_id: "verbs-everyday" },
  { pt: "Jogar fora", en: "To throw away", category_id: "verbs-everyday" },
  { pt: "Quebrar", en: "To break", category_id: "verbs-everyday" },
  { pt: "Consertar", en: "To fix / To repair", category_id: "verbs-everyday" },
  { pt: "Construir", en: "To build", category_id: "verbs-everyday" },
  { pt: "Destruir", en: "To destroy", category_id: "verbs-everyday" },
  { pt: "Empurrar", en: "To push", category_id: "verbs-everyday" },
  { pt: "Puxar", en: "To pull", category_id: "verbs-everyday" },
  { pt: "Carregar", en: "To carry / To charge", category_id: "verbs-everyday" },
  { pt: "Soltar", en: "To release / To let go", category_id: "verbs-everyday" },
  { pt: "Esconder", en: "To hide", category_id: "verbs-everyday" },
  { pt: "Procurar", en: "To look for / To search", category_id: "verbs-everyday" },
  { pt: "Descobrir", en: "To discover / To find out", category_id: "verbs-everyday" },
  { pt: "Cobrir", en: "To cover", category_id: "verbs-everyday" }
];

module.exports = { categories: [category], cards };
