const category = { id: "verbs-expanding", label: "Expanding Verbs", css_class: "cat-verbs-expanding", group_name: "Verbs" };

const cards = [
  { pt: "Imaginar", en: "To imagine", category_id: "verbs-expanding" },
  { pt: "Sonhar", en: "To dream", category_id: "verbs-expanding" },
  { pt: "Desejar", en: "To wish / To desire", category_id: "verbs-expanding" },
  { pt: "Respeitar", en: "To respect", category_id: "verbs-expanding" },
  { pt: "Confiar", en: "To trust", category_id: "verbs-expanding" },
  { pt: "Duvidar", en: "To doubt", category_id: "verbs-expanding" },
  { pt: "Arrepender", en: "To regret", category_id: "verbs-expanding" },
  { pt: "Perdoar", en: "To forgive", category_id: "verbs-expanding" },
  { pt: "Culpar", en: "To blame", category_id: "verbs-expanding" },
  { pt: "Elogiar", en: "To compliment / To praise", category_id: "verbs-expanding" },
  { pt: "Criticar", en: "To criticize", category_id: "verbs-expanding" },
  { pt: "Apoiar", en: "To support", category_id: "verbs-expanding" },
  { pt: "Incentivar", en: "To encourage", category_id: "verbs-expanding" },
  { pt: "Convencer", en: "To convince", category_id: "verbs-expanding" },
  { pt: "Concordar", en: "To agree", category_id: "verbs-expanding" },
  { pt: "Discordar", en: "To disagree", category_id: "verbs-expanding" },
  { pt: "Discutir", en: "To discuss / To argue", category_id: "verbs-expanding" },
  { pt: "Negociar", en: "To negotiate", category_id: "verbs-expanding" },
  { pt: "Exigir", en: "To demand", category_id: "verbs-expanding" },
  { pt: "Insistir", en: "To insist", category_id: "verbs-expanding" },
  { pt: "Avisar", en: "To warn / To notify", category_id: "verbs-expanding" },
  { pt: "Informar", en: "To inform", category_id: "verbs-expanding" },
  { pt: "Anunciar", en: "To announce", category_id: "verbs-expanding" },
  { pt: "Publicar", en: "To publish", category_id: "verbs-expanding" },
  { pt: "Traduzir", en: "To translate", category_id: "verbs-expanding" },
  { pt: "Pronunciar", en: "To pronounce", category_id: "verbs-expanding" },
  { pt: "Soletrar", en: "To spell", category_id: "verbs-expanding" },
  { pt: "Assinar", en: "To sign", category_id: "verbs-expanding" },
  { pt: "Imprimir", en: "To print", category_id: "verbs-expanding" },
  { pt: "Copiar", en: "To copy", category_id: "verbs-expanding" },
  { pt: "Colar", en: "To paste / To glue", category_id: "verbs-expanding" },
  { pt: "Apagar", en: "To erase / To turn off", category_id: "verbs-expanding" },
  { pt: "Salvar", en: "To save", category_id: "verbs-expanding" },
  { pt: "Baixar", en: "To download / To lower", category_id: "verbs-expanding" },
  { pt: "Instalar", en: "To install", category_id: "verbs-expanding" },
  { pt: "Funcionar", en: "To work / To function", category_id: "verbs-expanding" },
  { pt: "Estragar", en: "To break / To ruin", category_id: "verbs-expanding" },
  { pt: "Tropeçar", en: "To trip / To stumble", category_id: "verbs-expanding" },
  { pt: "Escorregar", en: "To slip", category_id: "verbs-expanding" },
  { pt: "Derrubar", en: "To knock down / To spill", category_id: "verbs-expanding" },
  { pt: "Derramar", en: "To spill / To pour", category_id: "verbs-expanding" },
  { pt: "Queimar", en: "To burn", category_id: "verbs-expanding" },
  { pt: "Congelar", en: "To freeze", category_id: "verbs-expanding" },
  { pt: "Ferver", en: "To boil", category_id: "verbs-expanding" },
  { pt: "Assar", en: "To roast / To bake", category_id: "verbs-expanding" },
  { pt: "Fritar", en: "To fry", category_id: "verbs-expanding" },
  { pt: "Temperar", en: "To season", category_id: "verbs-expanding" },
  { pt: "Picar", en: "To chop / To sting", category_id: "verbs-expanding" },
  { pt: "Refogar", en: "To sauté", category_id: "verbs-expanding" },
  { pt: "Provar", en: "To taste / To prove", category_id: "verbs-expanding" }
];

module.exports = { categories: [category], cards };
