const category = { id: "verbs-practical", label: "Practical Verbs", css_class: "cat-verbs-practical", group_name: "Verbs" };

const cards = [
  { pt: "Enviar", en: "To send", category_id: "verbs-practical" },
  { pt: "Recomendar", en: "To recommend", category_id: "verbs-practical" },
  { pt: "Sugerir", en: "To suggest", category_id: "verbs-practical" },
  { pt: "Combinar", en: "To arrange / To match", category_id: "verbs-practical" },
  { pt: "Marcar", en: "To schedule / To mark", category_id: "verbs-practical" },
  { pt: "Cancelar", en: "To cancel", category_id: "verbs-practical" },
  { pt: "Atrasar", en: "To delay / To be late", category_id: "verbs-practical" },
  { pt: "Demorar", en: "To take long", category_id: "verbs-practical" },
  { pt: "Aproveitar", en: "To enjoy / To take advantage", category_id: "verbs-practical" },
  { pt: "Celebrar", en: "To celebrate", category_id: "verbs-practical" },
  { pt: "Convidar", en: "To invite", category_id: "verbs-practical" },
  { pt: "Visitar", en: "To visit", category_id: "verbs-practical" },
  { pt: "Passear", en: "To go for a walk / To stroll", category_id: "verbs-practical" },
  { pt: "Reservar", en: "To reserve / To book", category_id: "verbs-practical" },
  { pt: "Alugar", en: "To rent", category_id: "verbs-practical" },
  { pt: "Gastar", en: "To spend (money)", category_id: "verbs-practical" },
  { pt: "Economizar", en: "To save (money)", category_id: "verbs-practical" },
  { pt: "Investir", en: "To invest", category_id: "verbs-practical" },
  { pt: "Desenvolver", en: "To develop", category_id: "verbs-practical" },
  { pt: "Melhorar", en: "To improve", category_id: "verbs-practical" },
  { pt: "Piorar", en: "To worsen", category_id: "verbs-practical" },
  { pt: "Aumentar", en: "To increase", category_id: "verbs-practical" },
  { pt: "Diminuir", en: "To decrease", category_id: "verbs-practical" },
  { pt: "Juntar", en: "To join / To gather", category_id: "verbs-practical" },
  { pt: "Separar", en: "To separate", category_id: "verbs-practical" },
  { pt: "Misturar", en: "To mix", category_id: "verbs-practical" },
  { pt: "Dividir", en: "To divide / To share", category_id: "verbs-practical" },
  { pt: "Compartilhar", en: "To share", category_id: "verbs-practical" },
  { pt: "Proteger", en: "To protect", category_id: "verbs-practical" },
  { pt: "Defender", en: "To defend", category_id: "verbs-practical" },
  { pt: "Atacar", en: "To attack", category_id: "verbs-practical" },
  { pt: "Competir", en: "To compete", category_id: "verbs-practical" },
  { pt: "Treinar", en: "To train", category_id: "verbs-practical" },
  { pt: "Exercitar", en: "To exercise", category_id: "verbs-practical" },
  { pt: "Alongar", en: "To stretch", category_id: "verbs-practical" },
  { pt: "Respirar", en: "To breathe", category_id: "verbs-practical" },
  { pt: "Tossir", en: "To cough", category_id: "verbs-practical" },
  { pt: "Espirrar", en: "To sneeze", category_id: "verbs-practical" },
  { pt: "Doer", en: "To hurt / To ache", category_id: "verbs-practical" },
  { pt: "Curar", en: "To cure / To heal", category_id: "verbs-practical" },
  { pt: "Operar", en: "To operate", category_id: "verbs-practical" },
  { pt: "Examinar", en: "To examine", category_id: "verbs-practical" },
  { pt: "Pesar", en: "To weigh", category_id: "verbs-practical" },
  { pt: "Medir", en: "To measure", category_id: "verbs-practical" },
  { pt: "Comparar", en: "To compare", category_id: "verbs-practical" },
  { pt: "Organizar", en: "To organize", category_id: "verbs-practical" },
  { pt: "Planejar", en: "To plan", category_id: "verbs-practical" },
  { pt: "Preparar", en: "To prepare", category_id: "verbs-practical" },
  { pt: "Verificar", en: "To verify / To check", category_id: "verbs-practical" },
  { pt: "Confirmar", en: "To confirm", category_id: "verbs-practical" }
];

module.exports = { categories: [category], cards };
