const parts = [
  require("./fitness"),
  require("./vocab"),
  require("./traits"),
  require("./weather"),
  require("./daily"),
  require("./time"),
  require("./time-adverbs"),
  require("./places"),
  require("./random"),
  require("./fruits"),
  require("./vegetables"),
  require("./drinks"),
  require("./meals"),
  require("./spices"),
  require("./furniture"),
  require("./kitchen"),
  require("./clothing"),
  require("./bathroom"),
  require("./family"),
  require("./body"),
  require("./professions"),
  require("./animals"),
  require("./insects"),
  require("./plants"),
  require("./beach"),
  require("./transportation"),
  require("./travel"),
  require("./shops"),
  require("./school"),
  require("./electronics"),
  require("./tools"),
  require("./colors"),
  require("./emotions"),
  require("./instruments"),
];

const categories = parts.flatMap(p => p.categories);
const cards = parts.flatMap(p => p.cards);

module.exports = { categories, cards };
