const category = { id: "nouns-common", label: "Common Nouns", css_class: "cat-nouns-common", group_name: "Topics" };

const cards = [
  { pt: "Caminho", en: "Path / Way", category_id: "nouns-common" },
  { pt: "Guerra", en: "War", category_id: "nouns-common" },
  { pt: "Exemplo", en: "Example", category_id: "nouns-common" },
  { pt: "Pergunta", en: "Question", category_id: "nouns-common" },
  { pt: "Resposta", en: "Answer", category_id: "nouns-common" },
  { pt: "Razão", en: "Reason", category_id: "nouns-common" },
  { pt: "Voz", en: "Voice", category_id: "nouns-common" },
  { pt: "Luz", en: "Light", category_id: "nouns-common" },
  { pt: "Força", en: "Strength / Force", category_id: "nouns-common" },
  { pt: "Grupo", en: "Group", category_id: "nouns-common" },
  { pt: "Sentido", en: "Sense / Meaning", category_id: "nouns-common" },
  { pt: "Conta", en: "Bill / Account", category_id: "nouns-common" },
  { pt: "Direito", en: "Right (legal) / Law", category_id: "nouns-common" },
  { pt: "Língua", en: "Language / Tongue", category_id: "nouns-common" },
  { pt: "Chave", en: "Key", category_id: "nouns-common" },
  { pt: "Notícia", en: "News", category_id: "nouns-common" },
  { pt: "Carta", en: "Letter", category_id: "nouns-common" },
  { pt: "Número", en: "Number", category_id: "nouns-common" },
  { pt: "Igreja", en: "Church", category_id: "nouns-common" },
  { pt: "Morte", en: "Death", category_id: "nouns-common" },
  { pt: "Fogo", en: "Fire", category_id: "nouns-common" },
  { pt: "Sangue", en: "Blood", category_id: "nouns-common" },
  { pt: "Pedra", en: "Stone / Rock", category_id: "nouns-common" },
  { pt: "Falta", en: "Lack / Absence", category_id: "nouns-common" },
  { pt: "Vontade", en: "Will / Desire", category_id: "nouns-common" },
  { pt: "Poder", en: "Power", category_id: "nouns-common" },
  { pt: "Povo", en: "People / Nation", category_id: "nouns-common" },
  { pt: "Lei", en: "Law", category_id: "nouns-common" },
  { pt: "Festa", en: "Party / Celebration", category_id: "nouns-common" },
  { pt: "Paz", en: "Peace", category_id: "nouns-common" },
  { pt: "Sonho", en: "Dream", category_id: "nouns-common" },
  { pt: "Rosto", en: "Face", category_id: "nouns-common" },
  { pt: "Início", en: "Beginning / Start", category_id: "nouns-common" },
  { pt: "Sinal", en: "Signal / Sign", category_id: "nouns-common" },
  { pt: "Conhecimento", en: "Knowledge", category_id: "nouns-common" },
  { pt: "Conversa", en: "Conversation", category_id: "nouns-common" },
  { pt: "Erro", en: "Error / Mistake", category_id: "nouns-common" },
  { pt: "Escolha", en: "Choice", category_id: "nouns-common" },
  { pt: "Experiência", en: "Experience", category_id: "nouns-common" },
  { pt: "Futuro", en: "Future", category_id: "nouns-common" },
  { pt: "Passado", en: "Past", category_id: "nouns-common" },
  { pt: "Sucesso", en: "Success", category_id: "nouns-common" },
  { pt: "Perigo", en: "Danger", category_id: "nouns-common" },
  { pt: "Ajuda", en: "Help", category_id: "nouns-common" },
  { pt: "Mudança", en: "Change", category_id: "nouns-common" },
  { pt: "Segurança", en: "Safety / Security", category_id: "nouns-common" },
  { pt: "Saúde", en: "Health", category_id: "nouns-common" },
  { pt: "Diferença", en: "Difference", category_id: "nouns-common" },
  { pt: "Opinião", en: "Opinion", category_id: "nouns-common" },
  { pt: "Resultado", en: "Result", category_id: "nouns-common" },
];

module.exports = { categories: [category], cards };
