const category = { id: "nouns-modern", label: "Modern Nouns", css_class: "cat-nouns-modern", group_name: "Topics" };

const cards = [
  { pt: "Sintoma", en: "Symptom", category_id: "nouns-modern" },
  { pt: "Doença", en: "Illness / disease", category_id: "nouns-modern" },
  { pt: "Ferida", en: "Wound", category_id: "nouns-modern" },
  { pt: "Exame", en: "Exam (medical)", category_id: "nouns-modern" },
  { pt: "Passaporte", en: "Passport", category_id: "nouns-modern" },
  { pt: "Bagagem", en: "Luggage", category_id: "nouns-modern" },
  { pt: "Voo", en: "Flight", category_id: "nouns-modern" },
  { pt: "Hospedagem", en: "Lodging", category_id: "nouns-modern" },
  { pt: "Embarque", en: "Boarding", category_id: "nouns-modern" },
  { pt: "Alfândega", en: "Customs (border)", category_id: "nouns-modern" },
  { pt: "Destino", en: "Destination", category_id: "nouns-modern" },
  { pt: "Alegria", en: "Joy", category_id: "nouns-modern" },
  { pt: "Tristeza", en: "Sadness", category_id: "nouns-modern" },
  { pt: "Angústia", en: "Anguish", category_id: "nouns-modern" },
  { pt: "Orgulho", en: "Pride", category_id: "nouns-modern" },
  { pt: "Vergonha", en: "Shame / embarrassment", category_id: "nouns-modern" },
  { pt: "Solidão", en: "Loneliness", category_id: "nouns-modern" },
  { pt: "Paixão", en: "Passion", category_id: "nouns-modern" },
  { pt: "Garçom", en: "Waiter", category_id: "nouns-modern" },
  { pt: "Sobremesa", en: "Dessert", category_id: "nouns-modern" },
  { pt: "Prato principal", en: "Main dish", category_id: "nouns-modern" },
  { pt: "Tela", en: "Screen", category_id: "nouns-modern" },
  { pt: "Senha", en: "Password", category_id: "nouns-modern" },
  { pt: "Aplicativo", en: "App", category_id: "nouns-modern" },
  { pt: "Nuvem", en: "Cloud (storage)", category_id: "nouns-modern" },
  { pt: "Rede", en: "Network", category_id: "nouns-modern" },
  { pt: "Dispositivo", en: "Device", category_id: "nouns-modern" },
  { pt: "Preocupação", en: "Worry / concern", category_id: "nouns-modern" },
  { pt: "Desafio", en: "Challenge", category_id: "nouns-modern" },
  { pt: "Impacto", en: "Impact", category_id: "nouns-modern" },
  { pt: "Vantagem", en: "Advantage", category_id: "nouns-modern" },
  { pt: "Desvantagem", en: "Disadvantage", category_id: "nouns-modern" },
  { pt: "Realidade", en: "Reality", category_id: "nouns-modern" },
  { pt: "Expectativa", en: "Expectation", category_id: "nouns-modern" },
  { pt: "Propósito", en: "Purpose", category_id: "nouns-modern" },
  { pt: "Objetivo", en: "Goal / objective", category_id: "nouns-modern" },
  { pt: "Plano", en: "Plan", category_id: "nouns-modern" },
  { pt: "Progresso", en: "Progress", category_id: "nouns-modern" },
  { pt: "Avanço", en: "Advance / progress", category_id: "nouns-modern" },
  { pt: "Perda", en: "Loss", category_id: "nouns-modern" },
  { pt: "Ganho", en: "Gain", category_id: "nouns-modern" },
  { pt: "Risco", en: "Risk", category_id: "nouns-modern" },
  { pt: "Benefício", en: "Benefit", category_id: "nouns-modern" },
  { pt: "Preferência", en: "Preference", category_id: "nouns-modern" },
];

module.exports = { categories: [category], cards };
