const category = { id: "traits", label: "Traits & Descriptors", css_class: "cat-traits", group_name: "Topics" };

const cards = [
  { pt: "Chateado", en: "Upset / Annoyed", category_id: "traits" },
  { pt: "Gostoso", en: "Delicious / Hot (attractive)", category_id: "traits" },
  { pt: "Divertida", en: "Fun", category_id: "traits" },
  { pt: "Novo(a) / Velho(a)", en: "New / Old", category_id: "traits" },
  { pt: "Mais nova / Mais velha", en: "Younger / Older", category_id: "traits" },
  { pt: "Feliz / Alegre", en: "Happy / Cheerful", category_id: "traits" },
  { pt: "Triste", en: "Sad", category_id: "traits" },
  { pt: "Educado(a)", en: "Polite", category_id: "traits" },
  { pt: "Mal-educado(a)", en: "Rude / Impolite", category_id: "traits" },
  { pt: "Inteligente", en: "Intelligent / Smart", category_id: "traits" },
  { pt: "Burro(a)", en: "Dumb / Stupid", category_id: "traits" },
  { pt: "Calmo(a)", en: "Calm", category_id: "traits" },
  { pt: "Nervoso(a)", en: "Nervous / Anxious", category_id: "traits" },
  { pt: "Corajoso(a)", en: "Brave", category_id: "traits" },
  { pt: "Medroso(a)", en: "Cowardly / Fearful", category_id: "traits" },
  { pt: "Honesto(a)", en: "Honest", category_id: "traits" },
  { pt: "Mentiroso(a)", en: "Liar / Dishonest", category_id: "traits" },
  { pt: "Bonito(a)", en: "Handsome / Beautiful", category_id: "traits" },
  { pt: "Lindo(a)", en: "Pretty", category_id: "traits" },
  { pt: "Feio(a)", en: "Ugly", category_id: "traits" },
  { pt: "Alto(a)", en: "Tall", category_id: "traits" },
  { pt: "Baixo(a)", en: "Short", category_id: "traits" },
  { pt: "Magro(a)", en: "Thin / Slim", category_id: "traits" },
  { pt: "Gordo(a)", en: "Fat / Overweight", category_id: "traits" },
  { pt: "Divertido(a)", en: "Fun", category_id: "traits" },
  { pt: "Legal", en: "Cool", category_id: "traits" },
  { pt: "Chato(a)", en: "Boring", category_id: "traits" },
  { pt: "Simpático(a)", en: "Nice", category_id: "traits" },
  { pt: "Grosso(a)", en: "Rude", category_id: "traits" },
  { pt: "Ignorante", en: "Ignorant", category_id: "traits" },
  { pt: "Fofo(a)", en: "Cute", category_id: "traits" },
  { pt: "Irritante", en: "Irritating", category_id: "traits" },
  { pt: "Maravilhoso(a)", en: "Wonderful", category_id: "traits" },
  { pt: "Interessante", en: "Interesting", category_id: "traits" },
  { pt: "Forte", en: "Strong", category_id: "traits" },
  { pt: "Fraco(a)", en: "Weak", category_id: "traits" },
  { pt: "Animado(a)", en: "Excited", category_id: "traits" },
  { pt: "Desanimado(a)", en: "Not excited", category_id: "traits" },
  { pt: "Organizado(a)", en: "Organized", category_id: "traits" },
  { pt: "Desorganizado(a)", en: "Disorganized", category_id: "traits" },
  { pt: "Preguiçoso(a)", en: "Lazy", category_id: "traits" },
  { pt: "Paciente", en: "Patient", category_id: "traits" },
  { pt: "Tímido(a)", en: "Shy", category_id: "traits" },
  { pt: "Contente", en: "Content / Happy", category_id: "traits" },
  { pt: "Cansado(a)", en: "Tired", category_id: "traits" },
  { pt: "Entediado(a)", en: "Bored", category_id: "traits" },
  { pt: "Preocupado(a)", en: "Worried", category_id: "traits" }
];

module.exports = { categories: [category], cards };
