const category = { id: "estar-conj", label: "Estar Conjugations", css_class: "cat-estar-conj", group_name: "Conjugations" };

const cards = [
  { pt: "Eu estou", en: "I am (present)", category_id: "estar-conj" },
  { pt: "Você está", en: "You are (present)", category_id: "estar-conj" },
  { pt: "Ele/Ela está", en: "He/She is (present)", category_id: "estar-conj" },
  { pt: "Nós estamos", en: "We are (present)", category_id: "estar-conj" },
  { pt: "Vocês estão", en: "You all are (present)", category_id: "estar-conj" },
  { pt: "Eles/Elas estão", en: "They are (present)", category_id: "estar-conj" },
  { pt: "Eu estava", en: "I used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Você estava", en: "You used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Ele/Ela estava", en: "He/She used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Nós estávamos", en: "We used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Vocês estavam", en: "You all used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Eles/Elas estavam", en: "They used to be (imperfect)", category_id: "estar-conj" },
  { pt: "Eu estive", en: "I was (preterite)", category_id: "estar-conj" },
  { pt: "Você esteve", en: "You were (preterite)", category_id: "estar-conj" },
  { pt: "Ele/Ela esteve", en: "He/She was (preterite)", category_id: "estar-conj" },
  { pt: "Nós estivemos", en: "We were (preterite)", category_id: "estar-conj" },
  { pt: "Vocês estiveram", en: "You all were (preterite)", category_id: "estar-conj" },
  { pt: "Eles/Elas estiveram", en: "They were (preterite)", category_id: "estar-conj" },
  { pt: "Eu estaria", en: "I would be (conditional)", category_id: "estar-conj" },
  { pt: "Você estaria", en: "You would be (conditional)", category_id: "estar-conj" },
  { pt: "Ele/Ela estaria", en: "He/She would be (conditional)", category_id: "estar-conj" },
  { pt: "Nós estaríamos", en: "We would be (conditional)", category_id: "estar-conj" },
  { pt: "Vocês estariam", en: "You all would be (conditional)", category_id: "estar-conj" },
  { pt: "Eles/Elas estariam", en: "They would be (conditional)", category_id: "estar-conj" },
  { pt: "Eu esteja", en: "I am (present subjunctive)", category_id: "estar-conj" },
  { pt: "Você esteja", en: "You are (present subjunctive)", category_id: "estar-conj" },
  { pt: "Ele/Ela esteja", en: "He/She is (present subjunctive)", category_id: "estar-conj" },
  { pt: "Nós estejamos", en: "We are (present subjunctive)", category_id: "estar-conj" },
  { pt: "Vocês estejam", en: "You all are (present subjunctive)", category_id: "estar-conj" },
  { pt: "Eles/Elas estejam", en: "They are (present subjunctive)", category_id: "estar-conj" },
  { pt: "Eu estivesse", en: "I were (imperfect subjunctive)", category_id: "estar-conj" },
  { pt: "Você estivesse", en: "You were (imperfect subjunctive)", category_id: "estar-conj" },
  { pt: "Ele/Ela estivesse", en: "He/She were (imperfect subjunctive)", category_id: "estar-conj" },
  { pt: "Nós estivéssemos", en: "We were (imperfect subjunctive)", category_id: "estar-conj" },
  { pt: "Vocês estivessem", en: "You all were (imperfect subjunctive)", category_id: "estar-conj" },
  { pt: "Eles/Elas estivessem", en: "They were (imperfect subjunctive)", category_id: "estar-conj" }
];

module.exports = { categories: [category], cards };
