const categories = [
  { id: "fitness", label: "Fitness", css_class: "cat-fitness", group_name: "Topics" },
  { id: "vocab", label: "Vocabulary", css_class: "cat-vocab", group_name: "Topics" },
  { id: "phrases", label: "Phrases", css_class: "cat-phrases", group_name: "Topics" },
  { id: "verbs", label: "Verbs", css_class: "cat-verbs", group_name: "Topics" },
  { id: "weather", label: "Weather", css_class: "cat-weather", group_name: "Topics" },
  { id: "daily", label: "Daily Life", css_class: "cat-daily", group_name: "Topics" },
  { id: "time", label: "Time & Days", css_class: "cat-time", group_name: "Topics" },
  { id: "bday", label: "Birthday", css_class: "cat-bday", group_name: "Topics" },
  { id: "quase", label: "Aula Mar 16 (Quase/Almost)", css_class: "cat-quase", group_name: "Aulas" },
  { id: "ir-phrases", label: "IR Phrases", css_class: "cat-ir-phrases", group_name: "IR" },
  { id: "ir-conj", label: "IR Conjugations", css_class: "cat-ir-conj", group_name: "IR" },
  { id: "ler-conj", label: "Ler Conjugations", css_class: "cat-ler-conj", group_name: "Conjugations" },
  { id: "esquecer-conj", label: "Esquecer Conjugations", css_class: "cat-esquecer-conj", group_name: "Conjugations" },
  { id: "lembrar-conj", label: "Lembrar Conjugations", css_class: "cat-lembrar-conj", group_name: "Conjugations" },
  { id: "dizer-conj", label: "Dizer Conjugations", css_class: "cat-dizer-conj", group_name: "Conjugations" },
  { id: "ser-conj", label: "Ser Conjugations", css_class: "cat-ser-conj", group_name: "Conjugations" },
  { id: "estar-conj", label: "Estar Conjugations", css_class: "cat-estar-conj", group_name: "Conjugations" },
  { id: "esperar-conj", label: "Esperar Conjugations", css_class: "cat-esperar-conj", group_name: "Conjugations" },
  { id: "buscar-conj", label: "Buscar Conjugations", css_class: "cat-buscar-conj", group_name: "Conjugations" },
  { id: "tomar-conj", label: "Tomar Conjugations", css_class: "cat-tomar-conj", group_name: "Conjugations" },
  { id: "fazer-conj", label: "Fazer Conjugations", css_class: "cat-fazer-conj", group_name: "Conjugations" },
  { id: "trabalhar-conj", label: "Trabalhar Conjugations", css_class: "cat-trabalhar-conj", group_name: "Conjugations" },
  { id: "ter-conj", label: "Ter Conjugations", css_class: "cat-ter-conj", group_name: "Conjugations" },
  { id: "poder-conj", label: "Poder Conjugations", css_class: "cat-poder-conj", group_name: "Conjugations" },
  { id: "querer-conj", label: "Querer Conjugations", css_class: "cat-querer-conj", group_name: "Conjugations" },
  { id: "saber-conj", label: "Saber Conjugations", css_class: "cat-saber-conj", group_name: "Conjugations" },
  { id: "dar-conj", label: "Dar Conjugations", css_class: "cat-dar-conj", group_name: "Conjugations" },
  { id: "ver-conj", label: "Ver Conjugations", css_class: "cat-ver-conj", group_name: "Conjugations" },
  { id: "vir-conj", label: "Vir Conjugations", css_class: "cat-vir-conj", group_name: "Conjugations" },
  { id: "aula-mar27", label: "Aula Mar 27", css_class: "cat-aula-mar27", group_name: "Aulas" },
  { id: "aula-mar30", label: "Aula Mar 30", css_class: "cat-aula-mar30", group_name: "Aulas" },
  { id: "april-fools", label: "April Fools", css_class: "cat-april-fools", group_name: "Aulas" },
  { id: "april2", label: "April 2", css_class: "cat-april2", group_name: "Aulas" }
];

const cards = [
  { pt: "Algo novo", en: "Something new", category_id: "vocab" },
  { pt: "Sobre", en: "About", category_id: "vocab" },
  { pt: "Atualmente só corro", en: "Currently I only run", category_id: "phrases" },
  { pt: "Eu não treino", en: "I don't work out", category_id: "phrases" },
  { pt: "Eu não tenho paciência", en: "I don't have patience", category_id: "phrases" },
  { pt: "Eu preciso de um plano", en: "I need a plan", category_id: "phrases" },
  { pt: "Musculação", en: "Weight training / Bodybuilding", category_id: "fitness" },
  { pt: "Levantar peso", en: "To lift weights", category_id: "fitness" },
  { pt: "Hoje é dia de…", en: "Today is the day for…", category_id: "phrases" },
  { pt: "Hoje eu vou treinar…", en: "Today I'm going to train…", category_id: "phrases" },
  { pt: "Hoje eu vou fazer cardio", en: "Today I'm going to do cardio", category_id: "phrases" },
  { pt: "Abdômen", en: "Abs", category_id: "fitness" },
  { pt: "Pernas", en: "Legs", category_id: "fitness" },
  { pt: "Inferiores", en: "Lower (body)", category_id: "fitness" },
  { pt: "Posteriores", en: "Hamstrings", category_id: "fitness" },
  { pt: "Quadríceps", en: "Quads", category_id: "fitness" },
  { pt: "Panturrilha", en: "Calves", category_id: "fitness" },
  { pt: "Glúteos", en: "Glutes", category_id: "fitness" },
  { pt: "Braços", en: "Arms", category_id: "fitness" },
  { pt: "Superiores", en: "Upper (body)", category_id: "fitness" },
  { pt: "Peito", en: "Chest", category_id: "fitness" },
  { pt: "Ombros", en: "Shoulders", category_id: "fitness" },
  { pt: "Bíceps", en: "Biceps", category_id: "fitness" },
  { pt: "Tríceps", en: "Triceps", category_id: "fitness" },
  { pt: "Trapézio", en: "Traps / Trapezius", category_id: "fitness" },
  { pt: "Costas", en: "Back", category_id: "fitness" },
  { pt: "Pescoço", en: "Neck", category_id: "fitness" },
  { pt: "Antebraço", en: "Forearm", category_id: "fitness" },
  { pt: "Elevação pélvica", en: "Hip thrust", category_id: "fitness" },
  { pt: "Barra", en: "Barbell / Bar", category_id: "fitness" },
  { pt: "Agachamento", en: "Squat", category_id: "fitness" },
  { pt: "Supino", en: "Bench press", category_id: "fitness" },
  { pt: "Elevação lateral", en: "Lateral raise", category_id: "fitness" },
  { pt: "Elevação frontal", en: "Front raise", category_id: "fitness" },
  { pt: "Peso livre", en: "Free weight", category_id: "fitness" },
  { pt: "Pular caixa", en: "Box jump", category_id: "fitness" },
  { pt: "Esteira", en: "Treadmill", category_id: "fitness" },
  { pt: "Meu barbeiro", en: "My barber", category_id: "vocab" },
  { pt: "Recomendou / Recomendar", en: "Recommended / To recommend", category_id: "verbs" },
  { pt: "Antes de ontem", en: "Day before yesterday", category_id: "time" },
  { pt: "Depois de amanhã", en: "Day after tomorrow", category_id: "time" },
  { pt: "Da manhã", en: "In the morning", category_id: "time" },
  { pt: "Da tarde", en: "In the afternoon", category_id: "time" },
  { pt: "Da noite", en: "In the evening / At night", category_id: "time" },
  { pt: "Duas", en: "Two (feminine, used for time/hours)", category_id: "vocab" },
  { pt: "Chateado", en: "Upset / Annoyed", category_id: "vocab" },
  { pt: "Com raiva", en: "Angry", category_id: "vocab" },
  { pt: "Ninguém falava", en: "Nobody was talking", category_id: "phrases" },
  { pt: "Talvez", en: "Maybe", category_id: "vocab" },
  { pt: "Eu prometo que", en: "I promise that", category_id: "phrases" },
  { pt: "Próxima vez", en: "Next time", category_id: "time" },
  { pt: "Complicada", en: "Complicated", category_id: "vocab" },
  { pt: "Prédio", en: "Building / Apartment building", category_id: "vocab" },
  { pt: "Rua", en: "Street", category_id: "vocab" },
  { pt: "Chuva", en: "Rain", category_id: "weather" },
  { pt: "Por causa de/da/do", en: "Because of…", category_id: "vocab" },
  { pt: "Escada", en: "Stairs", category_id: "vocab" },
  { pt: "Eu estou bem", en: "I'm fine / I'm good", category_id: "phrases" },
  { pt: "Eu cortei o cabelo", en: "I cut my hair", category_id: "phrases" },
  { pt: "Eu passei muita raiva", en: "I was very angry", category_id: "phrases" },
  { pt: "Eles não permitiram meu reembolso", en: "They didn't allow my refund", category_id: "phrases" },
  { pt: "Eu não pude devolver minha calça", en: "I couldn't return my pants", category_id: "phrases" },
  { pt: "Eu disse ao meu banco e eles me ajudaram", en: "I told my bank and they helped me", category_id: "phrases" },
  { pt: "Eles removeram o pagamento", en: "They removed the payment", category_id: "phrases" },
  { pt: "Eu só como batatas fritas quando eu treino", en: "I only eat fries when I work out", category_id: "phrases" },
  { pt: "Doze", en: "Twelve (12)", category_id: "vocab" },
  { pt: "Eu tenho", en: "I have", category_id: "verbs" },
  { pt: "Tive", en: "I had (past)", category_id: "verbs" },
  { pt: "Você tá perdendo", en: "You're missing out", category_id: "phrases" },
  { pt: "Que horas?", en: "What time?", category_id: "time" },
  { pt: "Próximo", en: "Next", category_id: "time" },
  { pt: "Depois", en: "After", category_id: "time" },
  { pt: "Perto", en: "Close / Nearby", category_id: "vocab" },
  { pt: "Foi", en: "It was / He/She went", category_id: "verbs" },
  { pt: "Eu fui", en: "I was / I went", category_id: "verbs" },
  { pt: "Você foi", en: "You were / You went", category_id: "verbs" },
  { pt: "Dormi", en: "I slept", category_id: "verbs" },
  { pt: "Comi", en: "I ate", category_id: "verbs" },
  { pt: "Corri", en: "I ran", category_id: "verbs" },
  { pt: "Quilômetros", en: "Kilometers", category_id: "vocab" },
  { pt: "Edifício", en: "Building / Edifice", category_id: "vocab" },
  { pt: "Manhã", en: "Morning", category_id: "time" },
  { pt: "Amanhã", en: "Tomorrow", category_id: "time" },
  { pt: "Sextar / Sextou", en: "To celebrate Friday / It's Friday!", category_id: "daily" },
  { pt: "Empresa", en: "Company", category_id: "vocab" },
  // Ir — Presente
  { pt: "Eu vou", en: "I go", category_id: "ir-conj" },
  { pt: "Você vai", en: "You go", category_id: "ir-conj" },
  { pt: "Ele/Ela vai", en: "He/She goes", category_id: "ir-conj" },
  // Fazer — Presente
  { pt: "Eu faço", en: "I do / I make", category_id: "fazer-conj" },
  { pt: "Você faz", en: "You do / You make", category_id: "fazer-conj" },
  { pt: "Ele/Ela faz", en: "He/She does / makes", category_id: "fazer-conj" },
  { pt: "Nós fazemos", en: "We do / We make", category_id: "fazer-conj" },
  { pt: "Vocês fazem", en: "You all do / make", category_id: "fazer-conj" },
  { pt: "Eles/Elas fazem", en: "They do / make", category_id: "fazer-conj" },
  // Fazer — Imperfeito
  { pt: "Eu fazia", en: "I used to do / I used to make", category_id: "fazer-conj" },
  { pt: "Você fazia", en: "You used to do / You used to make", category_id: "fazer-conj" },
  { pt: "Ele/Ela fazia", en: "He/She used to do / make", category_id: "fazer-conj" },
  { pt: "Nós fazíamos", en: "We used to do / We used to make", category_id: "fazer-conj" },
  { pt: "Vocês faziam", en: "You all used to do / make", category_id: "fazer-conj" },
  { pt: "Eles/Elas faziam", en: "They used to do / make", category_id: "fazer-conj" },
  // Fazer — Perfeito
  { pt: "Eu fiz", en: "I did / I made", category_id: "fazer-conj" },
  { pt: "Você fez", en: "You did / You made", category_id: "fazer-conj" },
  { pt: "Ele/Ela fez", en: "He/She did / made", category_id: "fazer-conj" },
  { pt: "Nós fizemos", en: "We did / We made", category_id: "fazer-conj" },
  { pt: "Vocês fizeram", en: "You all did / made", category_id: "fazer-conj" },
  { pt: "Eles/Elas fizeram", en: "They did / made", category_id: "fazer-conj" },
  // Fazer — Futuro
  { pt: "Eu farei", en: "I will do / I will make", category_id: "fazer-conj" },
  { pt: "Você fará", en: "You will do / You will make", category_id: "fazer-conj" },
  { pt: "Ele/Ela fará", en: "He/She will do / will make", category_id: "fazer-conj" },
  { pt: "Nós faremos", en: "We will do / We will make", category_id: "fazer-conj" },
  { pt: "Vocês farão", en: "You all will do / will make", category_id: "fazer-conj" },
  { pt: "Eles/Elas farão", en: "They will do / will make", category_id: "fazer-conj" },
  // Fazer — Conditional
  { pt: "Eu faria", en: "I would do / I would make", category_id: "fazer-conj" },
  { pt: "Você faria", en: "You would do / You would make", category_id: "fazer-conj" },
  { pt: "Ele/Ela faria", en: "He/She would do / would make", category_id: "fazer-conj" },
  { pt: "Nós faríamos", en: "We would do / We would make", category_id: "fazer-conj" },
  { pt: "Vocês fariam", en: "You all would do / would make", category_id: "fazer-conj" },
  { pt: "Eles/Elas fariam", en: "They would do / would make", category_id: "fazer-conj" },
  // Trabalhar — Presente
  { pt: "Eu trabalho", en: "I work", category_id: "trabalhar-conj" },
  { pt: "Você trabalha", en: "You work", category_id: "trabalhar-conj" },
  { pt: "Ele/Ela trabalha", en: "He/She works", category_id: "trabalhar-conj" },
  { pt: "Nós trabalhamos", en: "We work", category_id: "trabalhar-conj" },
  { pt: "Vocês trabalham", en: "You all work", category_id: "trabalhar-conj" },
  { pt: "Eles/Elas trabalham", en: "They work", category_id: "trabalhar-conj" },
  // Trabalhar — Imperfeito
  { pt: "Eu trabalhava", en: "I used to work", category_id: "trabalhar-conj" },
  { pt: "Você trabalhava", en: "You used to work", category_id: "trabalhar-conj" },
  { pt: "Ele/Ela trabalhava", en: "He/She used to work", category_id: "trabalhar-conj" },
  { pt: "Nós trabalhávamos", en: "We used to work", category_id: "trabalhar-conj" },
  { pt: "Vocês trabalhavam", en: "You all used to work", category_id: "trabalhar-conj" },
  { pt: "Eles/Elas trabalhavam", en: "They used to work", category_id: "trabalhar-conj" },
  // Trabalhar — Perfeito
  { pt: "Eu trabalhei", en: "I worked", category_id: "trabalhar-conj" },
  { pt: "Você trabalhou", en: "You worked", category_id: "trabalhar-conj" },
  { pt: "Ele/Ela trabalhou", en: "He/She worked", category_id: "trabalhar-conj" },
  { pt: "Nós trabalhamos (past)", en: "We worked", category_id: "trabalhar-conj" },
  { pt: "Vocês trabalharam", en: "You all worked", category_id: "trabalhar-conj" },
  { pt: "Eles/Elas trabalharam", en: "They worked", category_id: "trabalhar-conj" },
  // Trabalhar — Futuro
  { pt: "Eu trabalharei", en: "I will work", category_id: "trabalhar-conj" },
  { pt: "Você trabalhará", en: "You will work", category_id: "trabalhar-conj" },
  { pt: "Ele/Ela trabalhará", en: "He/She will work", category_id: "trabalhar-conj" },
  { pt: "Nós trabalharemos", en: "We will work", category_id: "trabalhar-conj" },
  { pt: "Vocês trabalharão", en: "You all will work", category_id: "trabalhar-conj" },
  { pt: "Eles/Elas trabalharão", en: "They will work", category_id: "trabalhar-conj" },
  // Trabalhar — Conditional
  { pt: "Eu trabalharia", en: "I would work", category_id: "trabalhar-conj" },
  { pt: "Você trabalharia", en: "You would work", category_id: "trabalhar-conj" },
  { pt: "Ele/Ela trabalharia", en: "He/She would work", category_id: "trabalhar-conj" },
  { pt: "Nós trabalharíamos", en: "We would work", category_id: "trabalhar-conj" },
  { pt: "Vocês trabalhariam", en: "You all would work", category_id: "trabalhar-conj" },
  { pt: "Eles/Elas trabalhariam", en: "They would work", category_id: "trabalhar-conj" },
  // Esperar — Presente
  { pt: "Eu espero", en: "I wait / I hope", category_id: "esperar-conj" },
  { pt: "Você espera", en: "You wait / You hope", category_id: "esperar-conj" },
  { pt: "Ele/Ela espera", en: "He/She waits / hopes", category_id: "esperar-conj" },
  { pt: "Nós esperamos", en: "We wait / We hope", category_id: "esperar-conj" },
  { pt: "Vocês esperam", en: "You all wait / hope", category_id: "esperar-conj" },
  { pt: "Eles/Elas esperam", en: "They wait / hope", category_id: "esperar-conj" },
  // Esperar — Imperfeito
  { pt: "Eu esperava", en: "I used to wait / I was hoping", category_id: "esperar-conj" },
  { pt: "Você esperava", en: "You used to wait / You were hoping", category_id: "esperar-conj" },
  { pt: "Ele/Ela esperava", en: "He/She used to wait / was hoping", category_id: "esperar-conj" },
  { pt: "Nós esperávamos", en: "We used to wait / We were hoping", category_id: "esperar-conj" },
  { pt: "Vocês esperavam", en: "You all used to wait / were hoping", category_id: "esperar-conj" },
  { pt: "Eles/Elas esperavam", en: "They used to wait / were hoping", category_id: "esperar-conj" },
  // Esperar — Perfeito
  { pt: "Eu esperei", en: "I waited / I hoped", category_id: "esperar-conj" },
  { pt: "Você esperou", en: "You waited / You hoped", category_id: "esperar-conj" },
  { pt: "Ele/Ela esperou", en: "He/She waited / hoped", category_id: "esperar-conj" },
  { pt: "Nós esperamos (past)", en: "We waited / We hoped", category_id: "esperar-conj" },
  { pt: "Vocês esperaram", en: "You all waited / hoped", category_id: "esperar-conj" },
  { pt: "Eles/Elas esperaram", en: "They waited / hoped", category_id: "esperar-conj" },
  // Esperar — Futuro
  { pt: "Eu esperarei", en: "I will wait / I will hope", category_id: "esperar-conj" },
  { pt: "Você esperará", en: "You will wait / You will hope", category_id: "esperar-conj" },
  { pt: "Ele/Ela esperará", en: "He/She will wait / will hope", category_id: "esperar-conj" },
  { pt: "Nós esperaremos", en: "We will wait / We will hope", category_id: "esperar-conj" },
  { pt: "Vocês esperarão", en: "You all will wait / will hope", category_id: "esperar-conj" },
  { pt: "Eles/Elas esperarão", en: "They will wait / will hope", category_id: "esperar-conj" },
  // Esperar — Conditional
  { pt: "Eu esperaria", en: "I would wait / I would hope", category_id: "esperar-conj" },
  { pt: "Você esperaria", en: "You would wait / You would hope", category_id: "esperar-conj" },
  { pt: "Ele/Ela esperaria", en: "He/She would wait / would hope", category_id: "esperar-conj" },
  { pt: "Nós esperaríamos", en: "We would wait / We would hope", category_id: "esperar-conj" },
  { pt: "Vocês esperariam", en: "You all would wait / would hope", category_id: "esperar-conj" },
  { pt: "Eles/Elas esperariam", en: "They would wait / would hope", category_id: "esperar-conj" },
  // Buscar — Presente
  { pt: "Eu busco", en: "I search / I fetch", category_id: "buscar-conj" },
  { pt: "Você busca", en: "You search / You fetch", category_id: "buscar-conj" },
  { pt: "Ele/Ela busca", en: "He/She searches / fetches", category_id: "buscar-conj" },
  { pt: "Nós buscamos", en: "We search / We fetch", category_id: "buscar-conj" },
  { pt: "Vocês buscam", en: "You all search / fetch", category_id: "buscar-conj" },
  { pt: "Eles/Elas buscam", en: "They search / fetch", category_id: "buscar-conj" },
  // Buscar — Imperfeito
  { pt: "Eu buscava", en: "I used to search / I was looking for", category_id: "buscar-conj" },
  { pt: "Você buscava", en: "You used to search / You were looking for", category_id: "buscar-conj" },
  { pt: "Ele/Ela buscava", en: "He/She used to search / was looking for", category_id: "buscar-conj" },
  { pt: "Nós buscávamos", en: "We used to search / We were looking for", category_id: "buscar-conj" },
  { pt: "Vocês buscavam", en: "You all used to search / were looking for", category_id: "buscar-conj" },
  { pt: "Eles/Elas buscavam", en: "They used to search / were looking for", category_id: "buscar-conj" },
  // Buscar — Perfeito
  { pt: "Eu busquei", en: "I searched / I fetched", category_id: "buscar-conj" },
  { pt: "Você buscou", en: "You searched / You fetched", category_id: "buscar-conj" },
  { pt: "Ele/Ela buscou", en: "He/She searched / fetched", category_id: "buscar-conj" },
  { pt: "Nós buscamos (past)", en: "We searched / We fetched", category_id: "buscar-conj" },
  { pt: "Vocês buscaram", en: "You all searched / fetched", category_id: "buscar-conj" },
  { pt: "Eles/Elas buscaram", en: "They searched / fetched", category_id: "buscar-conj" },
  // Buscar — Futuro
  { pt: "Eu buscarei", en: "I will search / I will fetch", category_id: "buscar-conj" },
  { pt: "Você buscará", en: "You will search / You will fetch", category_id: "buscar-conj" },
  { pt: "Ele/Ela buscará", en: "He/She will search / will fetch", category_id: "buscar-conj" },
  { pt: "Nós buscaremos", en: "We will search / We will fetch", category_id: "buscar-conj" },
  { pt: "Vocês buscarão", en: "You all will search / will fetch", category_id: "buscar-conj" },
  { pt: "Eles/Elas buscarão", en: "They will search / will fetch", category_id: "buscar-conj" },
  // Buscar — Conditional
  { pt: "Eu buscaria", en: "I would search / I would fetch", category_id: "buscar-conj" },
  { pt: "Você buscaria", en: "You would search / You would fetch", category_id: "buscar-conj" },
  { pt: "Ele/Ela buscaria", en: "He/She would search / would fetch", category_id: "buscar-conj" },
  { pt: "Nós buscaríamos", en: "We would search / We would fetch", category_id: "buscar-conj" },
  { pt: "Vocês buscariam", en: "You all would search / would fetch", category_id: "buscar-conj" },
  { pt: "Eles/Elas buscariam", en: "They would search / would fetch", category_id: "buscar-conj" },
  // Tomar — Presente
  { pt: "Eu tomo", en: "I take / I drink", category_id: "tomar-conj" },
  { pt: "Você toma", en: "You take / You drink", category_id: "tomar-conj" },
  { pt: "Ele/Ela toma", en: "He/She takes / drinks", category_id: "tomar-conj" },
  { pt: "Nós tomamos", en: "We take / We drink", category_id: "tomar-conj" },
  { pt: "Vocês tomam", en: "You all take / drink", category_id: "tomar-conj" },
  { pt: "Eles/Elas tomam", en: "They take / drink", category_id: "tomar-conj" },
  // Tomar — Imperfeito
  { pt: "Eu tomava", en: "I used to take / I used to drink", category_id: "tomar-conj" },
  { pt: "Você tomava", en: "You used to take / You used to drink", category_id: "tomar-conj" },
  { pt: "Ele/Ela tomava", en: "He/She used to take / drink", category_id: "tomar-conj" },
  { pt: "Nós tomávamos", en: "We used to take / We used to drink", category_id: "tomar-conj" },
  { pt: "Vocês tomavam", en: "You all used to take / drink", category_id: "tomar-conj" },
  { pt: "Eles/Elas tomavam", en: "They used to take / drink", category_id: "tomar-conj" },
  // Tomar — Perfeito
  { pt: "Eu tomei", en: "I took / I drank", category_id: "tomar-conj" },
  { pt: "Você tomou", en: "You took / You drank", category_id: "tomar-conj" },
  { pt: "Ele/Ela tomou", en: "He/She took / drank", category_id: "tomar-conj" },
  { pt: "Nós tomamos (past)", en: "We took / We drank", category_id: "tomar-conj" },
  { pt: "Vocês tomaram", en: "You all took / drank", category_id: "tomar-conj" },
  { pt: "Eles/Elas tomaram", en: "They took / drank", category_id: "tomar-conj" },
  // Tomar — Futuro
  { pt: "Eu tomarei", en: "I will take / I will drink", category_id: "tomar-conj" },
  { pt: "Você tomará", en: "You will take / You will drink", category_id: "tomar-conj" },
  { pt: "Ele/Ela tomará", en: "He/She will take / will drink", category_id: "tomar-conj" },
  { pt: "Nós tomaremos", en: "We will take / We will drink", category_id: "tomar-conj" },
  { pt: "Vocês tomarão", en: "You all will take / will drink", category_id: "tomar-conj" },
  { pt: "Eles/Elas tomarão", en: "They will take / will drink", category_id: "tomar-conj" },
  // Tomar — Conditional
  { pt: "Eu tomaria", en: "I would take / I would drink", category_id: "tomar-conj" },
  { pt: "Você tomaria", en: "You would take / You would drink", category_id: "tomar-conj" },
  { pt: "Ele/Ela tomaria", en: "He/She would take / would drink", category_id: "tomar-conj" },
  { pt: "Nós tomaríamos", en: "We would take / We would drink", category_id: "tomar-conj" },
  { pt: "Vocês tomariam", en: "You all would take / would drink", category_id: "tomar-conj" },
  { pt: "Eles/Elas tomariam", en: "They would take / would drink", category_id: "tomar-conj" },
  { pt: "Hoje eu vou fazer meu CPF no Banco do Brasil", en: "Today I'll get my CPF at Banco do Brasil", category_id: "phrases" },
  { pt: "Hoje eu vou cortar o meu cabelo", en: "Today I'm going to cut my hair", category_id: "phrases" },
  { pt: "Eu não comprei ainda", en: "I haven't bought it yet", category_id: "phrases" },
  { pt: "Eu não agendei ainda", en: "I haven't scheduled it yet", category_id: "phrases" },
  { pt: "Não tenho certeza", en: "I'm not sure", category_id: "phrases" },
  { pt: "Dessa vez sério", en: "This time for real", category_id: "phrases" },
  { pt: "No final de semana, o que você vai fazer?", en: "On the weekend, what are you going to do?", category_id: "phrases" },
  { pt: "Não tenho planos ainda", en: "I don't have plans yet", category_id: "phrases" },
  { pt: "Ontem eu fui preguiçoso", en: "Yesterday I was lazy", category_id: "phrases" },
  { pt: "Como está o trabalho?", en: "How is work?", category_id: "phrases" },
  { pt: "Com o que você trabalha?", en: "What do you work with?", category_id: "phrases" },
  { pt: "Você já ouviu falar", en: "Have you already heard of", category_id: "phrases" },
  { pt: "Você é o desenvolvedor do aplicativo?", en: "Are you the app developer?", category_id: "phrases" },
  { pt: "Eu criei o aplicativo", en: "I created the app", category_id: "phrases" },
  { pt: "Desenvolvedor de software", en: "Software developer", category_id: "vocab" },
  { pt: "Sócio", en: "Partner / Associate", category_id: "vocab" },
  { pt: "Meio-tempo / Tempo-parcial", en: "Part-time", category_id: "vocab" },
  { pt: "Conselheiro / Assessor", en: "Advisor / Counselor", category_id: "vocab" },
  { pt: "Segunda-feira", en: "Monday", category_id: "time" },
  { pt: "Terça-feira", en: "Tuesday", category_id: "time" },
  { pt: "Quarta-feira", en: "Wednesday", category_id: "time" },
  { pt: "Quinta-feira", en: "Thursday", category_id: "time" },
  { pt: "Sexta-feira", en: "Friday", category_id: "time" },
  { pt: "Sábado", en: "Saturday", category_id: "time" },
  { pt: "Domingo", en: "Sunday", category_id: "time" },
  { pt: "Essa / Esse", en: "This (feminine / masculine)", category_id: "vocab" },
  { pt: "A próxima / O próximo", en: "The next (fem / masc)", category_id: "vocab" },
  { pt: "Passada / Passado", en: "Last / Past (fem / masc)", category_id: "vocab" },
  { pt: "Agora", en: "Now", category_id: "vocab" },
  { pt: "Pesquisando / Buscando", en: "Searching", category_id: "vocab" },
  { pt: "Escritório", en: "Office", category_id: "vocab" },
  { pt: "Morar", en: "To live (reside)", category_id: "vocab" },
  { pt: "Então", en: "So / Then", category_id: "vocab" },
  { pt: "Aluguel", en: "Rent", category_id: "vocab" },
  { pt: "Comprar", en: "To buy", category_id: "vocab" },
  { pt: "Encontrar", en: "To find", category_id: "vocab" },
  { pt: "Provavelmente", en: "Probably", category_id: "vocab" },
  { pt: "Normalmente", en: "Normally", category_id: "vocab" },
  { pt: "Igualmente", en: "Equally / Likewise", category_id: "vocab" },
  { pt: "Pai", en: "Dad / Father", category_id: "daily" },
  { pt: "Avô", en: "Grandpa", category_id: "daily" },
  { pt: "Avó", en: "Grandma", category_id: "daily" },
  { pt: "Meio-dia", en: "Noon / Midday", category_id: "time" },
  { pt: "Meia-noite", en: "Midnight", category_id: "time" },
  { pt: "Hambúrguer", en: "Hamburger", category_id: "daily" },
  { pt: "Chá quente", en: "Hot tea", category_id: "daily" },
  { pt: "Eu necessito / Eu preciso", en: "I need", category_id: "vocab" },
  { pt: "Só isso", en: "That's it", category_id: "vocab" },
  { pt: "Mais do mesmo", en: "More of the same", category_id: "vocab" },
  { pt: "Gostoso", en: "Delicious / Hot (attractive)", category_id: "vocab" },
  { pt: "Buscando personal trainer para academia", en: "Looking for a personal trainer for the gym", category_id: "phrases" },
  { pt: "Eu preciso ficar forte", en: "I need to get strong", category_id: "phrases" },
  { pt: "Eu vou ao mercado", en: "I will go to the market", category_id: "phrases" },
  { pt: "No próximo final de semana eu vou…", en: "Next weekend I'm going to…", category_id: "phrases" },
  { pt: "Eu estou tendo uma classe boa", en: "I'm having a good class", category_id: "phrases" },
  { pt: "Estou buscando um escritório para trabalhar", en: "I'm looking for an office to work in", category_id: "phrases" },
  { pt: "Calor", en: "Heat / Hot (weather)", category_id: "weather" },
  { pt: "Frio", en: "Cold", category_id: "weather" },
  { pt: "Ai que calor", en: "Oh it's so hot", category_id: "weather" },
  { pt: "Muito calor", en: "Very hot", category_id: "weather" },
  { pt: "Estou com calor", en: "I'm hot (feeling)", category_id: "weather" },
  { pt: "Hoje está muito calor", en: "It's very hot today", category_id: "weather" },
  { pt: "Quente", en: "Hot (temperature)", category_id: "weather" },
  { pt: "Gelado", en: "Freezing / Ice cold", category_id: "weather" },
  { pt: "Gelo", en: "Ice", category_id: "weather" },
  { pt: "Fora", en: "Outside", category_id: "vocab" },
  { pt: "Lá fora", en: "Out there / Outside", category_id: "vocab" },
  { pt: "Bebê, está frio lá fora", en: "Baby, it's cold outside", category_id: "phrases" },
  { pt: "Dentro", en: "Inside", category_id: "vocab" },
  { pt: "Demorar", en: "To take long / To delay", category_id: "verbs" },
  { pt: "Atrasar / Atrasado(a)", en: "To be late / Late", category_id: "verbs" },
  { pt: "Acordar", en: "To wake up", category_id: "daily" },
  { pt: "Dormir", en: "To sleep", category_id: "daily" },
  { pt: "Comer", en: "To eat", category_id: "daily" },
  { pt: "Como foi o seu fim de semana?", en: "How was your weekend?", category_id: "phrases" },
  { pt: "Descansar / Eu descansei", en: "To rest / I rested", category_id: "verbs" },
  { pt: "Temos", en: "We have", category_id: "verbs" },
  { pt: "Começar / Terminar", en: "To start / To finish", category_id: "verbs" },
  { pt: "Gastar energia", en: "To spend energy", category_id: "vocab" },
  { pt: "Celebrou", en: "Celebrated", category_id: "verbs" },
  { pt: "Combina com sua personalidade", en: "It matches your personality", category_id: "phrases" },
  { pt: "Por que eu gosto de carnaval?", en: "Why do I like carnaval?", category_id: "phrases" },
  { pt: "Gosto", en: "I like / Taste", category_id: "vocab" },
  { pt: "Divertida", en: "Fun", category_id: "vocab" },
  { pt: "Colorida", en: "Colorful", category_id: "vocab" },
  { pt: "Vibrante", en: "Vibrant", category_id: "vocab" },
  { pt: "Elogio", en: "Compliment", category_id: "vocab" },
  { pt: "Novo(a) / Velho(a)", en: "New / Old", category_id: "vocab" },
  { pt: "Mais nova / Mais velha", en: "Younger / Older", category_id: "vocab" },
  { pt: "Dançarina / Dançarino", en: "Dancer (fem / masc)", category_id: "vocab" },
  { pt: "Bloco de carnaval", en: "Carnival street party / block", category_id: "vocab" },
  { pt: "Desfile", en: "Parade", category_id: "vocab" },
  { pt: "Eu ia ir", en: "I was going to go", category_id: "phrases" },
  { pt: "De novo", en: "Again", category_id: "vocab" },
  { pt: "2 vezes", en: "2 times", category_id: "vocab" },
  { pt: "Foi bom o carnaval ano passado aí?", en: "Was carnaval good last year there?", category_id: "phrases" },
  { pt: "Ano retrasado", en: "Two years ago", category_id: "time" },
  { pt: "Deveria", en: "Should", category_id: "verbs" },
  { pt: "Sair", en: "To get out / To leave", category_id: "verbs" },
  { pt: "Conhecer", en: "To know / To meet", category_id: "verbs" },
  { pt: "Algumas pessoas", en: "Some people", category_id: "vocab" },
  { pt: "Aí / Ali / Daí", en: "There / There (farther) / From there", category_id: "vocab" },
  { pt: "Aqui / Cá / Para cá", en: "Here / Here / Over here", category_id: "vocab" },
  { pt: "Mas você foi para o do Rio ano retrasado", en: "But you went to the one in Rio two years ago", category_id: "phrases" },
  { pt: "De abrir os olhos", en: "Eye-opening", category_id: "vocab" },
  { pt: "Foi uma nova experiência", en: "It was a new experience", category_id: "phrases" },
  { pt: "Mudou minha mente", en: "Changed my mind", category_id: "phrases" },
  { pt: "Explodiu minha mente", en: "Blew my mind", category_id: "phrases" },
  { pt: "Foi uma experiência de abrir os olhos", en: "It was an eye-opening experience", category_id: "phrases" },
  { pt: "Viajar", en: "To travel", category_id: "verbs" },
  { pt: "Para", en: "To / For", category_id: "vocab" },
  { pt: "No meio de março", en: "In the middle of March", category_id: "time" },
  { pt: "Mais cedo", en: "Earlier", category_id: "time" },
  { pt: "Mais tarde", en: "Later", category_id: "time" },
  { pt: "Desculpa", en: "Sorry / Excuse me", category_id: "vocab" },
  { pt: "Águas de janeiro", en: "January waters (famous Brazilian song)", category_id: "vocab" },
  { pt: "Eu tenho que trabalhar muito ainda hoje", en: "I still have to work a lot today", category_id: "phrases" },
  { pt: "Ainda", en: "Still / Yet", category_id: "vocab" },
  { pt: "Cardio", en: "Cardio", category_id: "fitness" },
  { pt: "Nós vamos", en: "We go", category_id: "ir-conj" },
  { pt: "Vocês vão", en: "You all go", category_id: "ir-conj" },
  { pt: "Eles/Elas vão", en: "They go", category_id: "ir-conj" },
  // Ir — Imperfeito
  { pt: "Eu ia", en: "I used to go", category_id: "ir-conj" },
  { pt: "Você ia", en: "You used to go", category_id: "ir-conj" },
  { pt: "Ele/Ela ia", en: "He/She used to go", category_id: "ir-conj" },
  { pt: "Nós íamos", en: "We used to go", category_id: "ir-conj" },
  { pt: "Vocês iam", en: "You all used to go", category_id: "ir-conj" },
  { pt: "Eles/Elas iam", en: "They used to go", category_id: "ir-conj" },
  // Ir — Perfeito (disambiguated with "(ir)" since Ser shares these forms)
  { pt: "Eu fui (ir)", en: "I went", category_id: "ir-conj" },
  { pt: "Você foi (ir)", en: "You went", category_id: "ir-conj" },
  { pt: "Ele/Ela foi (ir)", en: "He/She went", category_id: "ir-conj" },
  { pt: "Nós fomos (ir)", en: "We went", category_id: "ir-conj" },
  { pt: "Vocês foram (ir)", en: "You all went", category_id: "ir-conj" },
  { pt: "Eles/Elas foram (ir)", en: "They went", category_id: "ir-conj" },
  // Ir — Futuro
  { pt: "Eu irei", en: "I will go", category_id: "ir-conj" },
  { pt: "Você irá", en: "You will go", category_id: "ir-conj" },
  { pt: "Ele/Ela irá", en: "He/She will go", category_id: "ir-conj" },
  { pt: "Nós iremos", en: "We will go", category_id: "ir-conj" },
  { pt: "Vocês irão", en: "You all will go", category_id: "ir-conj" },
  { pt: "Eles/Elas irão", en: "They will go", category_id: "ir-conj" },
  // Ir — Conditional
  { pt: "Eu iria", en: "I would go", category_id: "ir-conj" },
  { pt: "Você iria", en: "You would go", category_id: "ir-conj" },
  { pt: "Ele/Ela iria", en: "He/She would go", category_id: "ir-conj" },
  { pt: "Nós iríamos", en: "We would go", category_id: "ir-conj" },
  { pt: "Vocês iriam", en: "You all would go", category_id: "ir-conj" },
  { pt: "Eles/Elas iriam", en: "They would go", category_id: "ir-conj" },
  // Estar — Presente
  { pt: "Eu estou", en: "I am (state)", category_id: "estar-conj" },
  { pt: "Você está", en: "You are (state)", category_id: "estar-conj" },
  { pt: "Ele/Ela está", en: "He/She is (state)", category_id: "estar-conj" },
  { pt: "Nós estamos", en: "We are (state)", category_id: "estar-conj" },
  { pt: "Vocês estão", en: "You all are (state)", category_id: "estar-conj" },
  { pt: "Eles/Elas estão", en: "They are (state)", category_id: "estar-conj" },
  // Estar — Imperfeito
  { pt: "Eu estava", en: "I was being / I used to be (state)", category_id: "estar-conj" },
  { pt: "Você estava", en: "You were being / You used to be (state)", category_id: "estar-conj" },
  { pt: "Ele/Ela estava", en: "He/She was being (state)", category_id: "estar-conj" },
  { pt: "Nós estávamos", en: "We were being / We used to be (state)", category_id: "estar-conj" },
  { pt: "Vocês estavam", en: "You all were being (state)", category_id: "estar-conj" },
  { pt: "Eles/Elas estavam", en: "They were being (state)", category_id: "estar-conj" },
  // Estar — Perfeito
  { pt: "Eu estive", en: "I was (state, specific occasion)", category_id: "estar-conj" },
  { pt: "Você esteve", en: "You were (state, specific occasion)", category_id: "estar-conj" },
  { pt: "Ele/Ela esteve", en: "He/She was (state, specific occasion)", category_id: "estar-conj" },
  { pt: "Nós estivemos", en: "We were (state, specific occasion)", category_id: "estar-conj" },
  { pt: "Vocês estiveram", en: "You all were (state, specific occasion)", category_id: "estar-conj" },
  { pt: "Eles/Elas estiveram", en: "They were (state, specific occasion)", category_id: "estar-conj" },
  // Estar — Futuro
  { pt: "Eu estarei", en: "I will be (state)", category_id: "estar-conj" },
  { pt: "Você estará", en: "You will be (state)", category_id: "estar-conj" },
  { pt: "Ele/Ela estará", en: "He/She will be (state)", category_id: "estar-conj" },
  { pt: "Nós estaremos", en: "We will be (state)", category_id: "estar-conj" },
  { pt: "Vocês estarão", en: "You all will be (state)", category_id: "estar-conj" },
  { pt: "Eles/Elas estarão", en: "They will be (state)", category_id: "estar-conj" },
  // Estar — Conditional
  { pt: "Eu estaria", en: "I would be (state)", category_id: "estar-conj" },
  { pt: "Você estaria", en: "You would be (state)", category_id: "estar-conj" },
  { pt: "Ele/Ela estaria", en: "He/She would be (state)", category_id: "estar-conj" },
  { pt: "Nós estaríamos", en: "We would be (state)", category_id: "estar-conj" },
  { pt: "Vocês estariam", en: "You all would be (state)", category_id: "estar-conj" },
  { pt: "Eles/Elas estariam", en: "They would be (state)", category_id: "estar-conj" },
  { pt: "Feliz / Alegre", en: "Happy / Cheerful", category_id: "vocab" },
  { pt: "Triste", en: "Sad", category_id: "vocab" },
  { pt: "Educado(a)", en: "Polite", category_id: "vocab" },
  { pt: "Mal-educado(a)", en: "Rude / Impolite", category_id: "vocab" },
  { pt: "Inteligente", en: "Intelligent / Smart", category_id: "vocab" },
  { pt: "Burro(a)", en: "Dumb / Stupid", category_id: "vocab" },
  { pt: "Calmo(a)", en: "Calm", category_id: "vocab" },
  { pt: "Nervoso(a)", en: "Nervous / Anxious", category_id: "vocab" },
  { pt: "Corajoso(a)", en: "Brave", category_id: "vocab" },
  { pt: "Medroso(a)", en: "Cowardly / Fearful", category_id: "vocab" },
  { pt: "Honesto(a)", en: "Honest", category_id: "vocab" },
  { pt: "Mentiroso(a)", en: "Liar / Dishonest", category_id: "vocab" },
  { pt: "Bonito(a)", en: "Handsome / Beautiful", category_id: "vocab" },
  { pt: "Lindo(a)", en: "Pretty", category_id: "vocab" },
  { pt: "Feio(a)", en: "Ugly", category_id: "vocab" },
  { pt: "Alto(a)", en: "Tall", category_id: "vocab" },
  { pt: "Baixo(a)", en: "Short", category_id: "vocab" },
  { pt: "Magro(a)", en: "Thin / Slim", category_id: "vocab" },
  { pt: "Gordo(a)", en: "Fat / Overweight", category_id: "vocab" },
  { pt: "Divertido(a)", en: "Fun", category_id: "vocab" },
  { pt: "Legal", en: "Cool", category_id: "vocab" },
  { pt: "Chato(a)", en: "Boring", category_id: "vocab" },
  { pt: "Simpático(a)", en: "Nice", category_id: "vocab" },
  { pt: "Grosso(a)", en: "Rude", category_id: "vocab" },
  { pt: "Ignorante", en: "Ignorant", category_id: "vocab" },
  { pt: "Fofo(a)", en: "Cute", category_id: "vocab" },
  { pt: "Irritante", en: "Irritating", category_id: "vocab" },
  { pt: "Imbécil", en: "Imbecile", category_id: "vocab" },
  { pt: "Maravilhoso(a)", en: "Wonderful", category_id: "vocab" },
  { pt: "Interessante", en: "Interesting", category_id: "vocab" },
  { pt: "Forte", en: "Strong", category_id: "vocab" },
  { pt: "Fraco(a)", en: "Weak", category_id: "vocab" },
  { pt: "Animado(a)", en: "Excited", category_id: "vocab" },
  { pt: "Desanimado(a)", en: "Not excited", category_id: "vocab" },
  { pt: "Organizado(a)", en: "Organized", category_id: "vocab" },
  { pt: "Desorganizado(a)", en: "Disorganized", category_id: "vocab" },
  { pt: "Preguiçoso(a)", en: "Lazy", category_id: "vocab" },
  { pt: "Paciente", en: "Patient", category_id: "vocab" },
  { pt: "Tímido(a)", en: "Shy", category_id: "vocab" },
  { pt: "Contente", en: "Content / Happy", category_id: "vocab" },
  { pt: "Cansado(a)", en: "Tired", category_id: "vocab" },
  { pt: "Entediado(a)", en: "Bored", category_id: "vocab" },
  { pt: "Preocupado(a)", en: "Worried", category_id: "vocab" },
  { pt: "Sala de aula", en: "Classroom", category_id: "vocab" },
  { pt: "Casa", en: "House / Home", category_id: "vocab" },
  { pt: "Supermercado", en: "Supermarket", category_id: "vocab" },
  { pt: "Juiz de Fora", en: "Juiz de Fora (city in Minas Gerais)", category_id: "vocab" },
  { pt: "Brasil", en: "Brazil", category_id: "vocab" },
  { pt: "Minas Gerais", en: "Minas Gerais (state in Brazil)", category_id: "vocab" },
  { pt: "Cinema", en: "Movie theater / Cinema", category_id: "vocab" },
  { pt: "Salão de beleza", en: "Beauty salon", category_id: "vocab" },
  { pt: "Fome", en: "Hunger / Hungry", category_id: "vocab" },
  { pt: "Sede", en: "Thirst / Thirsty", category_id: "vocab" },
  { pt: "Raiva", en: "Anger / Rage", category_id: "vocab" },
  { pt: "Medo", en: "Fear", category_id: "vocab" },
  { pt: "Dor de cabeça", en: "Headache", category_id: "vocab" },
  { pt: "Enjoo", en: "Nausea", category_id: "vocab" },
  { pt: "O braço quebrado", en: "The broken arm", category_id: "vocab" },
  { pt: "Eu ia ao trabalho de ônibus.", en: "I used to go to work by bus.", category_id: "ir-phrases" },
  { pt: "Você ia à escola a pé?", en: "Did you used to go to school on foot?", category_id: "ir-phrases" },
  { pt: "Ele ia ao mercado todo dia.", en: "He used to go to the market every day.", category_id: "ir-phrases" },
  { pt: "Ela ia à praia sempre.", en: "She always used to go to the beach.", category_id: "ir-phrases" },
  { pt: "Nós íamos estudar juntos.", en: "We used to study together.", category_id: "ir-phrases" },
  { pt: "Vocês iam ao curso à noite?", en: "Did you (pl.) used to go to the course at night?", category_id: "ir-phrases" },
  { pt: "Eles iam ao cinema com frequência.", en: "They used to go to the movies often.", category_id: "ir-phrases" },
  { pt: "Elas iam à academia antes.", en: "They (f.) used to go to the gym before.", category_id: "ir-phrases" },
  { pt: "Eu fui ao Brasil no ano passado.", en: "I went to Brazil last year.", category_id: "ir-phrases" },
  { pt: "Você foi ao evento ontem?", en: "Did you go to the event yesterday?", category_id: "ir-phrases" },
  { pt: "Ele foi ao trabalho cedo.", en: "He went to work early.", category_id: "ir-phrases" },
  { pt: "Ela foi ao médico ontem.", en: "She went to the doctor yesterday.", category_id: "ir-phrases" },
  { pt: "Nós fomos à praia ontem.", en: "We went to the beach yesterday.", category_id: "ir-phrases" },
  { pt: "Vocês foram ao show?", en: "Did you (pl.) go to the show?", category_id: "ir-phrases" },
  { pt: "Eles foram ao hotel.", en: "They went to the hotel.", category_id: "ir-phrases" },
  { pt: "Elas foram ao aeroporto.", en: "They (f.) went to the airport.", category_id: "ir-phrases" },
  { pt: "Eu vou ao trabalho todos os dias.", en: "I go to work every day.", category_id: "ir-phrases" },
  { pt: "Você vai à aula agora?", en: "Are you going to class now?", category_id: "ir-phrases" },
  { pt: "Ele vai ao mercado.", en: "He goes to the market.", category_id: "ir-phrases" },
  { pt: "Ela vai à praia hoje.", en: "She's going to the beach today.", category_id: "ir-phrases" },
  { pt: "Nós vamos viajar amanhã.", en: "We're going to travel tomorrow.", category_id: "ir-phrases" },
  { pt: "Vocês vão ao restaurante?", en: "Are you (pl.) going to the restaurant?", category_id: "ir-phrases" },
  { pt: "Eles vão ao cinema.", en: "They're going to the movies.", category_id: "ir-phrases" },
  { pt: "Elas vão à academia.", en: "They (f.) are going to the gym.", category_id: "ir-phrases" },
  { pt: "Eu irei ao Brasil em julho.", en: "I will go to Brazil in July.", category_id: "ir-phrases" },
  { pt: "Você irá à aula amanhã?", en: "Will you go to class tomorrow?", category_id: "ir-phrases" },
  { pt: "Ele irá ao trabalho mais tarde.", en: "He will go to work later.", category_id: "ir-phrases" },
  { pt: "Ela irá ao mercado depois.", en: "She will go to the market later.", category_id: "ir-phrases" },
  { pt: "Nós iremos viajar nas férias.", en: "We will travel on vacation.", category_id: "ir-phrases" },
  { pt: "Vocês irão ao evento?", en: "Will you (pl.) go to the event?", category_id: "ir-phrases" },
  { pt: "Eles irão ao restaurante.", en: "They will go to the restaurant.", category_id: "ir-phrases" },
  { pt: "Elas irão ao show.", en: "They (f.) will go to the show.", category_id: "ir-phrases" },
  { pt: "Eu iria ao Brasil se tivesse tempo.", en: "I would go to Brazil if I had time.", category_id: "ir-phrases" },
  { pt: "Você iria comigo?", en: "Would you go with me?", category_id: "ir-phrases" },
  { pt: "Ele iria ao evento, mas trabalhou.", en: "He would go to the event, but he worked.", category_id: "ir-phrases" },
  { pt: "Ela iria à festa, porém ficou doente.", en: "She would go to the party, but she got sick.", category_id: "ir-phrases" },
  { pt: "Nós iríamos viajar este ano.", en: "We would travel this year.", category_id: "ir-phrases" },
  { pt: "Vocês iriam ao curso se fosse online?", en: "Would you (pl.) go to the course if it were online?", category_id: "ir-phrases" },
  { pt: "Eles iriam ao cinema ontem.", en: "They would go to the movies yesterday.", category_id: "ir-phrases" },
  { pt: "Elas iriam à praia, mas choveu.", en: "They (f.) would go to the beach, but it rained.", category_id: "ir-phrases" },
  { pt: "Parabéns pra você", en: "Congrats to you", category_id: "bday" },
  { pt: "Nesta data querida", en: "On this dear date", category_id: "bday" },
  { pt: "Muitas felicidades", en: "Much happiness", category_id: "bday" },
  { pt: "Muitos anos de vida", en: "Many years of life", category_id: "bday" },
  { pt: "Hoje é dia de festa", en: "Today is day of party", category_id: "bday" },
  { pt: "Não é dia de tristeza", en: "It's not a day for sadness", category_id: "bday" },
  { pt: "Vai buscar teu noivo", en: "Go get your fiancé", category_id: "bday" },
  { pt: "Pra casar com certeza", en: "To get married for sure", category_id: "bday" },
  { pt: "É pique, é pique", en: "It's peak, it's peak", category_id: "bday" },
  { pt: "É hora, é hora", en: "It's time, it's time", category_id: "bday" },
  { pt: "Rá-tim-bum", en: "Hip hip hooray!", category_id: "bday" },
  { pt: "Encontrei", en: "I found", category_id: "quase" },
  { pt: "Lugar", en: "Place", category_id: "quase" },
  { pt: "Perto de mim", en: "Near me / Close to me", category_id: "quase" },
  { pt: "Se chama", en: "Is called / His/Her name is", category_id: "quase" },
  { pt: "Pode ser / Talvez seja", en: "Could be / Maybe it is", category_id: "quase" },
  { pt: "Bem devagar", en: "Very slowly", category_id: "quase" },
  { pt: "Devagar", en: "Slow / Slowly", category_id: "quase" },
  { pt: "Rápido", en: "Fast / Quickly", category_id: "quase" },
  { pt: "Prova", en: "Test / Exam / Proof", category_id: "quase" },
  { pt: "Faz sentido", en: "It makes sense", category_id: "quase" },
  { pt: "Chato", en: "Boring / Annoying", category_id: "quase" },
  { pt: "Entediante", en: "Boring / Tedious", category_id: "quase" },
  { pt: "Barato", en: "Cheap", category_id: "quase" },
  { pt: "Caro", en: "Expensive", category_id: "quase" },
  { pt: "Melancia", en: "Watermelon", category_id: "quase" },
  { pt: "Eu era / Você era / Ele era / Ela era", en: "I was / You were / He was / She was (Imperfeito)", category_id: "quase" },
  { pt: "Nós éramos / Vocês eram / Eles eram / Elas eram", en: "We were / You (pl.) were / They were (Imperfeito)", category_id: "quase" },
  { pt: "Modelos do Japão", en: "Models from Japan", category_id: "quase" },
  { pt: "Hoje", en: "Today", category_id: "quase" },
  { pt: "Tomava", en: "Used to drink / Used to take (Imperfeito)", category_id: "quase" },
  { pt: "Terapeuta", en: "Therapist", category_id: "quase" },
  { pt: "Estudando", en: "Studying", category_id: "quase" },
  { pt: "Doutorado", en: "Doctorate / PhD", category_id: "quase" },
  { pt: "Muito bem", en: "Very well", category_id: "aula-mar27" },
  { pt: "Me mude", en: "Move me / Change me", category_id: "aula-mar27" },
  { pt: "Cidade", en: "City", category_id: "aula-mar27" },
  { pt: "Estado", en: "State", category_id: "aula-mar27" },
  { pt: "Aprovar — aprovei", en: "To approve — I approved", category_id: "aula-mar27" },
  { pt: "Módulo", en: "Module", category_id: "aula-mar27" },
  { pt: "Por", en: "Per / For", category_id: "aula-mar27" },
  { pt: "Coisa", en: "Thing", category_id: "aula-mar27" },
  { pt: "Esquecer", en: "To forget", category_id: "aula-mar27" },
  { pt: "Lembrar", en: "To remember", category_id: "aula-mar27" },
  { pt: "Maravilhoso", en: "Wonderful", category_id: "aula-mar27" },
  { pt: "Os livros estão bons", en: "The books are good", category_id: "aula-mar27" },
  { pt: "Dizer — dizem", en: "To say — they say", category_id: "aula-mar27" },
  { pt: "Ler", en: "To read", category_id: "aula-mar27" },
  { pt: "Presente", en: "Present / Gift", category_id: "aula-mar27" },
  { pt: "Isso aconteceu na festa de natal da minha família", en: "This happened at my family's Christmas party", category_id: "aula-mar27" },
  { pt: "É maravilhoso que você lembra toda a informação e eu esqueceria", en: "It's wonderful that you remember all the information and I would forget", category_id: "aula-mar27" },
  { pt: "Eu não lembro de nada e eu esqueço tudo", en: "I don't remember anything and I forget everything", category_id: "aula-mar27" },
  // Ler — Presente
  { pt: "Eu leio", en: "I read", category_id: "ler-conj" },
  { pt: "Você lê", en: "You read", category_id: "ler-conj" },
  { pt: "Ele/Ela lê", en: "He/She reads", category_id: "ler-conj" },
  { pt: "Nós lemos", en: "We read", category_id: "ler-conj" },
  { pt: "Vocês leem", en: "You all read", category_id: "ler-conj" },
  { pt: "Eles/Elas leem", en: "They read", category_id: "ler-conj" },
  // Ler — Imperfeito
  { pt: "Eu lia", en: "I used to read", category_id: "ler-conj" },
  { pt: "Você lia", en: "You used to read", category_id: "ler-conj" },
  { pt: "Ele/Ela lia", en: "He/She used to read", category_id: "ler-conj" },
  { pt: "Nós líamos", en: "We used to read", category_id: "ler-conj" },
  { pt: "Vocês liam", en: "You all used to read", category_id: "ler-conj" },
  { pt: "Eles/Elas liam", en: "They used to read", category_id: "ler-conj" },
  // Ler — Perfeito
  { pt: "Eu li", en: "I read (past)", category_id: "ler-conj" },
  { pt: "Você leu", en: "You read (past)", category_id: "ler-conj" },
  { pt: "Ele/Ela leu", en: "He/She read (past)", category_id: "ler-conj" },
  { pt: "Nós lemos (past)", en: "We read (past)", category_id: "ler-conj" },
  { pt: "Vocês leram", en: "You all read (past)", category_id: "ler-conj" },
  { pt: "Eles/Elas leram", en: "They read (past)", category_id: "ler-conj" },
  // Ler — Futuro
  { pt: "Eu lerei", en: "I will read", category_id: "ler-conj" },
  { pt: "Você lerá", en: "You will read", category_id: "ler-conj" },
  { pt: "Ele/Ela lerá", en: "He/She will read", category_id: "ler-conj" },
  { pt: "Nós leremos", en: "We will read", category_id: "ler-conj" },
  { pt: "Vocês lerão", en: "You all will read", category_id: "ler-conj" },
  { pt: "Eles/Elas lerão", en: "They will read", category_id: "ler-conj" },
  // Ler — Conditional
  { pt: "Eu leria", en: "I would read", category_id: "ler-conj" },
  { pt: "Você leria", en: "You would read", category_id: "ler-conj" },
  { pt: "Ele/Ela leria", en: "He/She would read", category_id: "ler-conj" },
  { pt: "Nós leríamos", en: "We would read", category_id: "ler-conj" },
  { pt: "Vocês leriam", en: "You all would read", category_id: "ler-conj" },
  { pt: "Eles/Elas leriam", en: "They would read", category_id: "ler-conj" },
  // Esquecer — Presente
  { pt: "Eu esqueço", en: "I forget", category_id: "esquecer-conj" },
  { pt: "Você esquece", en: "You forget", category_id: "esquecer-conj" },
  { pt: "Ele/Ela esquece", en: "He/She forgets", category_id: "esquecer-conj" },
  { pt: "Nós esquecemos", en: "We forget", category_id: "esquecer-conj" },
  { pt: "Vocês esquecem", en: "You all forget", category_id: "esquecer-conj" },
  { pt: "Eles/Elas esquecem", en: "They forget", category_id: "esquecer-conj" },
  // Esquecer — Imperfeito
  { pt: "Eu esquecia", en: "I used to forget", category_id: "esquecer-conj" },
  { pt: "Você esquecia", en: "You used to forget", category_id: "esquecer-conj" },
  { pt: "Ele/Ela esquecia", en: "He/She used to forget", category_id: "esquecer-conj" },
  { pt: "Nós esquecíamos", en: "We used to forget", category_id: "esquecer-conj" },
  { pt: "Vocês esqueciam", en: "You all used to forget", category_id: "esquecer-conj" },
  { pt: "Eles/Elas esqueciam", en: "They used to forget", category_id: "esquecer-conj" },
  // Esquecer — Perfeito
  { pt: "Eu esqueci", en: "I forgot", category_id: "esquecer-conj" },
  { pt: "Você esqueceu", en: "You forgot", category_id: "esquecer-conj" },
  { pt: "Ele/Ela esqueceu", en: "He/She forgot", category_id: "esquecer-conj" },
  { pt: "Nós esquecemos (past)", en: "We forgot", category_id: "esquecer-conj" },
  { pt: "Vocês esqueceram", en: "You all forgot", category_id: "esquecer-conj" },
  { pt: "Eles/Elas esqueceram", en: "They forgot", category_id: "esquecer-conj" },
  // Esquecer — Futuro
  { pt: "Eu esquecerei", en: "I will forget", category_id: "esquecer-conj" },
  { pt: "Você esquecerá", en: "You will forget", category_id: "esquecer-conj" },
  { pt: "Ele/Ela esquecerá", en: "He/She will forget", category_id: "esquecer-conj" },
  { pt: "Nós esqueceremos", en: "We will forget", category_id: "esquecer-conj" },
  { pt: "Vocês esquecerão", en: "You all will forget", category_id: "esquecer-conj" },
  { pt: "Eles/Elas esquecerão", en: "They will forget", category_id: "esquecer-conj" },
  // Esquecer — Conditional
  { pt: "Eu esqueceria", en: "I would forget", category_id: "esquecer-conj" },
  { pt: "Você esqueceria", en: "You would forget", category_id: "esquecer-conj" },
  { pt: "Ele/Ela esqueceria", en: "He/She would forget", category_id: "esquecer-conj" },
  { pt: "Nós esqueceríamos", en: "We would forget", category_id: "esquecer-conj" },
  { pt: "Vocês esqueceriam", en: "You all would forget", category_id: "esquecer-conj" },
  { pt: "Eles/Elas esqueceriam", en: "They would forget", category_id: "esquecer-conj" },
  // Lembrar — Presente
  { pt: "Eu lembro", en: "I remember", category_id: "lembrar-conj" },
  { pt: "Você lembra", en: "You remember", category_id: "lembrar-conj" },
  { pt: "Ele/Ela lembra", en: "He/She remembers", category_id: "lembrar-conj" },
  { pt: "Nós lembramos", en: "We remember", category_id: "lembrar-conj" },
  { pt: "Vocês lembram", en: "You all remember", category_id: "lembrar-conj" },
  { pt: "Eles/Elas lembram", en: "They remember", category_id: "lembrar-conj" },
  // Lembrar — Imperfeito
  { pt: "Eu lembrava", en: "I used to remember", category_id: "lembrar-conj" },
  { pt: "Você lembrava", en: "You used to remember", category_id: "lembrar-conj" },
  { pt: "Ele/Ela lembrava", en: "He/She used to remember", category_id: "lembrar-conj" },
  { pt: "Nós lembrávamos", en: "We used to remember", category_id: "lembrar-conj" },
  { pt: "Vocês lembravam", en: "You all used to remember", category_id: "lembrar-conj" },
  { pt: "Eles/Elas lembravam", en: "They used to remember", category_id: "lembrar-conj" },
  // Lembrar — Perfeito
  { pt: "Eu lembrei", en: "I remembered", category_id: "lembrar-conj" },
  { pt: "Você lembrou", en: "You remembered", category_id: "lembrar-conj" },
  { pt: "Ele/Ela lembrou", en: "He/She remembered", category_id: "lembrar-conj" },
  { pt: "Nós lembramos (past)", en: "We remembered", category_id: "lembrar-conj" },
  { pt: "Vocês lembraram", en: "You all remembered", category_id: "lembrar-conj" },
  { pt: "Eles/Elas lembraram", en: "They remembered", category_id: "lembrar-conj" },
  // Lembrar — Futuro
  { pt: "Eu lembrarei", en: "I will remember", category_id: "lembrar-conj" },
  { pt: "Você lembrará", en: "You will remember", category_id: "lembrar-conj" },
  { pt: "Ele/Ela lembrará", en: "He/She will remember", category_id: "lembrar-conj" },
  { pt: "Nós lembraremos", en: "We will remember", category_id: "lembrar-conj" },
  { pt: "Vocês lembrarão", en: "You all will remember", category_id: "lembrar-conj" },
  { pt: "Eles/Elas lembrarão", en: "They will remember", category_id: "lembrar-conj" },
  // Lembrar — Conditional
  { pt: "Eu lembraria", en: "I would remember", category_id: "lembrar-conj" },
  { pt: "Você lembraria", en: "You would remember", category_id: "lembrar-conj" },
  { pt: "Ele/Ela lembraria", en: "He/She would remember", category_id: "lembrar-conj" },
  { pt: "Nós lembraríamos", en: "We would remember", category_id: "lembrar-conj" },
  { pt: "Vocês lembrariam", en: "You all would remember", category_id: "lembrar-conj" },
  { pt: "Eles/Elas lembrariam", en: "They would remember", category_id: "lembrar-conj" },
  // Dizer — Presente
  { pt: "Eu digo", en: "I say", category_id: "dizer-conj" },
  { pt: "Você diz", en: "You say", category_id: "dizer-conj" },
  { pt: "Ele/Ela diz", en: "He/She says", category_id: "dizer-conj" },
  { pt: "Nós dizemos", en: "We say", category_id: "dizer-conj" },
  { pt: "Vocês dizem", en: "You all say", category_id: "dizer-conj" },
  { pt: "Eles/Elas dizem", en: "They say", category_id: "dizer-conj" },
  // Dizer — Imperfeito
  { pt: "Eu dizia", en: "I used to say", category_id: "dizer-conj" },
  { pt: "Você dizia", en: "You used to say", category_id: "dizer-conj" },
  { pt: "Ele/Ela dizia", en: "He/She used to say", category_id: "dizer-conj" },
  { pt: "Nós dizíamos", en: "We used to say", category_id: "dizer-conj" },
  { pt: "Vocês diziam", en: "You all used to say", category_id: "dizer-conj" },
  { pt: "Eles/Elas diziam", en: "They used to say", category_id: "dizer-conj" },
  // Dizer — Perfeito
  { pt: "Eu disse", en: "I said", category_id: "dizer-conj" },
  { pt: "Você disse", en: "You said", category_id: "dizer-conj" },
  { pt: "Ele/Ela disse", en: "He/She said", category_id: "dizer-conj" },
  { pt: "Nós dissemos", en: "We said", category_id: "dizer-conj" },
  { pt: "Vocês disseram", en: "You all said", category_id: "dizer-conj" },
  { pt: "Eles/Elas disseram", en: "They said", category_id: "dizer-conj" },
  // Dizer — Futuro
  { pt: "Eu direi", en: "I will say", category_id: "dizer-conj" },
  { pt: "Você dirá", en: "You will say", category_id: "dizer-conj" },
  { pt: "Ele/Ela dirá", en: "He/She will say", category_id: "dizer-conj" },
  { pt: "Nós diremos", en: "We will say", category_id: "dizer-conj" },
  { pt: "Vocês dirão", en: "You all will say", category_id: "dizer-conj" },
  { pt: "Eles/Elas dirão", en: "They will say", category_id: "dizer-conj" },
  // Dizer — Conditional
  { pt: "Eu diria", en: "I would say", category_id: "dizer-conj" },
  { pt: "Você diria", en: "You would say", category_id: "dizer-conj" },
  { pt: "Ele/Ela diria", en: "He/She would say", category_id: "dizer-conj" },
  { pt: "Nós diríamos", en: "We would say", category_id: "dizer-conj" },
  { pt: "Vocês diriam", en: "You all would say", category_id: "dizer-conj" },
  { pt: "Eles/Elas diriam", en: "They would say", category_id: "dizer-conj" },
  { pt: "Opa", en: "Hey / What's up", category_id: "aula-mar30" },
  { pt: "Tudo bom", en: "All good / How's it going", category_id: "aula-mar30" },
  { pt: "Oi", en: "Hi", category_id: "aula-mar30" },
  { pt: "Do sábado pro domingo", en: "From Saturday to Sunday", category_id: "aula-mar30" },
  { pt: "Eu fui irritado", en: "I was irritated (went there irritated)", category_id: "aula-mar30" },
  { pt: "Eu estava irritado", en: "I was irritated (ongoing state)", category_id: "aula-mar30" },
  { pt: "Pouco", en: "A little / Few", category_id: "aula-mar30" },
  { pt: "Você viu o site que eu tive que mudar?", en: "Did you see the site that I had to change?", category_id: "aula-mar30" },
  { pt: "Enviar", en: "To send (letters / emails)", category_id: "aula-mar30" },
  { pt: "Mandar", en: "To send / To order", category_id: "aula-mar30" },
  { pt: "Mudar", en: "To change / To move", category_id: "aula-mar30" },
  { pt: "Me testa", en: "Test me", category_id: "aula-mar30" },
  { pt: "Provar", en: "To prove / To taste / To try on", category_id: "aula-mar30" },
  { pt: "Tentar", en: "To try", category_id: "aula-mar30" },
  { pt: "Eu gosto", en: "I like", category_id: "aula-mar30" },
  { pt: "Eu vou conseguir uma pra você", en: "I'm going to get one for you", category_id: "aula-mar30" },
  { pt: "Eu vou te dar uma", en: "I'm going to give you one", category_id: "aula-mar30" },
  { pt: "Te", en: "You (object pronoun)", category_id: "aula-mar30" },
  { pt: "Dar", en: "To give", category_id: "aula-mar30" },
  { pt: "Tudo", en: "Everything", category_id: "aula-mar30" },
  { pt: "Todo", en: "Full / Every / All", category_id: "aula-mar30" },
  { pt: "Tudo em todo lugar ao mesmo tempo", en: "Everything everywhere all at once", category_id: "aula-mar30" },
  { pt: "Chorar", en: "To cry", category_id: "aula-mar30" },
  { pt: "Ver", en: "To see", category_id: "aula-mar30" },
  { pt: "Vir", en: "To come", category_id: "aula-mar30" },
  { pt: "Eu sempre choro quando eu voo e eu vejo um filme", en: "I always cry when I fly and I watch a movie", category_id: "aula-mar30" },
  { pt: "Você me dá dever de casa, eu te dou dever de casa", en: "You give me homework, I give you homework", category_id: "aula-mar30" },
  { pt: "Relaxar", en: "To relax", category_id: "aula-mar30" },
  { pt: "Relaxando", en: "Relaxing", category_id: "aula-mar30" },
  { pt: "Assistir", en: "To watch (shows / TV)", category_id: "aula-mar30" },
  { pt: "Dever de casa", en: "Homework", category_id: "aula-mar30" },
  { pt: "Capitão Fantástico", en: "Captain Fantastic", category_id: "aula-mar30" },
  { pt: "Tocar", en: "To play (instrument) / To touch", category_id: "aula-mar30" },
  { pt: "Treinar", en: "To train", category_id: "aula-mar30" },
  { pt: "Treinador", en: "Trainer / Coach", category_id: "aula-mar30" },
  { pt: "Consertar", en: "To fix", category_id: "april-fools" },
  { pt: "Minha coisa nova favorita", en: "My new favorite thing", category_id: "april-fools" },
  { pt: "Almoço por peso", en: "Lunch by weight", category_id: "april-fools" },
  { pt: "Todo lugar que eu vou eles", en: "Every place I go they", category_id: "april-fools" },
  { pt: "Variedade", en: "Variety", category_id: "april-fools" },
  { pt: "Feijão", en: "Beans", category_id: "april-fools" },
  { pt: "Colocar / Botar", en: "To put / To place", category_id: "april-fools" },
  { pt: "Me diz", en: "Tell me", category_id: "april-fools" },
  { pt: "Farofa", en: "Farofa (toasted cassava flour)", category_id: "april-fools" },
  { pt: "Saudade", en: "Longing / Missing", category_id: "april-fools" },
  { pt: "Farofa é engraçada porque não tem motivo/razão pra gostar, mas você gosta", en: "Farofa is funny because there's no reason to like it, but you do", category_id: "april-fools" },
  { pt: "Sabor", en: "Flavor", category_id: "april-fools" },
  { pt: "Tempero", en: "Seasoning", category_id: "april-fools" },
  { pt: "Se", en: "If", category_id: "april-fools" },
  { pt: "Farinha", en: "Flour", category_id: "april-fools" },
  { pt: "Eu não sei", en: "I don't know", category_id: "april-fools" },
  { pt: "Impressionar", en: "To impress", category_id: "april-fools" },
  { pt: "Com minha fala", en: "With my speech", category_id: "april-fools" },
  { pt: "Escutar / Ouvir", en: "To hear / To listen", category_id: "april-fools" },
  { pt: "Único / Única", en: "Unique", category_id: "april-fools" },
  { pt: "Eu estou ansiosa / animada", en: "I am anxious / excited", category_id: "april-fools" },
  { pt: "Destaque", en: "Highlight", category_id: "april-fools" },
  { pt: "Ensinar", en: "To teach", category_id: "april-fools" },
  { pt: "Humor", en: "Humor", category_id: "april-fools" },
  { pt: "Engraçado", en: "Funny", category_id: "april-fools" },
  { pt: "Piadas", en: "Jokes", category_id: "april-fools" },
  { pt: "Eu vou te ensinar a ser engraçada", en: "I'm going to teach you to be funny", category_id: "april-fools" },
  { pt: "Todo dia é igual", en: "Every day is the same", category_id: "april2" },
  { pt: "Todos os dias são iguais", en: "Every day is the same (plural)", category_id: "april2" },
  { pt: "Entediado", en: "Bored", category_id: "april2" },
  { pt: "Eventualmente", en: "Eventually", category_id: "april2" },
  { pt: "Passagem", en: "Ticket / passage", category_id: "april2" },
  { pt: "Assim", en: "Like this / so", category_id: "april2" },
  { pt: "Poderia", en: "Could", category_id: "april2" },
  { pt: "Eu poderia fazer", en: "I could do", category_id: "april2" },
  { pt: "Visitante", en: "Visitor", category_id: "april2" },
  { pt: "Visitar", en: "To visit", category_id: "april2" },
  { pt: "Esperança", en: "Hope", category_id: "april2" },
  { pt: "Esperançosamente", en: "Hopefully", category_id: "april2" },
  { pt: "Poderiam", en: "They could", category_id: "april2" },
  { pt: "Feito", en: "Done / made", category_id: "april2" },
  { pt: "Feio", en: "Ugly", category_id: "april2" },
  { pt: "Achei", en: "I found / I thought", category_id: "april2" },
  { pt: "Basicamente", en: "Basically", category_id: "april2" },
  { pt: "Por causa", en: "Because of", category_id: "april2" },
  { pt: "Desistir", en: "To give up", category_id: "april2" },
  { pt: "Páscoa", en: "Easter", category_id: "april2" },
  { pt: "Eu tenho uma dúvida", en: "I have a question / doubt", category_id: "april2" },
  { pt: "Já ouviu falar", en: "Have you heard of", category_id: "april2" },
  { pt: "Frase", en: "Sentence / phrase", category_id: "april2" },
  { pt: "Graças a Deus é sexta", en: "Thank God it's Friday", category_id: "april2" },
  { pt: "Sextou", en: "It's Friday! (slang)", category_id: "april2" },
  { pt: "fds - final de semana", en: "Weekend", category_id: "april2" },
  { pt: "Eu não tenho planos", en: "I don't have plans", category_id: "april2" },
  { pt: "Descobrir", en: "To discover / find out", category_id: "april2" },
  { pt: "Eu não sabia", en: "I didn't know", category_id: "april2" },
  { pt: "Eu amo animais", en: "I love animals", category_id: "april2" },
  { pt: "Fazenda", en: "Farm", category_id: "april2" },
  { pt: "Aposentada", en: "Retired (f)", category_id: "april2" },
  { pt: "No meio do nada", en: "In the middle of nowhere", category_id: "april2" },
  // Ser — Presente
  { pt: "Eu sou", en: "I am", category_id: "ser-conj" },
  { pt: "Você é", en: "You are", category_id: "ser-conj" },
  { pt: "Ele/Ela é", en: "He/She is", category_id: "ser-conj" },
  { pt: "Nós somos", en: "We are", category_id: "ser-conj" },
  { pt: "Vocês são", en: "You all are", category_id: "ser-conj" },
  { pt: "Eles/Elas são", en: "They are", category_id: "ser-conj" },
  // Ser — Imperfeito
  { pt: "Eu era", en: "I used to be", category_id: "ser-conj" },
  { pt: "Você era", en: "You used to be", category_id: "ser-conj" },
  { pt: "Ele/Ela era", en: "He/She used to be", category_id: "ser-conj" },
  { pt: "Nós éramos", en: "We used to be", category_id: "ser-conj" },
  { pt: "Vocês eram", en: "You all used to be", category_id: "ser-conj" },
  { pt: "Eles/Elas eram", en: "They used to be", category_id: "ser-conj" },
  // Ser — Perfeito (disambiguated with "(ser)" since Ir shares these forms)
  { pt: "Eu fui (ser)", en: "I was", category_id: "ser-conj" },
  { pt: "Você foi (ser)", en: "You were", category_id: "ser-conj" },
  { pt: "Ele/Ela foi (ser)", en: "He/She was", category_id: "ser-conj" },
  { pt: "Nós fomos (ser)", en: "We were", category_id: "ser-conj" },
  { pt: "Vocês foram (ser)", en: "You all were", category_id: "ser-conj" },
  { pt: "Eles/Elas foram (ser)", en: "They were", category_id: "ser-conj" },
  // Ser — Futuro
  { pt: "Eu serei", en: "I will be", category_id: "ser-conj" },
  { pt: "Você será", en: "You will be", category_id: "ser-conj" },
  { pt: "Ele/Ela será", en: "He/She will be", category_id: "ser-conj" },
  { pt: "Nós seremos", en: "We will be", category_id: "ser-conj" },
  { pt: "Vocês serão", en: "You all will be", category_id: "ser-conj" },
  { pt: "Eles/Elas serão", en: "They will be", category_id: "ser-conj" },
  // Ser — Conditional
  { pt: "Eu seria", en: "I would be", category_id: "ser-conj" },
  { pt: "Você seria", en: "You would be", category_id: "ser-conj" },
  { pt: "Ele/Ela seria", en: "He/She would be", category_id: "ser-conj" },
  { pt: "Nós seríamos", en: "We would be", category_id: "ser-conj" },
  { pt: "Vocês seriam", en: "You all would be", category_id: "ser-conj" },
  { pt: "Eles/Elas seriam", en: "They would be", category_id: "ser-conj" },

  // Ter — Presente
  { pt: "Eu tenho", en: "I have", category_id: "ter-conj" },
  { pt: "Você tem", en: "You have", category_id: "ter-conj" },
  { pt: "Ele/Ela tem", en: "He/She has", category_id: "ter-conj" },
  { pt: "Nós temos", en: "We have", category_id: "ter-conj" },
  { pt: "Vocês têm", en: "You all have", category_id: "ter-conj" },
  { pt: "Eles/Elas têm", en: "They have", category_id: "ter-conj" },
  // Ter — Imperfeito
  { pt: "Eu tinha", en: "I had / I used to have", category_id: "ter-conj" },
  { pt: "Você tinha", en: "You had / You used to have", category_id: "ter-conj" },
  { pt: "Ele/Ela tinha", en: "He/She had", category_id: "ter-conj" },
  { pt: "Nós tínhamos", en: "We had / We used to have", category_id: "ter-conj" },
  { pt: "Vocês tinham", en: "You all had", category_id: "ter-conj" },
  { pt: "Eles/Elas tinham", en: "They had", category_id: "ter-conj" },
  // Ter — Perfeito
  { pt: "Eu tive", en: "I had", category_id: "ter-conj" },
  { pt: "Você teve", en: "You had", category_id: "ter-conj" },
  { pt: "Ele/Ela teve", en: "He/She had", category_id: "ter-conj" },
  { pt: "Nós tivemos", en: "We had", category_id: "ter-conj" },
  { pt: "Vocês tiveram", en: "You all had", category_id: "ter-conj" },
  { pt: "Eles/Elas tiveram", en: "They had", category_id: "ter-conj" },
  // Ter — Conditional
  { pt: "Eu teria", en: "I would have", category_id: "ter-conj" },
  { pt: "Você teria", en: "You would have", category_id: "ter-conj" },
  { pt: "Ele/Ela teria", en: "He/She would have", category_id: "ter-conj" },
  { pt: "Nós teríamos", en: "We would have", category_id: "ter-conj" },
  { pt: "Vocês teriam", en: "You all would have", category_id: "ter-conj" },
  { pt: "Eles/Elas teriam", en: "They would have", category_id: "ter-conj" },

  // Poder — Presente
  { pt: "Eu posso", en: "I can", category_id: "poder-conj" },
  { pt: "Você pode", en: "You can", category_id: "poder-conj" },
  { pt: "Ele/Ela pode", en: "He/She can", category_id: "poder-conj" },
  { pt: "Nós podemos", en: "We can", category_id: "poder-conj" },
  { pt: "Vocês podem", en: "You all can", category_id: "poder-conj" },
  { pt: "Eles/Elas podem", en: "They can", category_id: "poder-conj" },
  // Poder — Imperfeito
  { pt: "Eu podia", en: "I could / I used to be able to", category_id: "poder-conj" },
  { pt: "Você podia", en: "You could", category_id: "poder-conj" },
  { pt: "Ele/Ela podia", en: "He/She could", category_id: "poder-conj" },
  { pt: "Nós podíamos", en: "We could / We used to be able to", category_id: "poder-conj" },
  { pt: "Vocês podiam", en: "You all could", category_id: "poder-conj" },
  { pt: "Eles/Elas podiam", en: "They could", category_id: "poder-conj" },
  // Poder — Perfeito
  { pt: "Eu pude", en: "I was able to", category_id: "poder-conj" },
  { pt: "Você pôde", en: "You were able to", category_id: "poder-conj" },
  { pt: "Ele/Ela pôde", en: "He/She was able to", category_id: "poder-conj" },
  { pt: "Nós pudemos", en: "We were able to", category_id: "poder-conj" },
  { pt: "Vocês puderam", en: "You all were able to", category_id: "poder-conj" },
  { pt: "Eles/Elas puderam", en: "They were able to", category_id: "poder-conj" },
  // Poder — Conditional
  { pt: "Eu poderia", en: "I could / I would be able to", category_id: "poder-conj" },
  { pt: "Você poderia", en: "You could", category_id: "poder-conj" },
  { pt: "Ele/Ela poderia", en: "He/She could", category_id: "poder-conj" },
  { pt: "Nós poderíamos", en: "We could", category_id: "poder-conj" },
  { pt: "Vocês poderiam", en: "You all could", category_id: "poder-conj" },
  { pt: "Eles/Elas poderiam", en: "They could", category_id: "poder-conj" },

  // Querer — Presente
  { pt: "Eu quero", en: "I want", category_id: "querer-conj" },
  { pt: "Você quer", en: "You want", category_id: "querer-conj" },
  { pt: "Ele/Ela quer", en: "He/She wants", category_id: "querer-conj" },
  { pt: "Nós queremos", en: "We want", category_id: "querer-conj" },
  { pt: "Vocês querem", en: "You all want", category_id: "querer-conj" },
  { pt: "Eles/Elas querem", en: "They want", category_id: "querer-conj" },
  // Querer — Imperfeito
  { pt: "Eu queria", en: "I wanted / I used to want", category_id: "querer-conj" },
  { pt: "Você queria", en: "You wanted", category_id: "querer-conj" },
  { pt: "Ele/Ela queria", en: "He/She wanted", category_id: "querer-conj" },
  { pt: "Nós queríamos", en: "We wanted", category_id: "querer-conj" },
  { pt: "Vocês queriam", en: "You all wanted", category_id: "querer-conj" },
  { pt: "Eles/Elas queriam", en: "They wanted", category_id: "querer-conj" },
  // Querer — Perfeito
  { pt: "Eu quis", en: "I wanted", category_id: "querer-conj" },
  { pt: "Você quis", en: "You wanted", category_id: "querer-conj" },
  { pt: "Ele/Ela quis", en: "He/She wanted", category_id: "querer-conj" },
  { pt: "Nós quisemos", en: "We wanted", category_id: "querer-conj" },
  { pt: "Vocês quiseram", en: "You all wanted", category_id: "querer-conj" },
  { pt: "Eles/Elas quiseram", en: "They wanted", category_id: "querer-conj" },
  // Querer — Conditional
  { pt: "Eu quereria", en: "I would want", category_id: "querer-conj" },
  { pt: "Você quereria", en: "You would want", category_id: "querer-conj" },
  { pt: "Ele/Ela quereria", en: "He/She would want", category_id: "querer-conj" },
  { pt: "Nós quereríamos", en: "We would want", category_id: "querer-conj" },
  { pt: "Vocês quereriam", en: "You all would want", category_id: "querer-conj" },
  { pt: "Eles/Elas quereriam", en: "They would want", category_id: "querer-conj" },

  // Saber — Presente
  { pt: "Eu sei", en: "I know", category_id: "saber-conj" },
  { pt: "Você sabe", en: "You know", category_id: "saber-conj" },
  { pt: "Ele/Ela sabe", en: "He/She knows", category_id: "saber-conj" },
  { pt: "Nós sabemos", en: "We know", category_id: "saber-conj" },
  { pt: "Vocês sabem", en: "You all know", category_id: "saber-conj" },
  { pt: "Eles/Elas sabem", en: "They know", category_id: "saber-conj" },
  // Saber — Imperfeito
  { pt: "Eu sabia", en: "I knew / I used to know", category_id: "saber-conj" },
  { pt: "Você sabia", en: "You knew", category_id: "saber-conj" },
  { pt: "Ele/Ela sabia", en: "He/She knew", category_id: "saber-conj" },
  { pt: "Nós sabíamos", en: "We knew", category_id: "saber-conj" },
  { pt: "Vocês sabiam", en: "You all knew", category_id: "saber-conj" },
  { pt: "Eles/Elas sabiam", en: "They knew", category_id: "saber-conj" },
  // Saber — Perfeito
  { pt: "Eu soube", en: "I found out", category_id: "saber-conj" },
  { pt: "Você soube", en: "You found out", category_id: "saber-conj" },
  { pt: "Ele/Ela soube", en: "He/She found out", category_id: "saber-conj" },
  { pt: "Nós soubemos", en: "We found out", category_id: "saber-conj" },
  { pt: "Vocês souberam", en: "You all found out", category_id: "saber-conj" },
  { pt: "Eles/Elas souberam", en: "They found out", category_id: "saber-conj" },
  // Saber — Conditional
  { pt: "Eu saberia", en: "I would know", category_id: "saber-conj" },
  { pt: "Você saberia", en: "You would know", category_id: "saber-conj" },
  { pt: "Ele/Ela saberia", en: "He/She would know", category_id: "saber-conj" },
  { pt: "Nós saberíamos", en: "We would know", category_id: "saber-conj" },
  { pt: "Vocês saberiam", en: "You all would know", category_id: "saber-conj" },
  { pt: "Eles/Elas saberiam", en: "They would know", category_id: "saber-conj" },

  // Dar — Presente
  { pt: "Eu dou", en: "I give", category_id: "dar-conj" },
  { pt: "Você dá", en: "You give", category_id: "dar-conj" },
  { pt: "Ele/Ela dá", en: "He/She gives", category_id: "dar-conj" },
  { pt: "Nós damos", en: "We give", category_id: "dar-conj" },
  { pt: "Vocês dão", en: "You all give", category_id: "dar-conj" },
  { pt: "Eles/Elas dão", en: "They give", category_id: "dar-conj" },
  // Dar — Imperfeito
  { pt: "Eu dava", en: "I gave / I used to give", category_id: "dar-conj" },
  { pt: "Você dava", en: "You gave / You used to give", category_id: "dar-conj" },
  { pt: "Ele/Ela dava", en: "He/She gave", category_id: "dar-conj" },
  { pt: "Nós dávamos", en: "We gave / We used to give", category_id: "dar-conj" },
  { pt: "Vocês davam", en: "You all gave", category_id: "dar-conj" },
  { pt: "Eles/Elas davam", en: "They gave", category_id: "dar-conj" },
  // Dar — Perfeito
  { pt: "Eu dei", en: "I gave", category_id: "dar-conj" },
  { pt: "Você deu", en: "You gave", category_id: "dar-conj" },
  { pt: "Ele/Ela deu", en: "He/She gave", category_id: "dar-conj" },
  { pt: "Nós demos", en: "We gave", category_id: "dar-conj" },
  { pt: "Vocês deram", en: "You all gave", category_id: "dar-conj" },
  { pt: "Eles/Elas deram", en: "They gave", category_id: "dar-conj" },
  // Dar — Conditional
  { pt: "Eu daria", en: "I would give", category_id: "dar-conj" },
  { pt: "Você daria", en: "You would give", category_id: "dar-conj" },
  { pt: "Ele/Ela daria", en: "He/She would give", category_id: "dar-conj" },
  { pt: "Nós daríamos", en: "We would give", category_id: "dar-conj" },
  { pt: "Vocês dariam", en: "You all would give", category_id: "dar-conj" },
  { pt: "Eles/Elas dariam", en: "They would give", category_id: "dar-conj" },

  // Ver — Presente
  { pt: "Eu vejo", en: "I see", category_id: "ver-conj" },
  { pt: "Você vê", en: "You see", category_id: "ver-conj" },
  { pt: "Ele/Ela vê", en: "He/She sees", category_id: "ver-conj" },
  { pt: "Nós vemos", en: "We see", category_id: "ver-conj" },
  { pt: "Vocês veem", en: "You all see", category_id: "ver-conj" },
  { pt: "Eles/Elas veem", en: "They see", category_id: "ver-conj" },
  // Ver — Imperfeito
  { pt: "Eu via", en: "I saw / I used to see", category_id: "ver-conj" },
  { pt: "Você via", en: "You saw / You used to see", category_id: "ver-conj" },
  { pt: "Ele/Ela via", en: "He/She saw", category_id: "ver-conj" },
  { pt: "Nós víamos", en: "We saw / We used to see", category_id: "ver-conj" },
  { pt: "Vocês viam", en: "You all saw", category_id: "ver-conj" },
  { pt: "Eles/Elas viam", en: "They saw", category_id: "ver-conj" },
  // Ver — Perfeito
  { pt: "Eu vi", en: "I saw", category_id: "ver-conj" },
  { pt: "Você viu", en: "You saw", category_id: "ver-conj" },
  { pt: "Ele/Ela viu", en: "He/She saw", category_id: "ver-conj" },
  { pt: "Nós vimos", en: "We saw", category_id: "ver-conj" },
  { pt: "Vocês viram", en: "You all saw", category_id: "ver-conj" },
  { pt: "Eles/Elas viram", en: "They saw", category_id: "ver-conj" },
  // Ver — Conditional
  { pt: "Eu veria", en: "I would see", category_id: "ver-conj" },
  { pt: "Você veria", en: "You would see", category_id: "ver-conj" },
  { pt: "Ele/Ela veria", en: "He/She would see", category_id: "ver-conj" },
  { pt: "Nós veríamos", en: "We would see", category_id: "ver-conj" },
  { pt: "Vocês veriam", en: "You all would see", category_id: "ver-conj" },
  { pt: "Eles/Elas veriam", en: "They would see", category_id: "ver-conj" },

  // Vir — Presente
  { pt: "Eu venho", en: "I come", category_id: "vir-conj" },
  { pt: "Você vem", en: "You come", category_id: "vir-conj" },
  { pt: "Ele/Ela vem", en: "He/She comes", category_id: "vir-conj" },
  { pt: "Nós vimos", en: "We come", category_id: "vir-conj" },
  { pt: "Vocês vêm", en: "You all come", category_id: "vir-conj" },
  { pt: "Eles/Elas vêm", en: "They come", category_id: "vir-conj" },
  // Vir — Imperfeito
  { pt: "Eu vinha", en: "I came / I used to come", category_id: "vir-conj" },
  { pt: "Você vinha", en: "You came / You used to come", category_id: "vir-conj" },
  { pt: "Ele/Ela vinha", en: "He/She came", category_id: "vir-conj" },
  { pt: "Nós vínhamos", en: "We came / We used to come", category_id: "vir-conj" },
  { pt: "Vocês vinham", en: "You all came", category_id: "vir-conj" },
  { pt: "Eles/Elas vinham", en: "They came", category_id: "vir-conj" },
  // Vir — Perfeito
  { pt: "Eu vim", en: "I came", category_id: "vir-conj" },
  { pt: "Você veio", en: "You came", category_id: "vir-conj" },
  { pt: "Ele/Ela veio", en: "He/She came", category_id: "vir-conj" },
  { pt: "Nós viemos", en: "We came", category_id: "vir-conj" },
  { pt: "Vocês vieram", en: "You all came", category_id: "vir-conj" },
  { pt: "Eles/Elas vieram", en: "They came", category_id: "vir-conj" },
  // Vir — Conditional
  { pt: "Eu viria", en: "I would come", category_id: "vir-conj" },
  { pt: "Você viria", en: "You would come", category_id: "vir-conj" },
  { pt: "Ele/Ela viria", en: "He/She would come", category_id: "vir-conj" },
  { pt: "Nós viríamos", en: "We would come", category_id: "vir-conj" },
  { pt: "Vocês viriam", en: "You all would come", category_id: "vir-conj" },
  { pt: "Eles/Elas viriam", en: "They would come", category_id: "vir-conj" }
];

module.exports = { categories, cards };
