const categories = [
  { id: "fitness", label: "Fitness", css_class: "cat-fitness" },
  { id: "vocab", label: "Vocabulary", css_class: "cat-vocab" },
  { id: "phrases", label: "Phrases", css_class: "cat-phrases" },
  { id: "verbs", label: "Verbs", css_class: "cat-verbs" },
  { id: "weather", label: "Weather", css_class: "cat-weather" },
  { id: "daily", label: "Daily Life", css_class: "cat-daily" },
  { id: "time", label: "Time & Days", css_class: "cat-time" },
  { id: "ir-phrases", label: "IR Phrases", css_class: "cat-ir-phrases" },
  { id: "ir-conj", label: "IR Conjugations", css_class: "cat-ir-conj" },
  { id: "bday", label: "Birthday", css_class: "cat-bday" },
  { id: "quase", label: "Quase", css_class: "cat-quase" },
  { id: "aula-mar27", label: "Aula Mar 27", css_class: "cat-aula-mar27" },
  { id: "ler-conj", label: "Ler Conjugations", css_class: "cat-ler-conj" },
  { id: "esquecer-conj", label: "Esquecer Conjugations", css_class: "cat-esquecer-conj" },
  { id: "lembrar-conj", label: "Lembrar Conjugations", css_class: "cat-lembrar-conj" },
  { id: "dizer-conj", label: "Dizer Conjugations", css_class: "cat-dizer-conj" },
  { id: "aula-mar30", label: "Aula Mar 30", css_class: "cat-aula-mar30" },
  { id: "april-fools", label: "April Fools", css_class: "cat-april-fools" },
  { id: "april2", label: "April 2", css_class: "cat-april2" }
];

const cards = [
  { pt: "Algo novo", en: "Something new", category_id: "vocab" },
  { pt: "Sobre", en: "About", category_id: "vocab" },
  { pt: "Atualmente só corro", en: "Currently I only run", category_id: "phrases" },
  { pt: "Eu não treino", en: "I don't work out", category_id: "phrases" },
  { pt: "Eu não tenho paciência", en: "I don't have patience", category_id: "phrases" },
  { pt: "Eu preciso de um plano", en: "I need a plan", category_id: "phrases" },
  { pt: "Musculação", en: "Weight training / Bodybuilding", category_id: "fitness" },
  { pt: "Levantar peso", en: "To lift weights", category_id: "fitness" },
  { pt: "Hoje é dia de…", en: "Today is the day for…", category_id: "phrases" },
  { pt: "Hoje eu vou treinar…", en: "Today I'm going to train…", category_id: "phrases" },
  { pt: "Hoje eu vou fazer cardio", en: "Today I'm going to do cardio", category_id: "phrases" },
  { pt: "Abdômen", en: "Abs", category_id: "fitness" },
  { pt: "Pernas", en: "Legs", category_id: "fitness" },
  { pt: "Inferiores", en: "Lower (body)", category_id: "fitness" },
  { pt: "Posteriores", en: "Hamstrings", category_id: "fitness" },
  { pt: "Quadríceps", en: "Quads", category_id: "fitness" },
  { pt: "Panturrilha", en: "Calves", category_id: "fitness" },
  { pt: "Glúteos", en: "Glutes", category_id: "fitness" },
  { pt: "Braços", en: "Arms", category_id: "fitness" },
  { pt: "Superiores", en: "Upper (body)", category_id: "fitness" },
  { pt: "Peito", en: "Chest", category_id: "fitness" },
  { pt: "Ombros", en: "Shoulders", category_id: "fitness" },
  { pt: "Bíceps", en: "Biceps", category_id: "fitness" },
  { pt: "Tríceps", en: "Triceps", category_id: "fitness" },
  { pt: "Trapézio", en: "Traps / Trapezius", category_id: "fitness" },
  { pt: "Costas", en: "Back", category_id: "fitness" },
  { pt: "Pescoço", en: "Neck", category_id: "fitness" },
  { pt: "Antebraço", en: "Forearm", category_id: "fitness" },
  { pt: "Elevação pélvica", en: "Hip thrust", category_id: "fitness" },
  { pt: "Barra", en: "Barbell / Bar", category_id: "fitness" },
  { pt: "Agachamento", en: "Squat", category_id: "fitness" },
  { pt: "Supino", en: "Bench press", category_id: "fitness" },
  { pt: "Elevação lateral", en: "Lateral raise", category_id: "fitness" },
  { pt: "Elevação frontal", en: "Front raise", category_id: "fitness" },
  { pt: "Peso livre", en: "Free weight", category_id: "fitness" },
  { pt: "Pular caixa", en: "Box jump", category_id: "fitness" },
  { pt: "Esteira", en: "Treadmill", category_id: "fitness" },
  { pt: "Meu barbeiro", en: "My barber", category_id: "vocab" },
  { pt: "Recomendou / Recomendar", en: "Recommended / To recommend", category_id: "verbs" },
  { pt: "Antes de ontem", en: "Day before yesterday", category_id: "time" },
  { pt: "Depois de amanhã", en: "Day after tomorrow", category_id: "time" },
  { pt: "Da manhã", en: "In the morning", category_id: "time" },
  { pt: "Da tarde", en: "In the afternoon", category_id: "time" },
  { pt: "Da noite", en: "In the evening / At night", category_id: "time" },
  { pt: "Duas", en: "Two (feminine, used for time/hours)", category_id: "vocab" },
  { pt: "Chateado", en: "Upset / Annoyed", category_id: "vocab" },
  { pt: "Com raiva", en: "Angry", category_id: "vocab" },
  { pt: "Ninguém falava", en: "Nobody was talking", category_id: "phrases" },
  { pt: "Talvez", en: "Maybe", category_id: "vocab" },
  { pt: "Eu prometo que", en: "I promise that", category_id: "phrases" },
  { pt: "Próxima vez", en: "Next time", category_id: "time" },
  { pt: "Complicada", en: "Complicated", category_id: "vocab" },
  { pt: "Prédio", en: "Building / Apartment building", category_id: "vocab" },
  { pt: "Rua", en: "Street", category_id: "vocab" },
  { pt: "Chuva", en: "Rain", category_id: "weather" },
  { pt: "Por causa de/da/do", en: "Because of…", category_id: "vocab" },
  { pt: "Escada", en: "Stairs", category_id: "vocab" },
  { pt: "Eu estou bem", en: "I'm fine / I'm good", category_id: "phrases" },
  { pt: "Eu cortei o cabelo", en: "I cut my hair", category_id: "phrases" },
  { pt: "Eu passei muita raiva", en: "I was very angry", category_id: "phrases" },
  { pt: "Eles não permitiram meu reembolso", en: "They didn't allow my refund", category_id: "phrases" },
  { pt: "Eu não pude devolver minha calça", en: "I couldn't return my pants", category_id: "phrases" },
  { pt: "Eu disse ao meu banco e eles me ajudaram", en: "I told my bank and they helped me", category_id: "phrases" },
  { pt: "Eles removeram o pagamento", en: "They removed the payment", category_id: "phrases" },
  { pt: "Eu só como batatas fritas quando eu treino", en: "I only eat fries when I work out", category_id: "phrases" },
  { pt: "Estar (eu estava)", en: "To be — I was (past)", category_id: "verbs" },
  { pt: "Estar (eu estou)", en: "To be — I am (present)", category_id: "verbs" },
  { pt: "Estar (eu vou estar / estarei)", en: "To be — I will be (future)", category_id: "verbs" },
  { pt: "Esperar (eu esperei)", en: "To wait/hope — I waited (past)", category_id: "verbs" },
  { pt: "Esperar (eu espero)", en: "To wait/hope — I wait (present)", category_id: "verbs" },
  { pt: "Esperar (eu vou esperar / esperarei)", en: "To wait/hope — I will wait (future)", category_id: "verbs" },
  { pt: "Buscar (eu busquei)", en: "To search/fetch — I searched (past)", category_id: "verbs" },
  { pt: "Buscar (eu busco)", en: "To search/fetch — I search (present)", category_id: "verbs" },
  { pt: "Buscar (eu vou buscar / buscarei)", en: "To search/fetch — I will search (future)", category_id: "verbs" },
  { pt: "Tomar (eu tomei)", en: "To take/drink — I took (past)", category_id: "verbs" },
  { pt: "Tomar (eu tomo)", en: "To take/drink — I take (present)", category_id: "verbs" },
  { pt: "Tomar (eu vou tomar / tomarei)", en: "To take/drink — I will take (future)", category_id: "verbs" },
  { pt: "Doze", en: "Twelve (12)", category_id: "vocab" },
  { pt: "Eu tenho", en: "I have", category_id: "verbs" },
  { pt: "Tive", en: "I had (past)", category_id: "verbs" },
  { pt: "Você tá perdendo", en: "You're missing out", category_id: "phrases" },
  { pt: "Que horas?", en: "What time?", category_id: "time" },
  { pt: "Próximo", en: "Next", category_id: "time" },
  { pt: "Depois", en: "After", category_id: "time" },
  { pt: "Perto", en: "Close / Nearby", category_id: "vocab" },
  { pt: "Foi", en: "It was / He/She went", category_id: "verbs" },
  { pt: "Eu fui", en: "I was / I went", category_id: "verbs" },
  { pt: "Você foi", en: "You were / You went", category_id: "verbs" },
  { pt: "Dormi", en: "I slept", category_id: "verbs" },
  { pt: "Comi", en: "I ate", category_id: "verbs" },
  { pt: "Corri", en: "I ran", category_id: "verbs" },
  { pt: "Quilômetros", en: "Kilometers", category_id: "vocab" },
  { pt: "Edifício", en: "Building / Edifice", category_id: "vocab" },
  { pt: "Manhã", en: "Morning", category_id: "time" },
  { pt: "Amanhã", en: "Tomorrow", category_id: "time" },
  { pt: "Sextar / Sextou", en: "To celebrate Friday / It's Friday!", category_id: "daily" },
  { pt: "Empresa", en: "Company", category_id: "vocab" },
  { pt: "Ir (eu vou)", en: "To go — I go", category_id: "ir-conj" },
  { pt: "Ir (você vai)", en: "To go — You go", category_id: "ir-conj" },
  { pt: "Ir (ele/ela vai)", en: "To go — He/She goes", category_id: "ir-conj" },
  { pt: "Fazer (eu fiz)", en: "To do/make — I did (past)", category_id: "verbs" },
  { pt: "Fazer (eu estou fazendo)", en: "To do/make — I'm doing (present)", category_id: "verbs" },
  { pt: "Fazer (eu vou fazer)", en: "To do/make — I will do (future)", category_id: "verbs" },
  { pt: "Fazer (você fez)", en: "To do/make — You did (past)", category_id: "verbs" },
  { pt: "Fazer (você está fazendo)", en: "To do/make — You're doing (present)", category_id: "verbs" },
  { pt: "Trabalhar (eu trabalhei)", en: "To work — I worked (past)", category_id: "verbs" },
  { pt: "Trabalhar (eu trabalho)", en: "To work — I work (present)", category_id: "verbs" },
  { pt: "Trabalhar (eu vou trabalhar)", en: "To work — I will work (future)", category_id: "verbs" },
  { pt: "Hoje eu vou fazer meu CPF no Banco do Brasil", en: "Today I'll get my CPF at Banco do Brasil", category_id: "phrases" },
  { pt: "Hoje eu vou cortar o meu cabelo", en: "Today I'm going to cut my hair", category_id: "phrases" },
  { pt: "Eu não comprei ainda", en: "I haven't bought it yet", category_id: "phrases" },
  { pt: "Eu não agendei ainda", en: "I haven't scheduled it yet", category_id: "phrases" },
  { pt: "Não tenho certeza", en: "I'm not sure", category_id: "phrases" },
  { pt: "Dessa vez sério", en: "This time for real", category_id: "phrases" },
  { pt: "No final de semana, o que você vai fazer?", en: "On the weekend, what are you going to do?", category_id: "phrases" },
  { pt: "Não tenho planos ainda", en: "I don't have plans yet", category_id: "phrases" },
  { pt: "Ontem eu fui preguiçoso", en: "Yesterday I was lazy", category_id: "phrases" },
  { pt: "Como está o trabalho?", en: "How is work?", category_id: "phrases" },
  { pt: "Com o que você trabalha?", en: "What do you work with?", category_id: "phrases" },
  { pt: "Você já ouviu falar", en: "Have you already heard of", category_id: "phrases" },
  { pt: "Você é o desenvolvedor do aplicativo?", en: "Are you the app developer?", category_id: "phrases" },
  { pt: "Eu criei o aplicativo", en: "I created the app", category_id: "phrases" },
  { pt: "Desenvolvedor de software", en: "Software developer", category_id: "vocab" },
  { pt: "Sócio", en: "Partner / Associate", category_id: "vocab" },
  { pt: "Meio-tempo / Tempo-parcial", en: "Part-time", category_id: "vocab" },
  { pt: "Conselheiro / Assessor", en: "Advisor / Counselor", category_id: "vocab" },
  { pt: "Segunda-feira", en: "Monday", category_id: "time" },
  { pt: "Terça-feira", en: "Tuesday", category_id: "time" },
  { pt: "Quarta-feira", en: "Wednesday", category_id: "time" },
  { pt: "Quinta-feira", en: "Thursday", category_id: "time" },
  { pt: "Sexta-feira", en: "Friday", category_id: "time" },
  { pt: "Sábado", en: "Saturday", category_id: "time" },
  { pt: "Domingo", en: "Sunday", category_id: "time" },
  { pt: "Essa / Esse", en: "This (feminine / masculine)", category_id: "vocab" },
  { pt: "A próxima / O próximo", en: "The next (fem / masc)", category_id: "vocab" },
  { pt: "Passada / Passado", en: "Last / Past (fem / masc)", category_id: "vocab" },
  { pt: "Agora", en: "Now", category_id: "vocab" },
  { pt: "Pesquisando / Buscando", en: "Searching", category_id: "vocab" },
  { pt: "Escritório", en: "Office", category_id: "vocab" },
  { pt: "Morar", en: "To live (reside)", category_id: "vocab" },
  { pt: "Então", en: "So / Then", category_id: "vocab" },
  { pt: "Aluguel", en: "Rent", category_id: "vocab" },
  { pt: "Comprar", en: "To buy", category_id: "vocab" },
  { pt: "Encontrar", en: "To find", category_id: "vocab" },
  { pt: "Provavelmente", en: "Probably", category_id: "vocab" },
  { pt: "Normalmente", en: "Normally", category_id: "vocab" },
  { pt: "Igualmente", en: "Equally / Likewise", category_id: "vocab" },
  { pt: "Pai", en: "Dad / Father", category_id: "daily" },
  { pt: "Avô", en: "Grandpa", category_id: "daily" },
  { pt: "Avó", en: "Grandma", category_id: "daily" },
  { pt: "Meio-dia", en: "Noon / Midday", category_id: "time" },
  { pt: "Meia-noite", en: "Midnight", category_id: "time" },
  { pt: "Hambúrguer", en: "Hamburger", category_id: "daily" },
  { pt: "Chá quente", en: "Hot tea", category_id: "daily" },
  { pt: "Eu necessito / Eu preciso", en: "I need", category_id: "vocab" },
  { pt: "Só isso", en: "That's it", category_id: "vocab" },
  { pt: "Mais do mesmo", en: "More of the same", category_id: "vocab" },
  { pt: "Gostoso", en: "Delicious / Hot (attractive)", category_id: "vocab" },
  { pt: "Buscando personal trainer para academia", en: "Looking for a personal trainer for the gym", category_id: "phrases" },
  { pt: "Eu preciso ficar forte", en: "I need to get strong", category_id: "phrases" },
  { pt: "Eu vou ao mercado", en: "I will go to the market", category_id: "phrases" },
  { pt: "No próximo final de semana eu vou…", en: "Next weekend I'm going to…", category_id: "phrases" },
  { pt: "Eu estou tendo uma classe boa", en: "I'm having a good class", category_id: "phrases" },
  { pt: "Estou buscando um escritório para trabalhar", en: "I'm looking for an office to work in", category_id: "phrases" },
  { pt: "Calor", en: "Heat / Hot (weather)", category_id: "weather" },
  { pt: "Frio", en: "Cold", category_id: "weather" },
  { pt: "Ai que calor", en: "Oh it's so hot", category_id: "weather" },
  { pt: "Muito calor", en: "Very hot", category_id: "weather" },
  { pt: "Estou com calor", en: "I'm hot (feeling)", category_id: "weather" },
  { pt: "Hoje está muito calor", en: "It's very hot today", category_id: "weather" },
  { pt: "Quente", en: "Hot (temperature)", category_id: "weather" },
  { pt: "Gelado", en: "Freezing / Ice cold", category_id: "weather" },
  { pt: "Gelo", en: "Ice", category_id: "weather" },
  { pt: "Fora", en: "Outside", category_id: "vocab" },
  { pt: "Lá fora", en: "Out there / Outside", category_id: "vocab" },
  { pt: "Bebê, está frio lá fora", en: "Baby, it's cold outside", category_id: "phrases" },
  { pt: "Dentro", en: "Inside", category_id: "vocab" },
  { pt: "Demorar", en: "To take long / To delay", category_id: "verbs" },
  { pt: "Atrasar / Atrasado(a)", en: "To be late / Late", category_id: "verbs" },
  { pt: "Acordar", en: "To wake up", category_id: "daily" },
  { pt: "Dormir", en: "To sleep", category_id: "daily" },
  { pt: "Comer", en: "To eat", category_id: "daily" },
  { pt: "Como foi o seu fim de semana?", en: "How was your weekend?", category_id: "phrases" },
  { pt: "Descansar / Eu descansei", en: "To rest / I rested", category_id: "verbs" },
  { pt: "Temos", en: "We have", category_id: "verbs" },
  { pt: "Começar / Terminar", en: "To start / To finish", category_id: "verbs" },
  { pt: "Gastar energia", en: "To spend energy", category_id: "vocab" },
  { pt: "Celebrou", en: "Celebrated", category_id: "verbs" },
  { pt: "Combina com sua personalidade", en: "It matches your personality", category_id: "phrases" },
  { pt: "Por que eu gosto de carnaval?", en: "Why do I like carnaval?", category_id: "phrases" },
  { pt: "Gosto", en: "I like / Taste", category_id: "vocab" },
  { pt: "Divertida", en: "Fun", category_id: "vocab" },
  { pt: "Colorida", en: "Colorful", category_id: "vocab" },
  { pt: "Vibrante", en: "Vibrant", category_id: "vocab" },
  { pt: "Elogio", en: "Compliment", category_id: "vocab" },
  { pt: "Novo(a) / Velho(a)", en: "New / Old", category_id: "vocab" },
  { pt: "Mais nova / Mais velha", en: "Younger / Older", category_id: "vocab" },
  { pt: "Dançarina / Dançarino", en: "Dancer (fem / masc)", category_id: "vocab" },
  { pt: "Bloco de carnaval", en: "Carnival street party / block", category_id: "vocab" },
  { pt: "Desfile", en: "Parade", category_id: "vocab" },
  { pt: "Eu ia ir", en: "I was going to go", category_id: "phrases" },
  { pt: "De novo", en: "Again", category_id: "vocab" },
  { pt: "2 vezes", en: "2 times", category_id: "vocab" },
  { pt: "Foi bom o carnaval ano passado aí?", en: "Was carnaval good last year there?", category_id: "phrases" },
  { pt: "Ano retrasado", en: "Two years ago", category_id: "time" },
  { pt: "Deveria", en: "Should", category_id: "verbs" },
  { pt: "Sair", en: "To get out / To leave", category_id: "verbs" },
  { pt: "Conhecer", en: "To know / To meet", category_id: "verbs" },
  { pt: "Algumas pessoas", en: "Some people", category_id: "vocab" },
  { pt: "Aí / Ali / Daí", en: "There / There (farther) / From there", category_id: "vocab" },
  { pt: "Aqui / Cá / Para cá", en: "Here / Here / Over here", category_id: "vocab" },
  { pt: "Mas você foi para o do Rio ano retrasado", en: "But you went to the one in Rio two years ago", category_id: "phrases" },
  { pt: "De abrir os olhos", en: "Eye-opening", category_id: "vocab" },
  { pt: "Foi uma nova experiência", en: "It was a new experience", category_id: "phrases" },
  { pt: "Mudou minha mente", en: "Changed my mind", category_id: "phrases" },
  { pt: "Explodiu minha mente", en: "Blew my mind", category_id: "phrases" },
  { pt: "Foi uma experiência de abrir os olhos", en: "It was an eye-opening experience", category_id: "phrases" },
  { pt: "Viajar", en: "To travel", category_id: "verbs" },
  { pt: "Para", en: "To / For", category_id: "vocab" },
  { pt: "No meio de março", en: "In the middle of March", category_id: "time" },
  { pt: "Mais cedo", en: "Earlier", category_id: "time" },
  { pt: "Mais tarde", en: "Later", category_id: "time" },
  { pt: "Desculpa", en: "Sorry / Excuse me", category_id: "vocab" },
  { pt: "Águas de janeiro", en: "January waters (famous Brazilian song)", category_id: "vocab" },
  { pt: "Eu tenho que trabalhar muito ainda hoje", en: "I still have to work a lot today", category_id: "phrases" },
  { pt: "Ainda", en: "Still / Yet", category_id: "vocab" },
  { pt: "Cardio", en: "Cardio", category_id: "fitness" },
  { pt: "Ir (eu ia)", en: "To go — I used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (você ia)", en: "To go — You used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (ele/ela ia)", en: "To go — He/She used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (nós íamos)", en: "To go — We used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (vocês iam)", en: "To go — You (pl.) used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (eles/elas iam)", en: "To go — They used to go (Imperfeito)", category_id: "ir-conj" },
  { pt: "Ir (eu fui)", en: "To go — I went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (você foi)", en: "To go — You went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (ele/ela foi)", en: "To go — He/She went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (nós fomos)", en: "To go — We went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (vocês foram)", en: "To go — You (pl.) went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (eles/elas foram)", en: "To go — They went (Perfeito)", category_id: "ir-conj" },
  { pt: "Ir (nós vamos)", en: "To go — We go (Presente)", category_id: "ir-conj" },
  { pt: "Ir (vocês vão)", en: "To go — You (pl.) go (Presente)", category_id: "ir-conj" },
  { pt: "Ir (eles/elas vão)", en: "To go — They go (Presente)", category_id: "ir-conj" },
  { pt: "Ir (eu irei)", en: "To go — I will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (você irá)", en: "To go — You will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (ele/ela irá)", en: "To go — He/She will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (nós iremos)", en: "To go — We will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (vocês irão)", en: "To go — You (pl.) will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (eles/elas irão)", en: "To go — They will go (Futuro)", category_id: "ir-conj" },
  { pt: "Ir (eu iria)", en: "To go — I would go (Conditional)", category_id: "ir-conj" },
  { pt: "Ir (você iria)", en: "To go — You would go (Conditional)", category_id: "ir-conj" },
  { pt: "Ir (ele/ela iria)", en: "To go — He/She would go (Conditional)", category_id: "ir-conj" },
  { pt: "Ir (nós iríamos)", en: "To go — We would go (Conditional)", category_id: "ir-conj" },
  { pt: "Ir (vocês iriam)", en: "To go — You (pl.) would go (Conditional)", category_id: "ir-conj" },
  { pt: "Ir (eles/elas iriam)", en: "To go — They would go (Conditional)", category_id: "ir-conj" },
  { pt: "Estar (eu estava)", en: "To be — I was (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (você estava)", en: "To be — You were (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (ele/ela estava)", en: "To be — He/She was (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (nós estávamos)", en: "To be — We were (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (vocês estavam)", en: "To be — You (pl.) were (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (eles/elas estavam)", en: "To be — They were (Imperfeito)", category_id: "verbs" },
  { pt: "Estar (nós estamos)", en: "To be — We are (Presente)", category_id: "verbs" },
  { pt: "Estar (vocês estão)", en: "To be — You (pl.) are (Presente)", category_id: "verbs" },
  { pt: "Estar (eles/elas estão)", en: "To be — They are (Presente)", category_id: "verbs" },
  { pt: "Estar (eu vou estar)", en: "To be — I will be (Futuro)", category_id: "verbs" },
  { pt: "Estar (você vai estar)", en: "To be — You will be (Futuro)", category_id: "verbs" },
  { pt: "Estar (ele/ela vai estar)", en: "To be — He/She will be (Futuro)", category_id: "verbs" },
  { pt: "Estar (nós vamos estar)", en: "To be — We will be (Futuro)", category_id: "verbs" },
  { pt: "Estar (vocês vão estar)", en: "To be — You (pl.) will be (Futuro)", category_id: "verbs" },
  { pt: "Estar (eles/elas vão estar)", en: "To be — They will be (Futuro)", category_id: "verbs" },
  { pt: "Feliz / Alegre", en: "Happy / Cheerful", category_id: "vocab" },
  { pt: "Triste", en: "Sad", category_id: "vocab" },
  { pt: "Educado(a)", en: "Polite", category_id: "vocab" },
  { pt: "Mal-educado(a)", en: "Rude / Impolite", category_id: "vocab" },
  { pt: "Inteligente", en: "Intelligent / Smart", category_id: "vocab" },
  { pt: "Burro(a)", en: "Dumb / Stupid", category_id: "vocab" },
  { pt: "Calmo(a)", en: "Calm", category_id: "vocab" },
  { pt: "Nervoso(a)", en: "Nervous / Anxious", category_id: "vocab" },
  { pt: "Corajoso(a)", en: "Brave", category_id: "vocab" },
  { pt: "Medroso(a)", en: "Cowardly / Fearful", category_id: "vocab" },
  { pt: "Honesto(a)", en: "Honest", category_id: "vocab" },
  { pt: "Mentiroso(a)", en: "Liar / Dishonest", category_id: "vocab" },
  { pt: "Bonito(a)", en: "Handsome / Beautiful", category_id: "vocab" },
  { pt: "Lindo(a)", en: "Pretty", category_id: "vocab" },
  { pt: "Feio(a)", en: "Ugly", category_id: "vocab" },
  { pt: "Alto(a)", en: "Tall", category_id: "vocab" },
  { pt: "Baixo(a)", en: "Short", category_id: "vocab" },
  { pt: "Magro(a)", en: "Thin / Slim", category_id: "vocab" },
  { pt: "Gordo(a)", en: "Fat / Overweight", category_id: "vocab" },
  { pt: "Divertido(a)", en: "Fun", category_id: "vocab" },
  { pt: "Legal", en: "Cool", category_id: "vocab" },
  { pt: "Chato(a)", en: "Boring", category_id: "vocab" },
  { pt: "Simpático(a)", en: "Nice", category_id: "vocab" },
  { pt: "Grosso(a)", en: "Rude", category_id: "vocab" },
  { pt: "Ignorante", en: "Ignorant", category_id: "vocab" },
  { pt: "Fofo(a)", en: "Cute", category_id: "vocab" },
  { pt: "Irritante", en: "Irritating", category_id: "vocab" },
  { pt: "Imbécil", en: "Imbecile", category_id: "vocab" },
  { pt: "Maravilhoso(a)", en: "Wonderful", category_id: "vocab" },
  { pt: "Interessante", en: "Interesting", category_id: "vocab" },
  { pt: "Forte", en: "Strong", category_id: "vocab" },
  { pt: "Fraco(a)", en: "Weak", category_id: "vocab" },
  { pt: "Animado(a)", en: "Excited", category_id: "vocab" },
  { pt: "Desanimado(a)", en: "Not excited", category_id: "vocab" },
  { pt: "Organizado(a)", en: "Organized", category_id: "vocab" },
  { pt: "Desorganizado(a)", en: "Disorganized", category_id: "vocab" },
  { pt: "Preguiçoso(a)", en: "Lazy", category_id: "vocab" },
  { pt: "Paciente", en: "Patient", category_id: "vocab" },
  { pt: "Tímido(a)", en: "Shy", category_id: "vocab" },
  { pt: "Contente", en: "Content / Happy", category_id: "vocab" },
  { pt: "Cansado(a)", en: "Tired", category_id: "vocab" },
  { pt: "Entediado(a)", en: "Bored", category_id: "vocab" },
  { pt: "Preocupado(a)", en: "Worried", category_id: "vocab" },
  { pt: "Sala de aula", en: "Classroom", category_id: "vocab" },
  { pt: "Casa", en: "House / Home", category_id: "vocab" },
  { pt: "Supermercado", en: "Supermarket", category_id: "vocab" },
  { pt: "Juiz de Fora", en: "Juiz de Fora (city in Minas Gerais)", category_id: "vocab" },
  { pt: "Brasil", en: "Brazil", category_id: "vocab" },
  { pt: "Minas Gerais", en: "Minas Gerais (state in Brazil)", category_id: "vocab" },
  { pt: "Cinema", en: "Movie theater / Cinema", category_id: "vocab" },
  { pt: "Salão de beleza", en: "Beauty salon", category_id: "vocab" },
  { pt: "Fome", en: "Hunger / Hungry", category_id: "vocab" },
  { pt: "Sede", en: "Thirst / Thirsty", category_id: "vocab" },
  { pt: "Raiva", en: "Anger / Rage", category_id: "vocab" },
  { pt: "Medo", en: "Fear", category_id: "vocab" },
  { pt: "Dor de cabeça", en: "Headache", category_id: "vocab" },
  { pt: "Enjoo", en: "Nausea", category_id: "vocab" },
  { pt: "O braço quebrado", en: "The broken arm", category_id: "vocab" },
  { pt: "Eu ia ao trabalho de ônibus.", en: "I used to go to work by bus.", category_id: "ir-phrases" },
  { pt: "Você ia à escola a pé?", en: "Did you used to go to school on foot?", category_id: "ir-phrases" },
  { pt: "Ele ia ao mercado todo dia.", en: "He used to go to the market every day.", category_id: "ir-phrases" },
  { pt: "Ela ia à praia sempre.", en: "She always used to go to the beach.", category_id: "ir-phrases" },
  { pt: "Nós íamos estudar juntos.", en: "We used to study together.", category_id: "ir-phrases" },
  { pt: "Vocês iam ao curso à noite?", en: "Did you (pl.) used to go to the course at night?", category_id: "ir-phrases" },
  { pt: "Eles iam ao cinema com frequência.", en: "They used to go to the movies often.", category_id: "ir-phrases" },
  { pt: "Elas iam à academia antes.", en: "They (f.) used to go to the gym before.", category_id: "ir-phrases" },
  { pt: "Eu fui ao Brasil no ano passado.", en: "I went to Brazil last year.", category_id: "ir-phrases" },
  { pt: "Você foi ao evento ontem?", en: "Did you go to the event yesterday?", category_id: "ir-phrases" },
  { pt: "Ele foi ao trabalho cedo.", en: "He went to work early.", category_id: "ir-phrases" },
  { pt: "Ela foi ao médico ontem.", en: "She went to the doctor yesterday.", category_id: "ir-phrases" },
  { pt: "Nós fomos à praia ontem.", en: "We went to the beach yesterday.", category_id: "ir-phrases" },
  { pt: "Vocês foram ao show?", en: "Did you (pl.) go to the show?", category_id: "ir-phrases" },
  { pt: "Eles foram ao hotel.", en: "They went to the hotel.", category_id: "ir-phrases" },
  { pt: "Elas foram ao aeroporto.", en: "They (f.) went to the airport.", category_id: "ir-phrases" },
  { pt: "Eu vou ao trabalho todos os dias.", en: "I go to work every day.", category_id: "ir-phrases" },
  { pt: "Você vai à aula agora?", en: "Are you going to class now?", category_id: "ir-phrases" },
  { pt: "Ele vai ao mercado.", en: "He goes to the market.", category_id: "ir-phrases" },
  { pt: "Ela vai à praia hoje.", en: "She's going to the beach today.", category_id: "ir-phrases" },
  { pt: "Nós vamos viajar amanhã.", en: "We're going to travel tomorrow.", category_id: "ir-phrases" },
  { pt: "Vocês vão ao restaurante?", en: "Are you (pl.) going to the restaurant?", category_id: "ir-phrases" },
  { pt: "Eles vão ao cinema.", en: "They're going to the movies.", category_id: "ir-phrases" },
  { pt: "Elas vão à academia.", en: "They (f.) are going to the gym.", category_id: "ir-phrases" },
  { pt: "Eu irei ao Brasil em julho.", en: "I will go to Brazil in July.", category_id: "ir-phrases" },
  { pt: "Você irá à aula amanhã?", en: "Will you go to class tomorrow?", category_id: "ir-phrases" },
  { pt: "Ele irá ao trabalho mais tarde.", en: "He will go to work later.", category_id: "ir-phrases" },
  { pt: "Ela irá ao mercado depois.", en: "She will go to the market later.", category_id: "ir-phrases" },
  { pt: "Nós iremos viajar nas férias.", en: "We will travel on vacation.", category_id: "ir-phrases" },
  { pt: "Vocês irão ao evento?", en: "Will you (pl.) go to the event?", category_id: "ir-phrases" },
  { pt: "Eles irão ao restaurante.", en: "They will go to the restaurant.", category_id: "ir-phrases" },
  { pt: "Elas irão ao show.", en: "They (f.) will go to the show.", category_id: "ir-phrases" },
  { pt: "Eu iria ao Brasil se tivesse tempo.", en: "I would go to Brazil if I had time.", category_id: "ir-phrases" },
  { pt: "Você iria comigo?", en: "Would you go with me?", category_id: "ir-phrases" },
  { pt: "Ele iria ao evento, mas trabalhou.", en: "He would go to the event, but he worked.", category_id: "ir-phrases" },
  { pt: "Ela iria à festa, porém ficou doente.", en: "She would go to the party, but she got sick.", category_id: "ir-phrases" },
  { pt: "Nós iríamos viajar este ano.", en: "We would travel this year.", category_id: "ir-phrases" },
  { pt: "Vocês iriam ao curso se fosse online?", en: "Would you (pl.) go to the course if it were online?", category_id: "ir-phrases" },
  { pt: "Eles iriam ao cinema ontem.", en: "They would go to the movies yesterday.", category_id: "ir-phrases" },
  { pt: "Elas iriam à praia, mas choveu.", en: "They (f.) would go to the beach, but it rained.", category_id: "ir-phrases" },
  { pt: "Parabéns pra você", en: "Congrats to you", category_id: "bday" },
  { pt: "Nesta data querida", en: "On this dear date", category_id: "bday" },
  { pt: "Muitas felicidades", en: "Much happiness", category_id: "bday" },
  { pt: "Muitos anos de vida", en: "Many years of life", category_id: "bday" },
  { pt: "Hoje é dia de festa", en: "Today is day of party", category_id: "bday" },
  { pt: "Não é dia de tristeza", en: "It's not a day for sadness", category_id: "bday" },
  { pt: "Vai buscar teu noivo", en: "Go get your fiancé", category_id: "bday" },
  { pt: "Pra casar com certeza", en: "To get married for sure", category_id: "bday" },
  { pt: "É pique, é pique", en: "It's peak, it's peak", category_id: "bday" },
  { pt: "É hora, é hora", en: "It's time, it's time", category_id: "bday" },
  { pt: "Rá-tim-bum", en: "Hip hip hooray!", category_id: "bday" },
  { pt: "Encontrei", en: "I found", category_id: "quase" },
  { pt: "Lugar", en: "Place", category_id: "quase" },
  { pt: "Perto de mim", en: "Near me / Close to me", category_id: "quase" },
  { pt: "Se chama", en: "Is called / His/Her name is", category_id: "quase" },
  { pt: "Pode ser / Talvez seja", en: "Could be / Maybe it is", category_id: "quase" },
  { pt: "Bem devagar", en: "Very slowly", category_id: "quase" },
  { pt: "Devagar", en: "Slow / Slowly", category_id: "quase" },
  { pt: "Rápido", en: "Fast / Quickly", category_id: "quase" },
  { pt: "Prova", en: "Test / Exam / Proof", category_id: "quase" },
  { pt: "Faz sentido", en: "It makes sense", category_id: "quase" },
  { pt: "Chato", en: "Boring / Annoying", category_id: "quase" },
  { pt: "Entediante", en: "Boring / Tedious", category_id: "quase" },
  { pt: "Barato", en: "Cheap", category_id: "quase" },
  { pt: "Caro", en: "Expensive", category_id: "quase" },
  { pt: "Melancia", en: "Watermelon", category_id: "quase" },
  { pt: "Eu era / Você era / Ele era / Ela era", en: "I was / You were / He was / She was (Imperfeito)", category_id: "quase" },
  { pt: "Nós éramos / Vocês eram / Eles eram / Elas eram", en: "We were / You (pl.) were / They were (Imperfeito)", category_id: "quase" },
  { pt: "Modelos do Japão", en: "Models from Japan", category_id: "quase" },
  { pt: "Hoje", en: "Today", category_id: "quase" },
  { pt: "Tomava", en: "Used to drink / Used to take (Imperfeito)", category_id: "quase" },
  { pt: "Terapeuta", en: "Therapist", category_id: "quase" },
  { pt: "Estudando", en: "Studying", category_id: "quase" },
  { pt: "Doutorado", en: "Doctorate / PhD", category_id: "quase" },
  { pt: "Muito bem", en: "Very well", category_id: "aula-mar27" },
  { pt: "Me mude", en: "Move me / Change me", category_id: "aula-mar27" },
  { pt: "Cidade", en: "City", category_id: "aula-mar27" },
  { pt: "Estado", en: "State", category_id: "aula-mar27" },
  { pt: "Aprovar — aprovei", en: "To approve — I approved", category_id: "aula-mar27" },
  { pt: "Módulo", en: "Module", category_id: "aula-mar27" },
  { pt: "Por", en: "Per / For", category_id: "aula-mar27" },
  { pt: "Coisa", en: "Thing", category_id: "aula-mar27" },
  { pt: "Esquecer", en: "To forget", category_id: "aula-mar27" },
  { pt: "Lembrar", en: "To remember", category_id: "aula-mar27" },
  { pt: "Maravilhoso", en: "Wonderful", category_id: "aula-mar27" },
  { pt: "Os livros estão bons", en: "The books are good", category_id: "aula-mar27" },
  { pt: "Dizer — dizem", en: "To say — they say", category_id: "aula-mar27" },
  { pt: "Ler", en: "To read", category_id: "aula-mar27" },
  { pt: "Presente", en: "Present / Gift", category_id: "aula-mar27" },
  { pt: "Isso aconteceu na festa de natal da minha família", en: "This happened at my family's Christmas party", category_id: "aula-mar27" },
  { pt: "É maravilhoso que você lembra toda a informação e eu esqueceria", en: "It's wonderful that you remember all the information and I would forget", category_id: "aula-mar27" },
  { pt: "Eu não lembro de nada e eu esqueço tudo", en: "I don't remember anything and I forget everything", category_id: "aula-mar27" },
  { pt: "Ler (eu leio)", en: "To read — I read (Presente)", category_id: "ler-conj" },
  { pt: "Ler (você lê)", en: "To read — You read (Presente)", category_id: "ler-conj" },
  { pt: "Ler (ele/ela lê)", en: "To read — He/She reads (Presente)", category_id: "ler-conj" },
  { pt: "Ler (nós lemos)", en: "To read — We read (Presente)", category_id: "ler-conj" },
  { pt: "Ler (vocês leem)", en: "To read — You (pl.) read (Presente)", category_id: "ler-conj" },
  { pt: "Ler (eles/elas leem)", en: "To read — They read (Presente)", category_id: "ler-conj" },
  { pt: "Ler (eu lia)", en: "To read — I used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (você lia)", en: "To read — You used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (ele/ela lia)", en: "To read — He/She used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (nós líamos)", en: "To read — We used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (vocês liam)", en: "To read — You (pl.) used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (eles/elas liam)", en: "To read — They used to read (Imperfeito)", category_id: "ler-conj" },
  { pt: "Ler (eu li)", en: "To read — I read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (você leu)", en: "To read — You read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (ele/ela leu)", en: "To read — He/She read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (nós lemos)", en: "To read — We read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (vocês leram)", en: "To read — You (pl.) read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (eles/elas leram)", en: "To read — They read (Perfeito)", category_id: "ler-conj" },
  { pt: "Ler (eu lerei)", en: "To read — I will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (você lerá)", en: "To read — You will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (ele/ela lerá)", en: "To read — He/She will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (nós leremos)", en: "To read — We will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (vocês lerão)", en: "To read — You (pl.) will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (eles/elas lerão)", en: "To read — They will read (Futuro)", category_id: "ler-conj" },
  { pt: "Ler (eu leria)", en: "To read — I would read (Conditional)", category_id: "ler-conj" },
  { pt: "Ler (você leria)", en: "To read — You would read (Conditional)", category_id: "ler-conj" },
  { pt: "Ler (ele/ela leria)", en: "To read — He/She would read (Conditional)", category_id: "ler-conj" },
  { pt: "Ler (nós leríamos)", en: "To read — We would read (Conditional)", category_id: "ler-conj" },
  { pt: "Ler (vocês leriam)", en: "To read — You (pl.) would read (Conditional)", category_id: "ler-conj" },
  { pt: "Ler (eles/elas leriam)", en: "To read — They would read (Conditional)", category_id: "ler-conj" },
  { pt: "Esquecer (eu esqueço)", en: "To forget — I forget (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (você esquece)", en: "To forget — You forget (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (ele/ela esquece)", en: "To forget — He/She forgets (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (nós esquecemos)", en: "To forget — We forget (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (vocês esquecem)", en: "To forget — You (pl.) forget (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eles/elas esquecem)", en: "To forget — They forget (Presente)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eu esquecia)", en: "To forget — I used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (você esquecia)", en: "To forget — You used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (ele/ela esquecia)", en: "To forget — He/She used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (nós esquecíamos)", en: "To forget — We used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (vocês esqueciam)", en: "To forget — You (pl.) used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eles/elas esqueciam)", en: "To forget — They used to forget (Imperfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eu esqueci)", en: "To forget — I forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (você esqueceu)", en: "To forget — You forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (ele/ela esqueceu)", en: "To forget — He/She forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (nós esquecemos)", en: "To forget — We forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (vocês esqueceram)", en: "To forget — You (pl.) forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eles/elas esqueceram)", en: "To forget — They forgot (Perfeito)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eu esquecerei)", en: "To forget — I will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (você esquecerá)", en: "To forget — You will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (ele/ela esquecerá)", en: "To forget — He/She will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (nós esqueceremos)", en: "To forget — We will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (vocês esquecerão)", en: "To forget — You (pl.) will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eles/elas esquecerão)", en: "To forget — They will forget (Futuro)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eu esqueceria)", en: "To forget — I would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Esquecer (você esqueceria)", en: "To forget — You would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Esquecer (ele/ela esqueceria)", en: "To forget — He/She would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Esquecer (nós esqueceríamos)", en: "To forget — We would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Esquecer (vocês esqueceriam)", en: "To forget — You (pl.) would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Esquecer (eles/elas esqueceriam)", en: "To forget — They would forget (Conditional)", category_id: "esquecer-conj" },
  { pt: "Lembrar (eu lembro)", en: "To remember — I remember (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (você lembra)", en: "To remember — You remember (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (ele/ela lembra)", en: "To remember — He/She remembers (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (nós lembramos)", en: "To remember — We remember (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (vocês lembram)", en: "To remember — You (pl.) remember (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eles/elas lembram)", en: "To remember — They remember (Presente)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eu lembrava)", en: "To remember — I used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (você lembrava)", en: "To remember — You used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (ele/ela lembrava)", en: "To remember — He/She used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (nós lembrávamos)", en: "To remember — We used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (vocês lembravam)", en: "To remember — You (pl.) used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eles/elas lembravam)", en: "To remember — They used to remember (Imperfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eu lembrei)", en: "To remember — I remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (você lembrou)", en: "To remember — You remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (ele/ela lembrou)", en: "To remember — He/She remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (nós lembramos)", en: "To remember — We remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (vocês lembraram)", en: "To remember — You (pl.) remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eles/elas lembraram)", en: "To remember — They remembered (Perfeito)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eu lembrarei)", en: "To remember — I will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (você lembrará)", en: "To remember — You will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (ele/ela lembrará)", en: "To remember — He/She will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (nós lembraremos)", en: "To remember — We will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (vocês lembrarão)", en: "To remember — You (pl.) will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eles/elas lembrarão)", en: "To remember — They will remember (Futuro)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eu lembraria)", en: "To remember — I would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Lembrar (você lembraria)", en: "To remember — You would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Lembrar (ele/ela lembraria)", en: "To remember — He/She would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Lembrar (nós lembraríamos)", en: "To remember — We would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Lembrar (vocês lembrariam)", en: "To remember — You (pl.) would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Lembrar (eles/elas lembrariam)", en: "To remember — They would remember (Conditional)", category_id: "lembrar-conj" },
  { pt: "Dizer (eu digo)", en: "To say — I say (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (você diz)", en: "To say — You say (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (ele/ela diz)", en: "To say — He/She says (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (nós dizemos)", en: "To say — We say (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (vocês dizem)", en: "To say — You (pl.) say (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (eles/elas dizem)", en: "To say — They say (Presente)", category_id: "dizer-conj" },
  { pt: "Dizer (eu dizia)", en: "To say — I used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (você dizia)", en: "To say — You used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (ele/ela dizia)", en: "To say — He/She used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (nós dizíamos)", en: "To say — We used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (vocês diziam)", en: "To say — You (pl.) used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (eles/elas diziam)", en: "To say — They used to say (Imperfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (eu disse)", en: "To say — I said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (você disse)", en: "To say — You said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (ele/ela disse)", en: "To say — He/She said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (nós dissemos)", en: "To say — We said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (vocês disseram)", en: "To say — You (pl.) said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (eles/elas disseram)", en: "To say — They said (Perfeito)", category_id: "dizer-conj" },
  { pt: "Dizer (eu direi)", en: "To say — I will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (você dirá)", en: "To say — You will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (ele/ela dirá)", en: "To say — He/She will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (nós diremos)", en: "To say — We will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (vocês dirão)", en: "To say — You (pl.) will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (eles/elas dirão)", en: "To say — They will say (Futuro)", category_id: "dizer-conj" },
  { pt: "Dizer (eu diria)", en: "To say — I would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Dizer (você diria)", en: "To say — You would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Dizer (ele/ela diria)", en: "To say — He/She would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Dizer (nós diríamos)", en: "To say — We would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Dizer (vocês diriam)", en: "To say — You (pl.) would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Dizer (eles/elas diriam)", en: "To say — They would say (Conditional)", category_id: "dizer-conj" },
  { pt: "Opa", en: "Hey / What's up", category_id: "aula-mar30" },
  { pt: "Tudo bom", en: "All good / How's it going", category_id: "aula-mar30" },
  { pt: "Oi", en: "Hi", category_id: "aula-mar30" },
  { pt: "Do sábado pro domingo", en: "From Saturday to Sunday", category_id: "aula-mar30" },
  { pt: "Eu fui irritado", en: "I was irritated (went there irritated)", category_id: "aula-mar30" },
  { pt: "Eu estava irritado", en: "I was irritated (ongoing state)", category_id: "aula-mar30" },
  { pt: "Pouco", en: "A little / Few", category_id: "aula-mar30" },
  { pt: "Você viu o site que eu tive que mudar?", en: "Did you see the site that I had to change?", category_id: "aula-mar30" },
  { pt: "Enviar", en: "To send (letters / emails)", category_id: "aula-mar30" },
  { pt: "Mandar", en: "To send / To order", category_id: "aula-mar30" },
  { pt: "Mudar", en: "To change / To move", category_id: "aula-mar30" },
  { pt: "Me testa", en: "Test me", category_id: "aula-mar30" },
  { pt: "Provar", en: "To prove / To taste / To try on", category_id: "aula-mar30" },
  { pt: "Tentar", en: "To try", category_id: "aula-mar30" },
  { pt: "Eu gosto", en: "I like", category_id: "aula-mar30" },
  { pt: "Eu vou conseguir uma pra você", en: "I'm going to get one for you", category_id: "aula-mar30" },
  { pt: "Eu vou te dar uma", en: "I'm going to give you one", category_id: "aula-mar30" },
  { pt: "Te", en: "You (object pronoun)", category_id: "aula-mar30" },
  { pt: "Dar", en: "To give", category_id: "aula-mar30" },
  { pt: "Tudo", en: "Everything", category_id: "aula-mar30" },
  { pt: "Todo", en: "Full / Every / All", category_id: "aula-mar30" },
  { pt: "Tudo em todo lugar ao mesmo tempo", en: "Everything everywhere all at once", category_id: "aula-mar30" },
  { pt: "Chorar", en: "To cry", category_id: "aula-mar30" },
  { pt: "Ver", en: "To see", category_id: "aula-mar30" },
  { pt: "Vir", en: "To come", category_id: "aula-mar30" },
  { pt: "Eu sempre choro quando eu voo e eu vejo um filme", en: "I always cry when I fly and I watch a movie", category_id: "aula-mar30" },
  { pt: "Você me dá dever de casa, eu te dou dever de casa", en: "You give me homework, I give you homework", category_id: "aula-mar30" },
  { pt: "Relaxar", en: "To relax", category_id: "aula-mar30" },
  { pt: "Relaxando", en: "Relaxing", category_id: "aula-mar30" },
  { pt: "Assistir", en: "To watch (shows / TV)", category_id: "aula-mar30" },
  { pt: "Dever de casa", en: "Homework", category_id: "aula-mar30" },
  { pt: "Capitão Fantástico", en: "Captain Fantastic", category_id: "aula-mar30" },
  { pt: "Tocar", en: "To play (instrument) / To touch", category_id: "aula-mar30" },
  { pt: "Treinar", en: "To train", category_id: "aula-mar30" },
  { pt: "Treinador", en: "Trainer / Coach", category_id: "aula-mar30" },
  { pt: "Consertar", en: "To fix", category_id: "april-fools" },
  { pt: "Minha coisa nova favorita", en: "My new favorite thing", category_id: "april-fools" },
  { pt: "Almoço por peso", en: "Lunch by weight", category_id: "april-fools" },
  { pt: "Todo lugar que eu vou eles", en: "Every place I go they", category_id: "april-fools" },
  { pt: "Variedade", en: "Variety", category_id: "april-fools" },
  { pt: "Feijão", en: "Beans", category_id: "april-fools" },
  { pt: "Colocar / Botar", en: "To put / To place", category_id: "april-fools" },
  { pt: "Me diz", en: "Tell me", category_id: "april-fools" },
  { pt: "Farofa", en: "Farofa (toasted cassava flour)", category_id: "april-fools" },
  { pt: "Saudade", en: "Longing / Missing", category_id: "april-fools" },
  { pt: "Farofa é engraçada porque não tem motivo/razão pra gostar, mas você gosta", en: "Farofa is funny because there's no reason to like it, but you do", category_id: "april-fools" },
  { pt: "Sabor", en: "Flavor", category_id: "april-fools" },
  { pt: "Tempero", en: "Seasoning", category_id: "april-fools" },
  { pt: "Se", en: "If", category_id: "april-fools" },
  { pt: "Farinha", en: "Flour", category_id: "april-fools" },
  { pt: "Eu não sei", en: "I don't know", category_id: "april-fools" },
  { pt: "Impressionar", en: "To impress", category_id: "april-fools" },
  { pt: "Com minha fala", en: "With my speech", category_id: "april-fools" },
  { pt: "Escutar / Ouvir", en: "To hear / To listen", category_id: "april-fools" },
  { pt: "Único / Única", en: "Unique", category_id: "april-fools" },
  { pt: "Eu estou ansiosa / animada", en: "I am anxious / excited", category_id: "april-fools" },
  { pt: "Destaque", en: "Highlight", category_id: "april-fools" },
  { pt: "Ensinar", en: "To teach", category_id: "april-fools" },
  { pt: "Humor", en: "Humor", category_id: "april-fools" },
  { pt: "Engraçado", en: "Funny", category_id: "april-fools" },
  { pt: "Piadas", en: "Jokes", category_id: "april-fools" },
  { pt: "Eu vou te ensinar a ser engraçada", en: "I'm going to teach you to be funny", category_id: "april-fools" },
  { pt: "Todo dia é igual", en: "Every day is the same", category_id: "april2" },
  { pt: "Todos os dias são iguais", en: "Every day is the same (plural)", category_id: "april2" },
  { pt: "Entediado", en: "Bored", category_id: "april2" },
  { pt: "Eventualmente", en: "Eventually", category_id: "april2" },
  { pt: "Passagem", en: "Ticket / passage", category_id: "april2" },
  { pt: "Assim", en: "Like this / so", category_id: "april2" },
  { pt: "Poderia", en: "Could", category_id: "april2" },
  { pt: "Eu poderia fazer", en: "I could do", category_id: "april2" },
  { pt: "Visitante", en: "Visitor", category_id: "april2" },
  { pt: "Visitar", en: "To visit", category_id: "april2" },
  { pt: "Hope", en: "Esperança", category_id: "april2" },
  { pt: "Esperançosamente", en: "Hopefully", category_id: "april2" },
  { pt: "Poderiam", en: "They could", category_id: "april2" },
  { pt: "Feito", en: "Done / made", category_id: "april2" },
  { pt: "Feio", en: "Ugly", category_id: "april2" },
  { pt: "Achei", en: "I found / I thought", category_id: "april2" },
  { pt: "Basicamente", en: "Basically", category_id: "april2" },
  { pt: "Por causa", en: "Because of", category_id: "april2" },
  { pt: "Desistir", en: "To give up", category_id: "april2" },
  { pt: "Páscoa", en: "Easter", category_id: "april2" },
  { pt: "Eu tenho uma dúvida", en: "I have a question / doubt", category_id: "april2" },
  { pt: "Já ouviu falar", en: "Have you heard of", category_id: "april2" },
  { pt: "Frase", en: "Sentence / phrase", category_id: "april2" },
  { pt: "Graças a Deus é sexta", en: "Thank God it's Friday", category_id: "april2" },
  { pt: "Sextou", en: "It's Friday! (slang)", category_id: "april2" },
  { pt: "fds - final de semana", en: "Weekend", category_id: "april2" },
  { pt: "Eu não tenho planos", en: "I don't have plans", category_id: "april2" },
  { pt: "Descobrir", en: "To discover / find out", category_id: "april2" },
  { pt: "Eu não sabia", en: "I didn't know", category_id: "april2" },
  { pt: "Eu amo animais", en: "I love animals", category_id: "april2" },
  { pt: "Fazenda", en: "Farm", category_id: "april2" },
  { pt: "Aposentada", en: "Retired (f)", category_id: "april2" },
  { pt: "No meio do nada", en: "In the middle of nowhere", category_id: "april2" }
];

module.exports = { categories, cards };
