const category = { id: "phrases-general", label: "General Phrases", css_class: "cat-phrases-general", group_name: "Phrases" };

const cards = [
  { pt: "Eu necessito / Eu preciso", en: "I need", category_id: "phrases-general" },
  { pt: "Atualmente só corro", en: "Currently I only run", category_id: "phrases-general" },
  { pt: "Eu não treino", en: "I don't work out", category_id: "phrases-general" },
  { pt: "Eu não tenho paciência", en: "I don't have patience", category_id: "phrases-general" },
  { pt: "Eu preciso de um plano", en: "I need a plan", category_id: "phrases-general" },
  { pt: "Hoje é dia de…", en: "Today is the day for…", category_id: "phrases-general" },
  { pt: "Hoje eu vou treinar…", en: "Today I'm going to train…", category_id: "phrases-general" },
  { pt: "Hoje eu vou fazer cardio", en: "Today I'm going to do cardio", category_id: "phrases-general" },
  { pt: "Ninguém falava", en: "Nobody was talking", category_id: "phrases-general" },
  { pt: "Eu prometo que", en: "I promise that", category_id: "phrases-general" },
  { pt: "Eu estou bem", en: "I'm fine / I'm good", category_id: "phrases-general" },
  { pt: "Eu cortei o cabelo", en: "I cut my hair", category_id: "phrases-general" },
  { pt: "Eu passei muita raiva", en: "I was very angry", category_id: "phrases-general" },
  { pt: "Eles não permitiram meu reembolso", en: "They didn't allow my refund", category_id: "phrases-general" },
  { pt: "Eu não pude devolver minha calça", en: "I couldn't return my pants", category_id: "phrases-general" },
  { pt: "Eu disse ao meu banco e eles me ajudaram", en: "I told my bank and they helped me", category_id: "phrases-general" },
  { pt: "Eles removeram o pagamento", en: "They removed the payment", category_id: "phrases-general" },
  { pt: "Eu só como batatas fritas quando eu treino", en: "I only eat fries when I work out", category_id: "phrases-general" },
  { pt: "Você tá perdendo", en: "You're missing out", category_id: "phrases-general" },
  { pt: "Hoje eu vou fazer meu CPF no Banco do Brasil", en: "Today I'll get my CPF at Banco do Brasil", category_id: "phrases-general" },
  { pt: "Hoje eu vou cortar o meu cabelo", en: "Today I'm going to cut my hair", category_id: "phrases-general" },
  { pt: "Eu não comprei ainda", en: "I haven't bought it yet", category_id: "phrases-general" },
  { pt: "Eu não agendei ainda", en: "I haven't scheduled it yet", category_id: "phrases-general" },
  { pt: "Não tenho certeza", en: "I'm not sure", category_id: "phrases-general" },
  { pt: "Dessa vez sério", en: "This time for real", category_id: "phrases-general" },
  { pt: "No final de semana, o que você vai fazer?", en: "On the weekend, what are you going to do?", category_id: "phrases-general" },
  { pt: "Não tenho planos ainda", en: "I don't have plans yet", category_id: "phrases-general" },
  { pt: "Ontem eu fui preguiçoso", en: "Yesterday I was lazy", category_id: "phrases-general" },
  { pt: "Como está o trabalho?", en: "How is work?", category_id: "phrases-general" },
  { pt: "Com o que você trabalha?", en: "What do you work with?", category_id: "phrases-general" },
  { pt: "Você já ouviu falar", en: "Have you already heard of", category_id: "phrases-general" },
  { pt: "Você é o desenvolvedor do aplicativo?", en: "Are you the app developer?", category_id: "phrases-general" },
  { pt: "Eu criei o aplicativo", en: "I created the app", category_id: "phrases-general" },
  { pt: "Buscando personal trainer para academia", en: "Looking for a personal trainer for the gym", category_id: "phrases-general" },
  { pt: "Eu preciso ficar forte", en: "I need to get strong", category_id: "phrases-general" },
  { pt: "Eu vou ao mercado", en: "I will go to the market", category_id: "phrases-general" },
  { pt: "No próximo final de semana eu vou…", en: "Next weekend I'm going to…", category_id: "phrases-general" },
  { pt: "Eu estou tendo uma classe boa", en: "I'm having a good class", category_id: "phrases-general" },
  { pt: "Estou buscando um escritório para trabalhar", en: "I'm looking for an office to work in", category_id: "phrases-general" },
  { pt: "Bebê, está frio lá fora", en: "Baby, it's cold outside", category_id: "phrases-general" },
  { pt: "Como foi o seu fim de semana?", en: "How was your weekend?", category_id: "phrases-general" },
  { pt: "Combina com sua personalidade", en: "It matches your personality", category_id: "phrases-general" },
  { pt: "Por que eu gosto de carnaval?", en: "Why do I like carnaval?", category_id: "phrases-general" },
  { pt: "Eu ia ir", en: "I was going to go", category_id: "phrases-general" },
  { pt: "Foi bom o carnaval ano passado aí?", en: "Was carnaval good last year there?", category_id: "phrases-general" },
  { pt: "Mas você foi para o do Rio ano retrasado", en: "But you went to the one in Rio two years ago", category_id: "phrases-general" },
  { pt: "Foi uma nova experiência", en: "It was a new experience", category_id: "phrases-general" },
  { pt: "Mudou minha mente", en: "Changed my mind", category_id: "phrases-general" },
  { pt: "Explodiu minha mente", en: "Blew my mind", category_id: "phrases-general" },
  { pt: "Foi uma experiência de abrir os olhos", en: "It was an eye-opening experience", category_id: "phrases-general" },
  { pt: "Eu tenho que trabalhar muito ainda hoje", en: "I still have to work a lot today", category_id: "phrases-general" },
  { pt: "Estou com calor", en: "I'm hot (feeling)", category_id: "phrases-general" },
  { pt: "Hoje está muito calor", en: "It's very hot today", category_id: "phrases-general" },
  { pt: "Que horas?", en: "What time?", category_id: "phrases-general" }
];

module.exports = { categories: [category], cards };
