const category = { id: "phrases-health", label: "Feelings & Health", css_class: "cat-phrases-health", group_name: "Phrases" };

const cards = [
  { pt: "Tô bem", en: "I'm well", category_id: "phrases-health" },
  { pt: "Tô mal", en: "I'm not well", category_id: "phrases-health" },
  { pt: "Tô cansado", en: "I'm tired", category_id: "phrases-health" },
  { pt: "Tô exausto", en: "I'm exhausted", category_id: "phrases-health" },
  { pt: "Tô com sono", en: "I'm sleepy", category_id: "phrases-health" },
  { pt: "Tô com fome", en: "I'm hungry", category_id: "phrases-health" },
  { pt: "Tô com sede", en: "I'm thirsty", category_id: "phrases-health" },
  { pt: "Tô com calor", en: "I'm hot", category_id: "phrases-health" },
  { pt: "Tô com frio", en: "I'm cold", category_id: "phrases-health" },
  { pt: "Tô com pressa", en: "I'm in a rush", category_id: "phrases-health" },
  { pt: "Tô com medo", en: "I'm scared", category_id: "phrases-health" },
  { pt: "Tô feliz", en: "I'm happy", category_id: "phrases-health" },
  { pt: "Tô triste", en: "I'm sad", category_id: "phrases-health" },
  { pt: "Tô estressado", en: "I'm stressed", category_id: "phrases-health" },
  { pt: "Tô ansioso", en: "I'm anxious", category_id: "phrases-health" },
  { pt: "Tô animado", en: "I'm excited", category_id: "phrases-health" },
  { pt: "Tô preocupado", en: "I'm worried", category_id: "phrases-health" },
  { pt: "Tô bravo", en: "I'm angry", category_id: "phrases-health" },
  { pt: "Tô puto", en: "I'm pissed", category_id: "phrases-health" },
  { pt: "Tô chateado", en: "I'm upset", category_id: "phrases-health" },
  { pt: "Tô meio mal", en: "I'm not feeling great", category_id: "phrases-health" },
  { pt: "Tô doente", en: "I'm sick", category_id: "phrases-health" },
  { pt: "Tô com dor de cabeça", en: "I have a headache", category_id: "phrases-health" },
  { pt: "Tô com dor de barriga", en: "I have a stomachache", category_id: "phrases-health" },
  { pt: "Tô com dor de garganta", en: "I have a sore throat", category_id: "phrases-health" },
  { pt: "Tô resfriado", en: "I have a cold", category_id: "phrases-health" },
  { pt: "Tô gripado", en: "I have the flu", category_id: "phrases-health" },
  { pt: "Tô com febre", en: "I have a fever", category_id: "phrases-health" },
  { pt: "Tô com tosse", en: "I have a cough", category_id: "phrases-health" },
  { pt: "Tô espirrando muito", en: "I'm sneezing a lot", category_id: "phrases-health" },
  { pt: "Tô com enjoo", en: "I feel nauseous", category_id: "phrases-health" },
  { pt: "Tô tonto", en: "I'm dizzy", category_id: "phrases-health" },
  { pt: "Tô sem fome", en: "I have no appetite", category_id: "phrases-health" },
  { pt: "Tô sem energia", en: "I have no energy", category_id: "phrases-health" },
  { pt: "Tô meio gripado", en: "I'm a bit under the weather", category_id: "phrases-health" },
  { pt: "Vou ao médico", en: "I'm going to the doctor", category_id: "phrases-health" },
  { pt: "Preciso ir ao médico", en: "I need to see a doctor", category_id: "phrases-health" },
  { pt: "Você tem remédio pra dor?", en: "Do you have pain meds?", category_id: "phrases-health" },
  { pt: "Tô tomando remédio", en: "I'm on medication", category_id: "phrases-health" },
  { pt: "Já melhorei", en: "I'm better now", category_id: "phrases-health" },
  { pt: "Tô melhor", en: "I'm better", category_id: "phrases-health" },
  { pt: "Tô péssimo", en: "I feel awful", category_id: "phrases-health" },
  { pt: "Tô zerado", en: "I'm wiped out", category_id: "phrases-health" },
  { pt: "Não tô legal", en: "I'm not feeling good", category_id: "phrases-health" },
  { pt: "Não tô a fim", en: "I'm not in the mood", category_id: "phrases-health" },
  { pt: "Tô numa boa", en: "I'm doing fine", category_id: "phrases-health" },
  { pt: "Tô de cama", en: "I'm bedridden", category_id: "phrases-health" },
  { pt: "Tô de ressaca", en: "I'm hungover", category_id: "phrases-health" },
  { pt: "Sinto muito", en: "I'm so sorry", category_id: "phrases-health" },
  { pt: "Melhoras", en: "Get well soon", category_id: "phrases-health" }
];

module.exports = { categories: [category], cards };
