const category = { id: "phrases-help", label: "Asking for Help & Directions", css_class: "cat-phrases-help", group_name: "Phrases" };

const cards = [
  { pt: "Você pode me ajudar?", en: "Can you help me?", category_id: "phrases-help" },
  { pt: "Pode me ajudar com uma coisa?", en: "Can you help me with something?", category_id: "phrases-help" },
  { pt: "Onde fica...?", en: "Where is...?", category_id: "phrases-help" },
  { pt: "Como chego em...?", en: "How do I get to...?", category_id: "phrases-help" },
  { pt: "É longe daqui?", en: "Is it far from here?", category_id: "phrases-help" },
  { pt: "É perto?", en: "Is it close?", category_id: "phrases-help" },
  { pt: "Fica a quantos minutos?", en: "How many minutes away is it?", category_id: "phrases-help" },
  { pt: "Sou de fora", en: "I'm not from here", category_id: "phrases-help" },
  { pt: "Estou perdido", en: "I'm lost", category_id: "phrases-help" },
  { pt: "Você sabe onde é...?", en: "Do you know where ... is?", category_id: "phrases-help" },
  { pt: "Pra que lado eu vou?", en: "Which way do I go?", category_id: "phrases-help" },
  { pt: "É reto?", en: "Is it straight ahead?", category_id: "phrases-help" },
  { pt: "Vira à direita", en: "Turn right", category_id: "phrases-help" },
  { pt: "Vira à esquerda", en: "Turn left", category_id: "phrases-help" },
  { pt: "Segue reto", en: "Go straight", category_id: "phrases-help" },
  { pt: "Volta pra trás", en: "Go back", category_id: "phrases-help" },
  { pt: "Na próxima esquina", en: "On the next corner", category_id: "phrases-help" },
  { pt: "Atrás de você", en: "Behind you", category_id: "phrases-help" },
  { pt: "Na frente de...", en: "In front of...", category_id: "phrases-help" },
  { pt: "Do lado de...", en: "Next to...", category_id: "phrases-help" },
  { pt: "No final da rua", en: "At the end of the street", category_id: "phrases-help" },
  { pt: "Tem um ponto de ônibus?", en: "Is there a bus stop?", category_id: "phrases-help" },
  { pt: "Onde pego o metrô?", en: "Where do I catch the subway?", category_id: "phrases-help" },
  { pt: "Que ônibus passa aqui?", en: "Which bus comes by here?", category_id: "phrases-help" },
  { pt: "Pode chamar um Uber?", en: "Can you call an Uber?", category_id: "phrases-help" },
  { pt: "Tem ponto de táxi?", en: "Is there a taxi stand?", category_id: "phrases-help" },
  { pt: "Tem Wi-Fi aqui?", en: "Is there Wi-Fi here?", category_id: "phrases-help" },
  { pt: "Qual é a senha?", en: "What's the password?", category_id: "phrases-help" },
  { pt: "Tem banheiro?", en: "Is there a bathroom?", category_id: "phrases-help" },
  { pt: "Onde fica o banheiro?", en: "Where's the bathroom?", category_id: "phrases-help" },
  { pt: "Tem caixa eletrônico?", en: "Is there an ATM?", category_id: "phrases-help" },
  { pt: "Onde tem uma farmácia?", en: "Where's a pharmacy?", category_id: "phrases-help" },
  { pt: "Pode falar mais devagar?", en: "Can you speak more slowly?", category_id: "phrases-help" },
  { pt: "Pode repetir?", en: "Can you repeat?", category_id: "phrases-help" },
  { pt: "Não entendi", en: "I didn't understand", category_id: "phrases-help" },
  { pt: "Como se diz...?", en: "How do you say...?", category_id: "phrases-help" },
  { pt: "O que significa...?", en: "What does ... mean?", category_id: "phrases-help" },
  { pt: "Você fala inglês?", en: "Do you speak English?", category_id: "phrases-help" },
  { pt: "Eu não falo bem português", en: "I don't speak Portuguese well", category_id: "phrases-help" },
  { pt: "Estou aprendendo", en: "I'm learning", category_id: "phrases-help" },
  { pt: "Pode escrever pra mim?", en: "Can you write it down for me?", category_id: "phrases-help" },
  { pt: "Pode anotar?", en: "Can you write it down?", category_id: "phrases-help" },
  { pt: "Tem como ver no mapa?", en: "Can we look on the map?", category_id: "phrases-help" },
  { pt: "Estou procurando...", en: "I'm looking for...", category_id: "phrases-help" },
  { pt: "Por favor", en: "Please", category_id: "phrases-help" },
  { pt: "Com licença", en: "Excuse me", category_id: "phrases-help" },
  { pt: "Desculpa incomodar", en: "Sorry to bother you", category_id: "phrases-help" },
  { pt: "Obrigado pela ajuda", en: "Thanks for the help", category_id: "phrases-help" },
  { pt: "Tem alguém que fala inglês?", en: "Is there someone who speaks English?", category_id: "phrases-help" },
  { pt: "Preciso de ajuda", en: "I need help", category_id: "phrases-help" }
];

module.exports = { categories: [category], cards };
