const category = { id: "phrases-reactions", label: "Reactions & Fillers", css_class: "cat-phrases-reactions", group_name: "Phrases" };

const cards = [
  { pt: "Nossa!", en: "Wow!", category_id: "phrases-reactions" },
  { pt: "Sério?", en: "Seriously?", category_id: "phrases-reactions" },
  { pt: "Né?", en: "Right?", category_id: "phrases-reactions" },
  { pt: "Beleza", en: "Cool / Got it", category_id: "phrases-reactions" },
  { pt: "Valeu", en: "Thanks", category_id: "phrases-reactions" },
  { pt: "Tipo assim", en: "Like, you know", category_id: "phrases-reactions" },
  { pt: "Que legal!", en: "How cool!", category_id: "phrases-reactions" },
  { pt: "Que pena", en: "What a pity", category_id: "phrases-reactions" },
  { pt: "Pô", en: "Man / Damn", category_id: "phrases-reactions" },
  { pt: "Caraca", en: "Damn / No way", category_id: "phrases-reactions" },
  { pt: "Aí sim!", en: "Now we're talking!", category_id: "phrases-reactions" },
  { pt: "Pois é", en: "Yeah / Right", category_id: "phrases-reactions" },
  { pt: "Tá bom", en: "Okay", category_id: "phrases-reactions" },
  { pt: "Tá certo", en: "That's right", category_id: "phrases-reactions" },
  { pt: "Cara", en: "Dude", category_id: "phrases-reactions" },
  { pt: "Putz", en: "Damn", category_id: "phrases-reactions" },
  { pt: "Eita", en: "Whoa", category_id: "phrases-reactions" },
  { pt: "Vish", en: "Uh oh", category_id: "phrases-reactions" },
  { pt: "Que isso!", en: "Come on! / No way!", category_id: "phrases-reactions" },
  { pt: "Imagina", en: "Don't mention it", category_id: "phrases-reactions" },
  { pt: "Pra caramba", en: "Like crazy", category_id: "phrases-reactions" },
  { pt: "Demais", en: "Too much / Awesome", category_id: "phrases-reactions" },
  { pt: "Foi mal", en: "My bad", category_id: "phrases-reactions" },
  { pt: "Deixa pra lá", en: "Let it go / Never mind", category_id: "phrases-reactions" },
  { pt: "Que saco", en: "What a pain", category_id: "phrases-reactions" },
  { pt: "Que chato", en: "How annoying", category_id: "phrases-reactions" },
  { pt: "Que delícia", en: "How delicious / How lovely", category_id: "phrases-reactions" },
  { pt: "De boa", en: "It's all good", category_id: "phrases-reactions" },
  { pt: "Tranquilo", en: "Chill / No worries", category_id: "phrases-reactions" },
  { pt: "Sem problema", en: "No problem", category_id: "phrases-reactions" },
  { pt: "Com certeza", en: "For sure", category_id: "phrases-reactions" },
  { pt: "Claro", en: "Of course", category_id: "phrases-reactions" },
  { pt: "Óbvio", en: "Obviously", category_id: "phrases-reactions" },
  { pt: "Talvez", en: "Maybe", category_id: "phrases-reactions" },
  { pt: "Acho que sim", en: "I think so", category_id: "phrases-reactions" },
  { pt: "Acho que não", en: "I don't think so", category_id: "phrases-reactions" },
  { pt: "Não sei", en: "I don't know", category_id: "phrases-reactions" },
  { pt: "Sei lá", en: "Who knows / Beats me", category_id: "phrases-reactions" },
  { pt: "Tomara", en: "Hopefully", category_id: "phrases-reactions" },
  { pt: "Espero que sim", en: "I hope so", category_id: "phrases-reactions" },
  { pt: "Que bom!", en: "That's good!", category_id: "phrases-reactions" },
  { pt: "Que ótimo!", en: "How great!", category_id: "phrases-reactions" },
  { pt: "Verdade", en: "True", category_id: "phrases-reactions" },
  { pt: "Mentira!", en: "No way! (lit. lie)", category_id: "phrases-reactions" },
  { pt: "Jura?", en: "Really? (lit. swear?)", category_id: "phrases-reactions" },
  { pt: "Não acredito", en: "I don't believe it", category_id: "phrases-reactions" },
  { pt: "Vai vendo", en: "You'll see / Just watch", category_id: "phrases-reactions" },
  { pt: "Bora", en: "Let's go", category_id: "phrases-reactions" },
  { pt: "Falou", en: "Got it / See ya", category_id: "phrases-reactions" },
  { pt: "Massa", en: "Awesome / Cool", category_id: "phrases-reactions" }
];

module.exports = { categories: [category], cards };
