const category = { id: "phrases-restaurant", label: "Restaurant & Food", css_class: "cat-phrases-restaurant", group_name: "Phrases" };

const cards = [
  { pt: "A conta, por favor", en: "The check, please", category_id: "phrases-restaurant" },
  { pt: "Para viagem", en: "To go / Takeout", category_id: "phrases-restaurant" },
  { pt: "Para comer aqui", en: "For here", category_id: "phrases-restaurant" },
  { pt: "O cardápio, por favor", en: "The menu, please", category_id: "phrases-restaurant" },
  { pt: "Qual o prato do dia?", en: "What's the dish of the day?", category_id: "phrases-restaurant" },
  { pt: "O que vocês recomendam?", en: "What do you recommend?", category_id: "phrases-restaurant" },
  { pt: "Eu vou querer...", en: "I'll have...", category_id: "phrases-restaurant" },
  { pt: "Pode trazer mais um?", en: "Can you bring another?", category_id: "phrases-restaurant" },
  { pt: "Sem cebola, por favor", en: "No onion, please", category_id: "phrases-restaurant" },
  { pt: "Sem pimenta", en: "No pepper / No chili", category_id: "phrases-restaurant" },
  { pt: "Sou alérgico a...", en: "I'm allergic to...", category_id: "phrases-restaurant" },
  { pt: "Sou vegetariano", en: "I'm vegetarian", category_id: "phrases-restaurant" },
  { pt: "Tem opção vegana?", en: "Is there a vegan option?", category_id: "phrases-restaurant" },
  { pt: "Tá uma delícia", en: "It's delicious", category_id: "phrases-restaurant" },
  { pt: "Está muito bom", en: "It's very good", category_id: "phrases-restaurant" },
  { pt: "Posso ver o cardápio?", en: "Can I see the menu?", category_id: "phrases-restaurant" },
  { pt: "Faz reserva?", en: "Do you take reservations?", category_id: "phrases-restaurant" },
  { pt: "Tem couvert?", en: "Is there a cover charge?", category_id: "phrases-restaurant" },
  { pt: "Pode dividir a conta?", en: "Can we split the bill?", category_id: "phrases-restaurant" },
  { pt: "Vai uma cervejinha?", en: "How about a beer?", category_id: "phrases-restaurant" },
  { pt: "Sem gelo, por favor", en: "No ice, please", category_id: "phrases-restaurant" },
  { pt: "Com gás ou sem gás?", en: "Sparkling or still?", category_id: "phrases-restaurant" },
  { pt: "Eu queria um cafezinho", en: "I'd like a coffee", category_id: "phrases-restaurant" },
  { pt: "Mais uma água, por favor", en: "Another water, please", category_id: "phrases-restaurant" },
  { pt: "Tem mesa pra dois?", en: "Do you have a table for two?", category_id: "phrases-restaurant" },
  { pt: "Quanto tempo de espera?", en: "How long is the wait?", category_id: "phrases-restaurant" },
  { pt: "Vou pegar o rodízio", en: "I'll do the all-you-can-eat", category_id: "phrases-restaurant" },
  { pt: "Bem passado", en: "Well done", category_id: "phrases-restaurant" },
  { pt: "Mal passado", en: "Rare", category_id: "phrases-restaurant" },
  { pt: "Ao ponto", en: "Medium", category_id: "phrases-restaurant" },
  { pt: "Tá ótimo, obrigado", en: "It's great, thanks", category_id: "phrases-restaurant" },
  { pt: "Pode tirar o prato", en: "You can take the plate", category_id: "phrases-restaurant" },
  { pt: "Já posso pedir?", en: "Can I order now?", category_id: "phrases-restaurant" },
  { pt: "Demora muito?", en: "Does it take long?", category_id: "phrases-restaurant" },
  { pt: "Vem com o quê?", en: "What does it come with?", category_id: "phrases-restaurant" },
  { pt: "É picante?", en: "Is it spicy?", category_id: "phrases-restaurant" },
  { pt: "Tá faltando o...", en: "The ... is missing", category_id: "phrases-restaurant" },
  { pt: "Posso trocar por...?", en: "Can I swap it for...?", category_id: "phrases-restaurant" },
  { pt: "Foi mal, eu pedi outra coisa", en: "Sorry, I ordered something else", category_id: "phrases-restaurant" },
  { pt: "Pode embrulhar pra mim?", en: "Can you wrap it up for me?", category_id: "phrases-restaurant" },
  { pt: "Eu pago a sua", en: "I'll get yours", category_id: "phrases-restaurant" },
  { pt: "Vamos rachar", en: "Let's split it", category_id: "phrases-restaurant" },
  { pt: "A gorjeta tá inclusa?", en: "Is the tip included?", category_id: "phrases-restaurant" },
  { pt: "Está reservado em nome de...", en: "It's reserved under...", category_id: "phrases-restaurant" },
  { pt: "Quero meia porção", en: "I'd like a half portion", category_id: "phrases-restaurant" },
  { pt: "O que é isso aqui?", en: "What's this here?", category_id: "phrases-restaurant" },
  { pt: "Estou cheio", en: "I'm full", category_id: "phrases-restaurant" },
  { pt: "Parabéns ao chef", en: "Compliments to the chef", category_id: "phrases-restaurant" },
  { pt: "Tem suco natural?", en: "Do you have fresh juice?", category_id: "phrases-restaurant" },
  { pt: "Pode trazer mais pão?", en: "Can you bring more bread?", category_id: "phrases-restaurant" }
];

module.exports = { categories: [category], cards };
