const category = { id: "phrases-routine", label: "Daily Routine & Time", css_class: "cat-phrases-routine", group_name: "Phrases" };

const cards = [
  { pt: "Tô a caminho", en: "I'm on my way", category_id: "phrases-routine" },
  { pt: "Já já chego", en: "I'll be there soon", category_id: "phrases-routine" },
  { pt: "Daqui a pouco", en: "In a bit", category_id: "phrases-routine" },
  { pt: "Mais tarde", en: "Later", category_id: "phrases-routine" },
  { pt: "Agora não dá", en: "I can't right now", category_id: "phrases-routine" },
  { pt: "Acabei de acordar", en: "I just woke up", category_id: "phrases-routine" },
  { pt: "Acabei de chegar", en: "I just got here", category_id: "phrases-routine" },
  { pt: "Tô atrasado", en: "I'm late", category_id: "phrases-routine" },
  { pt: "Tô chegando", en: "I'm almost there", category_id: "phrases-routine" },
  { pt: "Cheguei", en: "I'm here", category_id: "phrases-routine" },
  { pt: "Vou tomar banho", en: "I'm going to shower", category_id: "phrases-routine" },
  { pt: "Vou dormir", en: "I'm going to sleep", category_id: "phrases-routine" },
  { pt: "Bom dia", en: "Good morning", category_id: "phrases-routine" },
  { pt: "Boa tarde", en: "Good afternoon", category_id: "phrases-routine" },
  { pt: "Boa noite", en: "Good night", category_id: "phrases-routine" },
  { pt: "Que horas são?", en: "What time is it?", category_id: "phrases-routine" },
  { pt: "Já são oito horas", en: "It's already eight o'clock", category_id: "phrases-routine" },
  { pt: "Tô sem tempo", en: "I'm out of time", category_id: "phrases-routine" },
  { pt: "Hoje em dia", en: "Nowadays", category_id: "phrases-routine" },
  { pt: "Antes de dormir", en: "Before bed", category_id: "phrases-routine" },
  { pt: "Logo cedo", en: "Early in the morning", category_id: "phrases-routine" },
  { pt: "Mais cedo", en: "Earlier", category_id: "phrases-routine" },
  { pt: "No fim do dia", en: "At the end of the day", category_id: "phrases-routine" },
  { pt: "Hoje à noite", en: "Tonight", category_id: "phrases-routine" },
  { pt: "Amanhã cedo", en: "Tomorrow morning", category_id: "phrases-routine" },
  { pt: "Depois de amanhã", en: "Day after tomorrow", category_id: "phrases-routine" },
  { pt: "Anteontem", en: "Day before yesterday", category_id: "phrases-routine" },
  { pt: "Outro dia", en: "The other day", category_id: "phrases-routine" },
  { pt: "Semana que vem", en: "Next week", category_id: "phrases-routine" },
  { pt: "Mês que vem", en: "Next month", category_id: "phrases-routine" },
  { pt: "Ano passado", en: "Last year", category_id: "phrases-routine" },
  { pt: "Já é tarde", en: "It's already late", category_id: "phrases-routine" },
  { pt: "Tô indo agora", en: "I'm going now", category_id: "phrases-routine" },
  { pt: "Vou nessa", en: "I'm out of here", category_id: "phrases-routine" },
  { pt: "Tô saindo", en: "I'm leaving", category_id: "phrases-routine" },
  { pt: "Ainda tô em casa", en: "I'm still home", category_id: "phrases-routine" },
  { pt: "Ainda não almocei", en: "I haven't had lunch yet", category_id: "phrases-routine" },
  { pt: "Tô tomando café", en: "I'm having coffee / breakfast", category_id: "phrases-routine" },
  { pt: "Já jantei", en: "I already had dinner", category_id: "phrases-routine" },
  { pt: "Tô voltando", en: "I'm coming back", category_id: "phrases-routine" },
  { pt: "De manhã eu...", en: "In the morning I...", category_id: "phrases-routine" },
  { pt: "À tarde eu...", en: "In the afternoon I...", category_id: "phrases-routine" },
  { pt: "À noite eu...", en: "At night I...", category_id: "phrases-routine" },
  { pt: "Final de semana eu...", en: "On the weekend I...", category_id: "phrases-routine" },
  { pt: "Toda segunda", en: "Every Monday", category_id: "phrases-routine" },
  { pt: "Todo dia", en: "Every day", category_id: "phrases-routine" },
  { pt: "Uma vez por semana", en: "Once a week", category_id: "phrases-routine" },
  { pt: "De vez em quando", en: "Once in a while", category_id: "phrases-routine" },
  { pt: "Sempre", en: "Always", category_id: "phrases-routine" },
  { pt: "Nunca", en: "Never", category_id: "phrases-routine" }
];

module.exports = { categories: [category], cards };
