const category = { id: "phrases-shopping", label: "Shopping & Money", css_class: "cat-phrases-shopping", group_name: "Phrases" };

const cards = [
  { pt: "Quanto custa?", en: "How much is it?", category_id: "phrases-shopping" },
  { pt: "Quanto é?", en: "How much?", category_id: "phrases-shopping" },
  { pt: "Aceita cartão?", en: "Do you take cards?", category_id: "phrases-shopping" },
  { pt: "Aceita PIX?", en: "Do you take PIX?", category_id: "phrases-shopping" },
  { pt: "Pode parcelar?", en: "Can I pay in installments?", category_id: "phrases-shopping" },
  { pt: "Em quantas vezes?", en: "In how many installments?", category_id: "phrases-shopping" },
  { pt: "Tem desconto?", en: "Is there a discount?", category_id: "phrases-shopping" },
  { pt: "Tem desconto à vista?", en: "Discount for paying in cash?", category_id: "phrases-shopping" },
  { pt: "Faz por menos?", en: "Will you take less?", category_id: "phrases-shopping" },
  { pt: "Tá caro", en: "It's expensive", category_id: "phrases-shopping" },
  { pt: "Tá barato", en: "It's cheap", category_id: "phrases-shopping" },
  { pt: "Vou levar", en: "I'll take it", category_id: "phrases-shopping" },
  { pt: "Vou pensar", en: "I'll think about it", category_id: "phrases-shopping" },
  { pt: "Só estou olhando", en: "I'm just looking", category_id: "phrases-shopping" },
  { pt: "Tem outra cor?", en: "Do you have another color?", category_id: "phrases-shopping" },
  { pt: "Tem tamanho M?", en: "Do you have size M?", category_id: "phrases-shopping" },
  { pt: "Posso experimentar?", en: "Can I try it on?", category_id: "phrases-shopping" },
  { pt: "Onde fica o provador?", en: "Where's the fitting room?", category_id: "phrases-shopping" },
  { pt: "Não serviu", en: "It didn't fit", category_id: "phrases-shopping" },
  { pt: "Ficou apertado", en: "It's too tight", category_id: "phrases-shopping" },
  { pt: "Ficou folgado", en: "It's too loose", category_id: "phrases-shopping" },
  { pt: "Tem nota fiscal?", en: "Is there a receipt?", category_id: "phrases-shopping" },
  { pt: "Pode embrulhar pra presente?", en: "Can you gift-wrap it?", category_id: "phrases-shopping" },
  { pt: "Posso trocar?", en: "Can I exchange it?", category_id: "phrases-shopping" },
  { pt: "Qual o prazo de troca?", en: "What's the exchange window?", category_id: "phrases-shopping" },
  { pt: "Tem garantia?", en: "Does it have a warranty?", category_id: "phrases-shopping" },
  { pt: "Está em promoção?", en: "Is it on sale?", category_id: "phrases-shopping" },
  { pt: "Quanto fica à vista?", en: "How much is it in cash?", category_id: "phrases-shopping" },
  { pt: "Tem troco?", en: "Do you have change?", category_id: "phrases-shopping" },
  { pt: "Não tenho troco", en: "I don't have change", category_id: "phrases-shopping" },
  { pt: "Pode passar no débito", en: "You can charge it as debit", category_id: "phrases-shopping" },
  { pt: "No crédito ou débito?", en: "Credit or debit?", category_id: "phrases-shopping" },
  { pt: "Esqueci a carteira", en: "I forgot my wallet", category_id: "phrases-shopping" },
  { pt: "Tô sem dinheiro", en: "I'm out of money", category_id: "phrases-shopping" },
  { pt: "Tô duro", en: "I'm broke", category_id: "phrases-shopping" },
  { pt: "Tá fora do meu orçamento", en: "It's out of my budget", category_id: "phrases-shopping" },
  { pt: "Vale a pena?", en: "Is it worth it?", category_id: "phrases-shopping" },
  { pt: "Não vale a pena", en: "It's not worth it", category_id: "phrases-shopping" },
  { pt: "Compensa", en: "It's worth it", category_id: "phrases-shopping" },
  { pt: "Saiu caro", en: "It came out expensive", category_id: "phrases-shopping" },
  { pt: "Custa os olhos da cara", en: "Costs an arm and a leg", category_id: "phrases-shopping" },
  { pt: "Posso pagar depois?", en: "Can I pay later?", category_id: "phrases-shopping" },
  { pt: "Tem mais barato?", en: "Is there a cheaper one?", category_id: "phrases-shopping" },
  { pt: "Esse é o último?", en: "Is this the last one?", category_id: "phrases-shopping" },
  { pt: "Tem em estoque?", en: "Is it in stock?", category_id: "phrases-shopping" },
  { pt: "Pode reservar pra mim?", en: "Can you hold it for me?", category_id: "phrases-shopping" },
  { pt: "Quando chega?", en: "When does it arrive?", category_id: "phrases-shopping" },
  { pt: "Faz entrega?", en: "Do you deliver?", category_id: "phrases-shopping" },
  { pt: "Quanto é a entrega?", en: "How much is delivery?", category_id: "phrases-shopping" },
  { pt: "Recibo, por favor", en: "Receipt, please", category_id: "phrases-shopping" }
];

module.exports = { categories: [category], cards };
