const category = { id: "phrases-smalltalk", label: "Small Talk & Greetings", css_class: "cat-phrases-smalltalk", group_name: "Phrases" };

const cards = [
  { pt: "Tudo bem?", en: "All good?", category_id: "phrases-smalltalk" },
  { pt: "Tudo bom?", en: "All good?", category_id: "phrases-smalltalk" },
  { pt: "Como vai?", en: "How's it going?", category_id: "phrases-smalltalk" },
  { pt: "E aí?", en: "What's up?", category_id: "phrases-smalltalk" },
  { pt: "Beleza?", en: "All cool?", category_id: "phrases-smalltalk" },
  { pt: "Quanto tempo!", en: "Long time no see!", category_id: "phrases-smalltalk" },
  { pt: "Faz tempo", en: "It's been a while", category_id: "phrases-smalltalk" },
  { pt: "Como você tá?", en: "How are you?", category_id: "phrases-smalltalk" },
  { pt: "Tô bem, e você?", en: "I'm good, and you?", category_id: "phrases-smalltalk" },
  { pt: "Tô na correria", en: "Things are crazy busy", category_id: "phrases-smalltalk" },
  { pt: "Tudo certo?", en: "Everything good?", category_id: "phrases-smalltalk" },
  { pt: "Que bom te ver", en: "Good to see you", category_id: "phrases-smalltalk" },
  { pt: "Manda um abraço pra...", en: "Send a hug to...", category_id: "phrases-smalltalk" },
  { pt: "Manda um beijo pra...", en: "Send a kiss to...", category_id: "phrases-smalltalk" },
  { pt: "A gente se fala", en: "We'll talk soon", category_id: "phrases-smalltalk" },
  { pt: "A gente se vê", en: "See you around", category_id: "phrases-smalltalk" },
  { pt: "Até mais", en: "See you later", category_id: "phrases-smalltalk" },
  { pt: "Até logo", en: "See you soon", category_id: "phrases-smalltalk" },
  { pt: "Até amanhã", en: "See you tomorrow", category_id: "phrases-smalltalk" },
  { pt: "Tchau, tchau", en: "Bye-bye", category_id: "phrases-smalltalk" },
  { pt: "Boa sorte!", en: "Good luck!", category_id: "phrases-smalltalk" },
  { pt: "Bom fim de semana", en: "Have a good weekend", category_id: "phrases-smalltalk" },
  { pt: "Boa semana", en: "Have a good week", category_id: "phrases-smalltalk" },
  { pt: "Bom feriado", en: "Happy holiday", category_id: "phrases-smalltalk" },
  { pt: "Bom descanso", en: "Rest well", category_id: "phrases-smalltalk" },
  { pt: "Boa viagem", en: "Have a good trip", category_id: "phrases-smalltalk" },
  { pt: "Bom apetite", en: "Enjoy your meal", category_id: "phrases-smalltalk" },
  { pt: "Saúde!", en: "Cheers! / Bless you!", category_id: "phrases-smalltalk" },
  { pt: "Parabéns!", en: "Congrats!", category_id: "phrases-smalltalk" },
  { pt: "Felicidades", en: "Best wishes", category_id: "phrases-smalltalk" },
  { pt: "E a família?", en: "And the family?", category_id: "phrases-smalltalk" },
  { pt: "Como tá a família?", en: "How's the family?", category_id: "phrases-smalltalk" },
  { pt: "E o trabalho?", en: "And work?", category_id: "phrases-smalltalk" },
  { pt: "Cadê você?", en: "Where are you?", category_id: "phrases-smalltalk" },
  { pt: "Sumiu!", en: "You've disappeared!", category_id: "phrases-smalltalk" },
  { pt: "Você anda sumido", en: "You've been MIA", category_id: "phrases-smalltalk" },
  { pt: "Quando a gente se vê?", en: "When are we meeting up?", category_id: "phrases-smalltalk" },
  { pt: "Vamos marcar", en: "Let's set something up", category_id: "phrases-smalltalk" },
  { pt: "Te ligo depois", en: "I'll call you later", category_id: "phrases-smalltalk" },
  { pt: "Te chamo no zap", en: "I'll message you on WhatsApp", category_id: "phrases-smalltalk" },
  { pt: "Me dá seu zap", en: "Give me your WhatsApp", category_id: "phrases-smalltalk" },
  { pt: "Foi um prazer", en: "It was a pleasure", category_id: "phrases-smalltalk" },
  { pt: "Igualmente", en: "Likewise", category_id: "phrases-smalltalk" },
  { pt: "O prazer é meu", en: "The pleasure is mine", category_id: "phrases-smalltalk" },
  { pt: "Muito prazer", en: "Nice to meet you", category_id: "phrases-smalltalk" },
  { pt: "Prazer em te conhecer", en: "Nice to meet you", category_id: "phrases-smalltalk" },
  { pt: "Como é seu nome?", en: "What's your name?", category_id: "phrases-smalltalk" },
  { pt: "De onde você é?", en: "Where are you from?", category_id: "phrases-smalltalk" },
  { pt: "Tem quanto tempo aqui?", en: "How long have you been here?", category_id: "phrases-smalltalk" },
  { pt: "Bem-vindo", en: "Welcome", category_id: "phrases-smalltalk" }
];

module.exports = { categories: [category], cards };
