const category = { id: "aula-jul20", label: "Aula Jul 20", css_class: "cat-aula-jul20", group_name: "Aulas" };

const cards = [
  { pt: "Ar condicionado", en: "Air conditioner", category_id: "aula-jul20" },
  { pt: "Consertado", en: "Fixed / Repaired", category_id: "aula-jul20" },
  { pt: "Fumaça", en: "Smoke", category_id: "aula-jul20" },
  { pt: "Incêndio", en: "Fire (blaze)", category_id: "aula-jul20" },
  { pt: "Incêndio florestal", en: "Forest fire / Wildfire", category_id: "aula-jul20" },
  { pt: "Pulmão / Pulmões", en: "Lung / Lungs", category_id: "aula-jul20" },
  { pt: "Pássaros / Aves", en: "Birds (songbirds) / Birds (in general)", category_id: "aula-jul20" },
  { pt: "Passarinho", en: "Little bird / Birdie", category_id: "aula-jul20" },
  { pt: "Doença / Doente", en: "Illness / Sick", category_id: "aula-jul20" },
  { pt: "Pombos", en: "Pigeons", category_id: "aula-jul20" },
  { pt: "Dentro da parede", en: "Inside the wall", category_id: "aula-jul20" },
  { pt: "Dentro do armário", en: "Inside the cabinet", category_id: "aula-jul20" },
  { pt: "Matar", en: "To kill", category_id: "aula-jul20" },
  { pt: "Formigas", en: "Ants", category_id: "aula-jul20" },
  { pt: "Caramujo", en: "Snail", category_id: "aula-jul20" },
  { pt: "Farmácia / Drogaria", en: "Pharmacy / Drugstore", category_id: "aula-jul20" },
  { pt: "Envenenado", en: "Poisoned", category_id: "aula-jul20" },
  { pt: "Morri", en: "I died", category_id: "aula-jul20" },
  { pt: "Da / Do / De", en: "Of the (fem.) / Of the (masc.) / Of, from", category_id: "aula-jul20" },
  { pt: "Noiva", en: "Bride / Fiancée", category_id: "aula-jul20" },
  { pt: "Psiquiatria", en: "Psychiatry", category_id: "aula-jul20" },
  { pt: "Acessar", en: "To access", category_id: "aula-jul20" },
  { pt: "Causar", en: "To cause", category_id: "aula-jul20" },
  { pt: "Dano", en: "Damage / Harm", category_id: "aula-jul20" },
  { pt: "Um dos melhores filmes já feitos", en: "One of the best movies ever made", category_id: "aula-jul20" },
  { pt: "Concordo", en: "I agree", category_id: "aula-jul20" },
  { pt: "Parceiro", en: "Partner", category_id: "aula-jul20" },
  { pt: "Parceiro de negócios", en: "Business partner", category_id: "aula-jul20" },
  { pt: "Sentir / Sentar", en: "To feel / To sit", category_id: "aula-jul20" },
  { pt: "Sinto / Sento", en: "I feel / I sit", category_id: "aula-jul20" },
  { pt: "Esperançoso / Esperançosamente", en: "Hopeful / Hopefully", category_id: "aula-jul20" },
  { pt: "Compromisso / Eu sou compromissado", en: "Commitment / I'm taken (in a relationship)", category_id: "aula-jul20" },
  { pt: "Sessão / Consulta", en: "Session / (Medical) appointment", category_id: "aula-jul20" },
  { pt: "Meta", en: "Goal / Target", category_id: "aula-jul20" },
  { pt: "Trapacear", en: "To cheat", category_id: "aula-jul20" },
  { pt: "Juízes", en: "Judges", category_id: "aula-jul20" },
  { pt: "Triste / Tristeza", en: "Sad / Sadness", category_id: "aula-jul20" },
  { pt: "Houve", en: "There was / There were", category_id: "aula-jul20" },
  { pt: "Abraço / Braço", en: "Hug / Arm", category_id: "aula-jul20" },
  { pt: "Pé / Pés", en: "Foot / Feet", category_id: "aula-jul20" },
  { pt: "Estressante", en: "Stressful", category_id: "aula-jul20" },
  { pt: "Chaminé", en: "Chimney", category_id: "aula-jul20" },
  { pt: "Resfriado / Gripe / Gripado", en: "Cold / Flu / Down with the flu", category_id: "aula-jul20" },
  { pt: "Estranho", en: "Strange / Weird", category_id: "aula-jul20" },
  { pt: "Tarde demais", en: "Too late", category_id: "aula-jul20" },
  { pt: "Remover", en: "To remove", category_id: "aula-jul20" },
  { pt: "Assim que acabar", en: "As soon as it's over", category_id: "aula-jul20" },
  { pt: "Roubo / Roubar", en: "Robbery / To steal", category_id: "aula-jul20" },
  { pt: "Começar", en: "To begin / To start", category_id: "aula-jul20" },
  { pt: "Teoria da conspiração", en: "Conspiracy theory", category_id: "aula-jul20" },
  { pt: "Contar", en: "To tell / To count", category_id: "aula-jul20" },
  { pt: "Alguma razão / Sem razão", en: "Some reason / No reason", category_id: "aula-jul20" },
  { pt: "Cadê", en: "Where is…?", category_id: "aula-jul20" },
  { pt: "Dormiu", en: "(You / He / She) slept", category_id: "aula-jul20" },
  { pt: "Sono", en: "Sleep / Sleepiness", category_id: "aula-jul20" },
  { pt: "Desistir de algo", en: "To give up on something", category_id: "aula-jul20" },
  { pt: "Nesse / Nessa", en: "In that (masc.) / In that (fem.)", category_id: "aula-jul20" },
  { pt: "Ensolarado", en: "Sunny", category_id: "aula-jul20" },
  { pt: "Placas", en: "Signs / License plates", category_id: "aula-jul20" },
  { pt: "Eu sou grato", en: "I am grateful", category_id: "aula-jul20" },
  { pt: "Besteira", en: "Nonsense / Silly thing", category_id: "aula-jul20" },
  { pt: "Pelo / Por", en: "Through/by the (masc.) / By, for", category_id: "aula-jul20" },
  { pt: "Saudade de", en: "Missing / Longing for", category_id: "aula-jul20" },
  { pt: "Nossos / Nossas", en: "Our (masc. pl.) / Our (fem. pl.)", category_id: "aula-jul20" },
  { pt: "Aeroporto / Avião", en: "Airport / Airplane", category_id: "aula-jul20" },
  { pt: "Aquecer / Aquecimento / Aquecedores", en: "To heat / Heating / Heaters", category_id: "aula-jul20" },
  { pt: "Eu confio em você", en: "I trust you (confiar em)", category_id: "aula-jul20" },
  { pt: "Fisioterapeuta", en: "Physical therapist", category_id: "aula-jul20" },
  { pt: "Você deveria fazer amizade com suas vizinhas", en: "You should make friends with your neighbors", category_id: "aula-jul20" },
  { pt: "Ficar amigos / Virar amigos", en: "To become friends", category_id: "aula-jul20" },
  { pt: "Construção", en: "Construction", category_id: "aula-jul20" },
  { pt: "Tirei", en: "I took (out) / I got (tirar)", category_id: "aula-jul20" },
  { pt: "Equilíbrio", en: "Balance", category_id: "aula-jul20" },
  { pt: "Doar", en: "To donate", category_id: "aula-jul20" },
  { pt: "Alcançar uma meta", en: "To reach a goal", category_id: "aula-jul20" },
  { pt: "Calça / Calças", en: "Pants", category_id: "aula-jul20" },
  { pt: "Ponte", en: "Bridge", category_id: "aula-jul20" },
  { pt: "Espetinho", en: "Skewer (street-food kebab)", category_id: "aula-jul20" },
  { pt: "São João / Festa Junina", en: "St. John's Day / June festival", category_id: "aula-jul20" },
  { pt: "Levar / Ela me levou", en: "To take (someone somewhere) / She took me", category_id: "aula-jul20" },
  { pt: "Devolver", en: "To return / To give back", category_id: "aula-jul20" },
  { pt: "Merecer", en: "To deserve", category_id: "aula-jul20" },
  { pt: "Chances", en: "Chances", category_id: "aula-jul20" },
  { pt: "Bater", en: "To hit / To knock", category_id: "aula-jul20" },
  { pt: "Comemorar", en: "To celebrate", category_id: "aula-jul20" },
  { pt: "Zoológicos", en: "Zoos", category_id: "aula-jul20" },
  { pt: "De graça", en: "For free", category_id: "aula-jul20" },
  { pt: "Tempestade", en: "Storm", category_id: "aula-jul20" },
  { pt: "Menos", en: "Less / Minus", category_id: "aula-jul20" },
  { pt: "Escutar", en: "To listen", category_id: "aula-jul20" },
  { pt: "Assunto", en: "Subject / Topic", category_id: "aula-jul20" },
  { pt: "Quebrada / Quebrar", en: "Broken (fem.) / To break", category_id: "aula-jul20" },
  { pt: "Estresse", en: "Stress", category_id: "aula-jul20" },
  { pt: "Leve / Leveza", en: "Light, mild / Lightness", category_id: "aula-jul20" },
  { pt: "Pintura", en: "Painting", category_id: "aula-jul20" },
  { pt: "Vista", en: "View", category_id: "aula-jul20" },
  { pt: "Fumar", en: "To smoke", category_id: "aula-jul20" },
  { pt: "No caminho da volta", en: "On the way back", category_id: "aula-jul20" },
  { pt: "Honestamente", en: "Honestly", category_id: "aula-jul20" },
  { pt: "Churrasco", en: "Barbecue", category_id: "aula-jul20" },
  { pt: "Carta / Cartas", en: "Letter / Letters", category_id: "aula-jul20" },
  { pt: "Uma hora de carro", en: "One hour by car", category_id: "aula-jul20" },
  { pt: "Doutor / Doutora", en: "Doctor (m.) / Doctor (f.)", category_id: "aula-jul20" },
  { pt: "Agonia", en: "Agony / Distress", category_id: "aula-jul20" },
  { pt: "Aparelho", en: "Device / Appliance / Braces", category_id: "aula-jul20" },
  { pt: "Inveja", en: "Envy", category_id: "aula-jul20" },
  { pt: "Resta", en: "Remains / Is left (restar)", category_id: "aula-jul20" },
  { pt: "Forma", en: "Shape / Form / Way", category_id: "aula-jul20" },
  { pt: "Curvado", en: "Bent / Hunched over", category_id: "aula-jul20" },
  { pt: "Avaliação", en: "Evaluation / Assessment", category_id: "aula-jul20" },
  { pt: "Segredo / Secreta", en: "Secret (noun) / Secret (adj., fem.)", category_id: "aula-jul20" }
];

module.exports = { categories: [category], cards };
