const CHUNK = 25;

const words = [
  { pt: "Ar condicionado", en: "Air conditioner" },
  { pt: "Consertado", en: "Fixed / Repaired" },
  { pt: "Fumaça", en: "Smoke" },
  { pt: "Incêndio", en: "Fire (blaze)" },
  { pt: "Incêndio florestal", en: "Forest fire / Wildfire" },
  { pt: "Pulmão / Pulmões", en: "Lung / Lungs" },
  { pt: "Pássaros / Aves", en: "Birds (songbirds) / Birds (in general)" },
  { pt: "Passarinho", en: "Little bird / Birdie" },
  { pt: "Doença / Doente", en: "Illness / Sick" },
  { pt: "Pombos", en: "Pigeons" },
  { pt: "Dentro da parede", en: "Inside the wall" },
  { pt: "Dentro do armário", en: "Inside the cabinet" },
  { pt: "Matar", en: "To kill" },
  { pt: "Formigas", en: "Ants" },
  { pt: "Caramujo", en: "Snail" },
  { pt: "Farmácia / Drogaria", en: "Pharmacy / Drugstore" },
  { pt: "Envenenado", en: "Poisoned" },
  { pt: "Morri", en: "I died" },
  { pt: "Da / Do / De", en: "Of the (fem.) / Of the (masc.) / Of, from" },
  { pt: "Noiva", en: "Bride / Fiancée" },
  { pt: "Psiquiatria", en: "Psychiatry" },
  { pt: "Acessar", en: "To access" },
  { pt: "Causar", en: "To cause" },
  { pt: "Dano", en: "Damage / Harm" },
  { pt: "Um dos melhores filmes já feitos", en: "One of the best movies ever made" },
  { pt: "Concordo", en: "I agree" },
  { pt: "Parceiro", en: "Partner" },
  { pt: "Parceiro de negócios", en: "Business partner" },
  { pt: "Sentir / Sentar", en: "To feel / To sit" },
  { pt: "Sinto / Sento", en: "I feel / I sit" },
  { pt: "Esperançoso / Esperançosamente", en: "Hopeful / Hopefully" },
  { pt: "Compromisso / Eu sou compromissado", en: "Commitment / I'm taken (in a relationship)" },
  { pt: "Sessão / Consulta", en: "Session / (Medical) appointment" },
  { pt: "Meta", en: "Goal / Target" },
  { pt: "Trapacear", en: "To cheat" },
  { pt: "Juízes", en: "Judges" },
  { pt: "Triste / Tristeza", en: "Sad / Sadness" },
  { pt: "Houve", en: "There was / There were" },
  { pt: "Abraço / Braço", en: "Hug / Arm" },
  { pt: "Pé / Pés", en: "Foot / Feet" },
  { pt: "Estressante", en: "Stressful" },
  { pt: "Chaminé", en: "Chimney" },
  { pt: "Resfriado / Gripe / Gripado", en: "Cold / Flu / Down with the flu" },
  { pt: "Estranho", en: "Strange / Weird" },
  { pt: "Tarde demais", en: "Too late" },
  { pt: "Remover", en: "To remove" },
  { pt: "Assim que acabar", en: "As soon as it's over" },
  { pt: "Roubo / Roubar", en: "Robbery / To steal" },
  { pt: "Começar", en: "To begin / To start" },
  { pt: "Teoria da conspiração", en: "Conspiracy theory" },
  { pt: "Contar", en: "To tell / To count" },
  { pt: "Alguma razão / Sem razão", en: "Some reason / No reason" },
  { pt: "Cadê", en: "Where is…?" },
  { pt: "Dormiu", en: "(You / He / She) slept" },
  { pt: "Sono", en: "Sleep / Sleepiness" },
  { pt: "Desistir de algo", en: "To give up on something" },
  { pt: "Nesse / Nessa", en: "In that (masc.) / In that (fem.)" },
  { pt: "Ensolarado", en: "Sunny" },
  { pt: "Placas", en: "Signs / License plates" },
  { pt: "Eu sou grato", en: "I am grateful" },
  { pt: "Besteira", en: "Nonsense / Silly thing" },
  { pt: "Pelo / Por", en: "Through/by the (masc.) / By, for" },
  { pt: "Saudade de", en: "Missing / Longing for" },
  { pt: "Nossos / Nossas", en: "Our (masc. pl.) / Our (fem. pl.)" },
  { pt: "Aeroporto / Avião", en: "Airport / Airplane" },
  { pt: "Aquecer / Aquecimento / Aquecedores", en: "To heat / Heating / Heaters" },
  { pt: "Eu confio em você", en: "I trust you (confiar em)" },
  { pt: "Fisioterapeuta", en: "Physical therapist" },
  { pt: "Você deveria fazer amizade com suas vizinhas", en: "You should make friends with your neighbors" },
  { pt: "Ficar amigos / Virar amigos", en: "To become friends" },
  { pt: "Construção", en: "Construction" },
  { pt: "Tirei", en: "I took (out) / I got (tirar)" },
  { pt: "Equilíbrio", en: "Balance" },
  { pt: "Doar", en: "To donate" },
  { pt: "Alcançar uma meta", en: "To reach a goal" },
  { pt: "Calça / Calças", en: "Pants" },
  { pt: "Ponte", en: "Bridge" },
  { pt: "Espetinho", en: "Skewer (street-food kebab)" },
  { pt: "São João / Festa Junina", en: "St. John's Day / June festival" },
  { pt: "Levar / Ela me levou", en: "To take (someone somewhere) / She took me" },
  { pt: "Devolver", en: "To return / To give back" },
  { pt: "Merecer", en: "To deserve" },
  { pt: "Chances", en: "Chances" },
  { pt: "Bater", en: "To hit / To knock" },
  { pt: "Comemorar", en: "To celebrate" },
  { pt: "Zoológicos", en: "Zoos" },
  { pt: "De graça", en: "For free" },
  { pt: "Tempestade", en: "Storm" },
  { pt: "Menos", en: "Less / Minus" },
  { pt: "Escutar", en: "To listen" },
  { pt: "Assunto", en: "Subject / Topic" },
  { pt: "Quebrada / Quebrar", en: "Broken (fem.) / To break" },
  { pt: "Estresse", en: "Stress" },
  { pt: "Leve / Leveza", en: "Light, mild / Lightness" },
  { pt: "Pintura", en: "Painting" },
  { pt: "Vista", en: "View" },
  { pt: "Fumar", en: "To smoke" },
  { pt: "No caminho da volta", en: "On the way back" },
  { pt: "Honestamente", en: "Honestly" },
  { pt: "Churrasco", en: "Barbecue" },
  { pt: "Carta / Cartas", en: "Letter / Letters" },
  { pt: "Uma hora de carro", en: "One hour by car" },
  { pt: "Doutor / Doutora", en: "Doctor (m.) / Doctor (f.)" },
  { pt: "Agonia", en: "Agony / Distress" },
  { pt: "Aparelho", en: "Device / Appliance / Braces" },
  { pt: "Inveja", en: "Envy" },
  { pt: "Resta", en: "Remains / Is left (restar)" },
  { pt: "Forma", en: "Shape / Form / Way" },
  { pt: "Curvado", en: "Bent / Hunched over" },
  { pt: "Avaliação", en: "Evaluation / Assessment" },
  { pt: "Segredo / Secreta", en: "Secret (noun) / Secret (adj., fem.)" }
];

const categories = [];
const cards = [];

for (let i = 0; i < words.length; i += CHUNK) {
  const n = i / CHUNK + 1;
  const id = `aula-jul20-${n}`;
  categories.push({ id, label: `Aula Jul 20 (${n})`, css_class: "cat-aula-jul20", group_name: "Aulas" });
  cards.push(...words.slice(i, i + CHUNK).map(w => ({ ...w, category_id: id })));
}

module.exports = { categories, cards };
