const category = { id: "ir-phrases", label: "IR Phrases", css_class: "cat-ir-phrases", group_name: "IR" };

const cards = [
  { pt: "Eu ia ao trabalho de ônibus.", en: "I used to go to work by bus.", category_id: "ir-phrases" },
  { pt: "Você ia à escola a pé?", en: "Did you used to go to school on foot?", category_id: "ir-phrases" },
  { pt: "Ele ia ao mercado todo dia.", en: "He used to go to the market every day.", category_id: "ir-phrases" },
  { pt: "Ela ia à praia sempre.", en: "She always used to go to the beach.", category_id: "ir-phrases" },
  { pt: "Nós íamos estudar juntos.", en: "We used to study together.", category_id: "ir-phrases" },
  { pt: "Vocês iam ao curso à noite?", en: "Did you (pl.) used to go to the course at night?", category_id: "ir-phrases" },
  { pt: "Eles iam ao cinema com frequência.", en: "They used to go to the movies often.", category_id: "ir-phrases" },
  { pt: "Elas iam à academia antes.", en: "They (f.) used to go to the gym before.", category_id: "ir-phrases" },
  { pt: "Eu fui ao Brasil no ano passado.", en: "I went to Brazil last year.", category_id: "ir-phrases" },
  { pt: "Você foi ao evento ontem?", en: "Did you go to the event yesterday?", category_id: "ir-phrases" },
  { pt: "Ele foi ao trabalho cedo.", en: "He went to work early.", category_id: "ir-phrases" },
  { pt: "Ela foi ao médico ontem.", en: "She went to the doctor yesterday.", category_id: "ir-phrases" },
  { pt: "Nós fomos à praia ontem.", en: "We went to the beach yesterday.", category_id: "ir-phrases" },
  { pt: "Vocês foram ao show?", en: "Did you (pl.) go to the show?", category_id: "ir-phrases" },
  { pt: "Eles foram ao hotel.", en: "They went to the hotel.", category_id: "ir-phrases" },
  { pt: "Elas foram ao aeroporto.", en: "They (f.) went to the airport.", category_id: "ir-phrases" },
  { pt: "Eu vou ao trabalho todos os dias.", en: "I go to work every day.", category_id: "ir-phrases" },
  { pt: "Você vai à aula agora?", en: "Are you going to class now?", category_id: "ir-phrases" },
  { pt: "Ele vai ao mercado.", en: "He goes to the market.", category_id: "ir-phrases" },
  { pt: "Ela vai à praia hoje.", en: "She's going to the beach today.", category_id: "ir-phrases" },
  { pt: "Nós vamos viajar amanhã.", en: "We're going to travel tomorrow.", category_id: "ir-phrases" },
  { pt: "Vocês vão ao restaurante?", en: "Are you (pl.) going to the restaurant?", category_id: "ir-phrases" },
  { pt: "Eles vão ao cinema.", en: "They're going to the movies.", category_id: "ir-phrases" },
  { pt: "Elas vão à academia.", en: "They (f.) are going to the gym.", category_id: "ir-phrases" },
  { pt: "Eu irei ao Brasil em julho.", en: "I will go to Brazil in July.", category_id: "ir-phrases" },
  { pt: "Você irá à aula amanhã?", en: "Will you go to class tomorrow?", category_id: "ir-phrases" },
  { pt: "Ele irá ao trabalho mais tarde.", en: "He will go to work later.", category_id: "ir-phrases" },
  { pt: "Ela irá ao mercado depois.", en: "She will go to the market later.", category_id: "ir-phrases" },
  { pt: "Nós iremos viajar nas férias.", en: "We will travel on vacation.", category_id: "ir-phrases" },
  { pt: "Vocês irão ao evento?", en: "Will you (pl.) go to the event?", category_id: "ir-phrases" },
  { pt: "Eles irão ao restaurante.", en: "They will go to the restaurant.", category_id: "ir-phrases" },
  { pt: "Elas irão ao show.", en: "They (f.) will go to the show.", category_id: "ir-phrases" },
  { pt: "Eu iria ao Brasil se tivesse tempo.", en: "I would go to Brazil if I had time.", category_id: "ir-phrases" },
  { pt: "Você iria comigo?", en: "Would you go with me?", category_id: "ir-phrases" },
  { pt: "Ele iria ao evento, mas trabalhou.", en: "He would go to the event, but he worked.", category_id: "ir-phrases" },
  { pt: "Ela iria à festa, porém ficou doente.", en: "She would go to the party, but she got sick.", category_id: "ir-phrases" },
  { pt: "Nós iríamos viajar este ano.", en: "We would travel this year.", category_id: "ir-phrases" },
  { pt: "Vocês iriam ao curso se fosse online?", en: "Would you (pl.) go to the course if it were online?", category_id: "ir-phrases" },
  { pt: "Eles iriam ao cinema ontem.", en: "They would go to the movies yesterday.", category_id: "ir-phrases" },
  { pt: "Elas iriam à praia, mas choveu.", en: "They (f.) would go to the beach, but it rained.", category_id: "ir-phrases" }
];

module.exports = { categories: [category], cards };
